import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Animated, Easing, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { PlusExperience } from '@/src/components/PlusExperience';
import { createSupportRequest, hasPlusEntitlement, loadLiveDashboard, updatePrivacySettings } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

const redirects:Record<string,string>={tags:'/tags',family:'/family',guest:'/guest',valet:'/modes',service:'/modes',routing:'/routing',emergency:'/emergency',timeline:'/timeline'};

export default function FeatureV054(){
  const {slug}=useLocalSearchParams<{slug?:string}>();
  const key=String(slug||'privacy');
  const redirect=redirects[key];
  const [data,setData]=useState<any>(null);
  const [busy,setBusy]=useState(false);
  const [subject,setSubject]=useState('');
  const [body,setBody]=useState('');
  const [privacy,setPrivacy]=useState({showPlate:true,showBrandModel:true,showColor:true});
  const enter=useRef(new Animated.Value(0)).current;
  useEffect(()=>{Animated.timing(enter,{toValue:1,duration:420,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start()},[enter]);
  useEffect(()=>{
    if(redirect){router.replace(redirect as any);return;}
    loadLiveDashboard().then(next=>{setData(next);const current=next.profile?.privacy_settings||{};setPrivacy({showPlate:current.showPlate!==false,showBrandModel:current.showBrandModel!==false,showColor:current.showColor!==false})}).catch(()=>router.replace('/auth'));
  },[redirect]);
  const plus=useMemo(()=>data?hasPlusEntitlement(data.profile,data.subscription):false,[data]);
  async function savePrivacy(){setBusy(true);try{await updatePrivacySettings(privacy);Alert.alert('Gizlilik güncellendi','QR/NFC ekranında gösterilecek araç alanları kaydedildi.')}catch(e:any){Alert.alert('Kaydedilemedi',String(e?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  async function sendSupport(){
    if(!subject.trim()||!body.trim())return Alert.alert('Eksik bilgi','Konu ve açıklama gerekli.');
    setBusy(true);
    try{await createSupportRequest(subject,body);setSubject('');setBody('');Alert.alert('Destek kaydı oluşturuldu','Talebin Destek Merkezi’ne kaydedildi. Admin kullanıcısına bildirim gönderildi.');}
    catch(e:any){Alert.alert('Gönderilemedi',String(e?.message||'İşlem başarısız.'))}
    finally{setBusy(false)}
  }
  if(redirect||!data)return <SafeAreaView style={s.safe}><AuroraBackground/><View style={s.loading}><ActivityIndicator color={palette.cyan}/></View></SafeAreaView>;
  const support=key==='support';const plusPage=key==='plus';const color=support?palette.blue:plusPage?palette.yellow:palette.green;
  const title=support?'Nasıl Yardımcı Olabiliriz?':plusPage?'DraBornPark+':'Gizlilik Merkezi';
  return <SafeAreaView style={s.safe}><AuroraBackground accent={color} secondary={support?palette.cyan:palette.purple}/><Animated.View style={{flex:1,opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <ScreenHeader title={title} eyebrow={support?'DESTEK MERKEZİ':plusPage?'PREMIUM EXPERIENCE':'PRIVACY FIRST'} accent={color} subtitle={support?'Etiket, park, bildirim veya hesap sorununu hesabına bağlı güvenli destek kaydıyla ilet.':plusPage?'14 günlük hediyeni, aktif haklarını ve Google Play abonelik seçeneklerini tek yerde yönet.':'QR/NFC ziyaretçisinin görebileceği araç alanlarını sen belirlersin.'}/>
    {plusPage?<PlusExperience data={data}/>:null}
    {support?<><View style={[s.hero,{borderColor:`${palette.blue}55`,backgroundColor:`${palette.blue}10`}]}><View style={[s.heroIcon,{backgroundColor:`${palette.blue}20`}]}><MaterialCommunityIcons name="lifebuoy" size={36} color={palette.blue}/><View style={s.heroDot}/></View><View style={{flex:1}}><Text style={s.heroKicker}>DRABORNPARK DESTEK</Text><Text style={s.heroTitle}>Sorununu doğru yere ulaştır.</Text><Text style={s.heroBody}>Destek kayıtların hesabına bağlı tutulur ve admin panelinden ayrıntılı olarak incelenir.</Text></View></View><SectionHeading title="Yeni destek kaydı" subtitle="Sorunu kısa ve anlaşılır şekilde anlat"/><View style={s.panel}><Field label="KONU" value={subject} set={setSubject} placeholder="Etiket aktivasyonu"/><Text style={s.label}>AÇIKLAMA</Text><TextInput value={body} onChangeText={setBody} multiline maxLength={2000} placeholder="Sorunu, gördüğün hatayı ve denediğin adımları anlat…" placeholderTextColor={palette.muted2} style={[s.input,s.area]}/><Button color={palette.blue} busy={busy} label="DESTEK KAYDI OLUŞTUR" onPress={sendSupport}/></View><View style={s.locked}><MaterialCommunityIcons name="bell-check-outline" size={23} color={palette.green}/><Text style={s.lockedText}>Yeni kayıt oluşturulduğunda admin kullanıcısına bildirim gönderilir. Bildirime dokunulduğunda kayıt ayrıntısı açılır.</Text></View></>:null}
    {!support&&!plusPage?<><View style={[s.hero,{borderColor:`${palette.green}45`,backgroundColor:`${palette.green}0E`}]}><View style={[s.heroIcon,{backgroundColor:`${palette.green}20`}]}><MaterialCommunityIcons name="shield-lock-outline" size={36} color={palette.green}/></View><View style={{flex:1}}><Text style={[s.heroKicker,{color:palette.green}]}>GİZLİLİK ÖNCELİKLİ</Text><Text style={s.heroTitle}>Kişisel bilgilerin varsayılan olarak kapalı.</Text><Text style={s.heroBody}>Telefon, e-posta, tam ad ve park geçmişi bu görünürlük seçeneklerinden bağımsız olarak kamusal değildir.</Text></View></View><SectionHeading title="Kamusal araç alanları" subtitle="Dış QR/NFC ekranında görünmesini istediğin bilgileri seç"/><View style={s.panel}><Toggle icon="card-account-details-outline" color={palette.cyan} title="Plaka" detail="Araç plakası gösterilsin" value={privacy.showPlate} set={v=>setPrivacy(c=>({...c,showPlate:v}))}/><Toggle icon="car-info" color={palette.blue} title="Marka ve model" detail="Araç marka/model bilgisi gösterilsin" value={privacy.showBrandModel} set={v=>setPrivacy(c=>({...c,showBrandModel:v}))}/><Toggle icon="palette-outline" color={palette.purple} title="Araç rengi" detail="Kayıtlı renk dış kullanıcıya gösterilsin" value={privacy.showColor} set={v=>setPrivacy(c=>({...c,showColor:v}))}/></View><View style={s.locked}><MaterialCommunityIcons name="lock" size={23} color={palette.green}/><Text style={s.lockedText}>Telefon, e-posta, tam ad ve park geçmişi hiçbir zaman bu görünürlük anahtarlarıyla açılmaz.</Text></View><Button color={palette.green} busy={busy} label="GİZLİLİĞİ KAYDET" onPress={savePrivacy}/></>:null}
  </ScrollView></Animated.View></SafeAreaView>;
}
function Toggle({icon,color,title,detail,value,set}:{icon:any;color:string;title:string;detail:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.toggle}><View style={[s.toggleIcon,{backgroundColor:`${color}18`}]}><MaterialCommunityIcons name={icon} size={23} color={color}/></View><View style={{flex:1}}><Text style={s.toggleTitle}>{title}</Text><Text style={s.toggleBody}>{detail}</Text></View><Switch value={value} onValueChange={set} trackColor={{false:'#315064',true:`${color}88`}} thumbColor={value?color:'#A9BBC6'}/></View>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={palette.muted2} style={s.input}/></View>}
function Button({color,busy,label,onPress}:{color:string;busy:boolean;label:string;onPress:()=>void}){return <Pressable disabled={busy} onPress={onPress} style={[s.button,{backgroundColor:color},busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><Text style={s.buttonText}>{label}</Text><MaterialCommunityIcons name="arrow-right" size={21} color={palette.ink}/></>}</Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:70},loading:{flex:1,alignItems:'center',justifyContent:'center'},hero:{minHeight:160,borderRadius:radius.xl,borderWidth:1,padding:19,flexDirection:'row',alignItems:'center',gap:15,overflow:'hidden'},heroIcon:{width:70,height:70,borderRadius:23,alignItems:'center',justifyContent:'center'},heroDot:{position:'absolute',right:7,top:7,width:10,height:10,borderRadius:5,backgroundColor:palette.green},heroKicker:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:1},heroTitle:{color:palette.text,fontSize:23,fontWeight:'900',lineHeight:28,marginTop:4},heroBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:6},panel:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,paddingHorizontal:16},toggle:{minHeight:88,borderBottomWidth:1,borderBottomColor:palette.lineSoft,flexDirection:'row',alignItems:'center',gap:12},toggleIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},toggleTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},toggleBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},locked:{marginTop:14,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0D`,padding:15,flexDirection:'row',gap:11},lockedText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19},label:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:13,marginBottom:7},input:{height:56,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},area:{height:150,textAlignVertical:'top',paddingTop:14},button:{height:63,borderRadius:20,marginTop:18,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},buttonText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'}});