import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { supabase } from '@/src/lib/supabase';
import { palette, radius, type } from '@/src/theme';

export default function AdminSupportScreen(){
  const {id}=useLocalSearchParams<{id?:string}>();const target=String(id||'');const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [authorized,setAuthorized]=useState(true);const [busy,setBusy]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const {data:admin,error:adminError}=await supabase.rpc('drabornpark_is_admin');if(adminError||!admin){setAuthorized(false);return;}const {data,error}=await supabase.rpc('dkd_drabornpark_admin_support_v054',{drabornpark_request_id:null});if(error)throw error;const list=data??[];setRows(target?[...list].sort((a:any,b:any)=>String(a.id)===target?-1:String(b.id)===target?1:0):list);}catch(e:any){Alert.alert('Destek kayıtları açılamadı',e?.message||'İşlem başarısız.');}finally{setLoading(false)}},[target]);
  useEffect(()=>{void load()},[load]);
  async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
  async function status(row:any,next:string){setBusy(row.id);try{const {data,error}=await supabase.rpc('dkd_drabornpark_admin_support_mark_v054',{drabornpark_request_id:row.id,drabornpark_status:next});if(error)throw error;if(data)await load();}catch(e:any){Alert.alert('Durum değiştirilemedi',e?.message||'İşlem başarısız.');}finally{setBusy(null)}}
  if(loading)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.blue}/><View style={s.loading}><ActivityIndicator color={palette.cyan}/><Text style={s.loadingText}>Destek kayıtları yükleniyor…</Text></View></SafeAreaView>;
  if(!authorized)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.red}/><View style={s.denied}><MaterialCommunityIcons name="shield-lock-outline" size={48} color={palette.red}/><Text style={s.deniedTitle}>Admin erişimi gerekli</Text><Text style={s.deniedBody}>Bu ekran yalnızca DraBornPark admin hesabına açıktır.</Text><Pressable onPress={()=>router.replace('/')} style={s.back}><Text style={s.backText}>ANA SAYFAYA DÖN</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.blue} secondary={palette.purple}/><ScrollView contentContainerStyle={s.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={palette.cyan}/>} showsVerticalScrollIndicator={false}>
    <ScreenHeader title="Admin Destek Merkezi" eyebrow="DRABORNPARK OPERASYON" accent={palette.blue} subtitle="Kullanıcıların oluşturduğu destek kayıtlarını ayrıntılı incele ve durumlarını yönet."/>
    <View style={s.stats}><Stat icon="inbox-arrow-down-outline" label="Toplam" value={rows.length} color={palette.cyan}/><Stat icon="alert-circle-outline" label="Açık" value={rows.filter(x=>x.status==='open').length} color={palette.orange}/><Stat icon="check-circle-outline" label="Çözüldü" value={rows.filter(x=>['resolved','closed'].includes(x.status)).length} color={palette.green}/></View>
    <SectionHeading title="Destek kayıtları" subtitle={target?'Bildirimden açılan kayıt en üstte gösteriliyor':'En yeni kayıtlar önce gösterilir'} badge={`${rows.length} KAYIT`} color={palette.blue}/>
    {rows.length?rows.map(row=><View key={row.id} style={[s.card,String(row.id)===target&&s.target]}><View style={s.cardHead}><View style={[s.cardIcon,{backgroundColor:`${String(row.id)===target?palette.pink:palette.blue}20`}]}><MaterialCommunityIcons name={String(row.id)===target?'bell-badge-outline':'lifebuoy'} size={28} color={String(row.id)===target?palette.pink:palette.blue}/></View><View style={{flex:1}}><Text style={s.subject}>{row.subject}</Text><Text style={s.owner}>{row.owner_username?`@${row.owner_username}`:row.owner_display_name||'Kullanıcı'} • {new Date(row.created_at).toLocaleString('tr-TR')}</Text></View><View style={[s.status,{borderColor:`${statusColor(row.status)}55`,backgroundColor:`${statusColor(row.status)}0D`}]}><Text style={[s.statusText,{color:statusColor(row.status)}]}>{statusLabel(row.status)}</Text></View></View><View style={s.divider}/><Text style={s.label}>AÇIKLAMA</Text><Text style={s.body}>{row.body}</Text><View style={s.meta}><MaterialCommunityIcons name="account-outline" size={17} color={palette.muted}/><Text style={s.metaText}>Kullanıcı ID: {String(row.owner_user_id).slice(0,8)}…</Text></View><Text style={s.label}>DURUMU GÜNCELLE</Text><View style={s.actions}><Action title="İnceleniyor" icon="eye-outline" color={palette.orange} disabled={busy===row.id} onPress={()=>status(row,'in_review')}/><Action title="Çözüldü" icon="check-decagram-outline" color={palette.green} disabled={busy===row.id} onPress={()=>status(row,'resolved')}/><Action title="Kapat" icon="archive-outline" color={palette.muted} disabled={busy===row.id} onPress={()=>status(row,'closed')}/></View></View>):<View style={s.empty}><MaterialCommunityIcons name="inbox-check-outline" size={42} color={palette.green}/><Text style={s.emptyTitle}>Destek kaydı yok</Text><Text style={s.emptyBody}>Yeni kullanıcı talebi geldiğinde burada görünecek.</Text></View>}
  </ScrollView></SafeAreaView>;
}
function statusColor(status:string){if(status==='open')return palette.orange;if(status==='in_review')return palette.cyan;if(status==='resolved')return palette.green;return palette.muted}
function statusLabel(status:string){return status==='open'?'AÇIK':status==='in_review'?'İNCELENİYOR':status==='resolved'?'ÇÖZÜLDÜ':'KAPALI'}
function Stat({icon,label,value,color}:{icon:any;label:string;value:number;color:string}){return <View style={[s.stat,{borderColor:`${color}45`,backgroundColor:`${color}0D`}]}><MaterialCommunityIcons name={icon} size={23} color={color}/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
function Action({title,icon,color,disabled,onPress}:{title:string;icon:any;color:string;disabled:boolean;onPress:()=>void}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,{borderColor:`${color}45`,backgroundColor:`${color}0D`,opacity:disabled?.55:1}]}><MaterialCommunityIcons name={icon} size={19} color={color}/><Text style={[s.actionText,{color}]}>{title}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:70},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12},loadingText:{color:palette.muted,fontSize:type.body},denied:{flex:1,alignItems:'center',justifyContent:'center',padding:30},deniedTitle:{color:palette.text,fontSize:25,fontWeight:'900',marginTop:14},deniedBody:{color:palette.muted,fontSize:type.body,textAlign:'center',marginTop:7},back:{marginTop:20,borderRadius:18,backgroundColor:palette.red,paddingHorizontal:20,paddingVertical:14},backText:{color:palette.white,fontWeight:'900'},stats:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:112,borderRadius:22,borderWidth:1,padding:13},statValue:{color:palette.text,fontSize:25,fontWeight:'900',marginTop:10},statLabel:{color:palette.muted,fontSize:type.caption,marginTop:2},card:{marginTop:11,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:16},target:{borderColor:`${palette.pink}78`,backgroundColor:`${palette.pink}0B`},cardHead:{flexDirection:'row',alignItems:'flex-start',gap:11},cardIcon:{width:52,height:52,borderRadius:18,alignItems:'center',justifyContent:'center'},subject:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},owner:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},status:{borderRadius:999,borderWidth:1,paddingHorizontal:9,paddingVertical:6},statusText:{fontSize:9,fontWeight:'900'},divider:{height:1,backgroundColor:palette.lineSoft,marginVertical:14},label:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:9,marginBottom:6},body:{color:palette.text,fontSize:type.body,lineHeight:23},meta:{marginTop:12,flexDirection:'row',alignItems:'center',gap:6},metaText:{color:palette.muted2,fontSize:type.micro},actions:{flexDirection:'row',gap:7},action:{flex:1,minHeight:54,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center',gap:4,padding:6},actionText:{fontSize:9,fontWeight:'900',textAlign:'center'},empty:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:35,alignItems:'center'},emptyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:12},emptyBody:{color:palette.muted,fontSize:type.caption,marginTop:5}});