import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { addFamilyMember, hasPlusEntitlement, loadLiveDashboard, removeFamilyMember, updateFamilyMember } from '@/src/lib/drabornpark';
import { palette, radius } from '@/src/theme';

export default function FamilyScreen() {
  const [data,setData]=useState<any>(null); const [email,setEmail]=useState(''); const [name,setName]=useState(''); const [canPark,setCanPark]=useState(false); const [canNotify,setCanNotify]=useState(true); const [busy,setBusy]=useState(false);
  async function refresh(){try{setData(await loadLiveDashboard())}catch{router.replace('/auth')}} useEffect(()=>{refresh()},[]);
  const plus=data?hasPlusEntitlement(data.profile,data.subscription):false;
  async function invite(){if(!plus)return Alert.alert('DraBornPark+ gerekli','Family Plus kapsamındadır.');if(!email.trim())return Alert.alert('E-posta gerekli');setBusy(true);try{await addFamilyMember({email,displayName:name,canViewPark:canPark,canReceiveNotifications:canNotify});setEmail('');setName('');Alert.alert('Davet oluşturuldu','Aile üyesi izinleri kaydedildi.');await refresh()}catch(e:any){Alert.alert('Davet oluşturulamadı',String(e?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  async function toggle(id:string,patch:any){try{await updateFamilyMember(id,patch);await refresh()}catch(e:any){Alert.alert('Güncellenemedi',String(e?.message||'İşlem başarısız.'))}}
  async function remove(id:string){try{await removeFamilyMember(id);await refresh()}catch(e:any){Alert.alert('Silinemedi',String(e?.message||'İşlem başarısız.'))}}
  if(!data)return <SafeAreaView style={s.safe}><View style={s.loader}><ActivityIndicator color={palette.purple}/></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><Header/><Text style={s.over}>DRABORNPARK+ • AİLE ARAÇ AĞI</Text><Text style={s.title}>Family</Text><Text style={s.sub}>Aile üyelerini davet et; her kişi için son park konumu ve araç bildirimlerini ayrı ayrı aç veya kapat.</Text>{!plus?<View style={s.locked}><MaterialCommunityIcons name="lock-outline" size={20} color={palette.yellow}/><Text style={s.lockText}>Family ayarlarını değiştirmek için aktif Plus gerekir.</Text></View>:null}
  <View style={s.form}><Text style={s.formTitle}>Yeni aile üyesi</Text><Text style={s.label}>E-POSTA</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="aile@mail.com" placeholderTextColor="#627087" style={s.input}/><Text style={s.label}>GÖRÜNEN AD</Text><TextInput value={name} onChangeText={setName} placeholder="Eşim" placeholderTextColor="#627087" style={s.input}/><RowToggle label="Son park konumunu görebilsin" value={canPark} set={setCanPark}/><RowToggle label="Araç bildirimlerini alabilsin" value={canNotify} set={setCanNotify}/><Pressable disabled={busy||!plus} onPress={invite} style={[s.cta,(busy||!plus)&&{opacity:.5}]}>{busy?<ActivityIndicator color={palette.bg}/>:<><MaterialCommunityIcons name="account-plus-outline" size={20} color={palette.bg}/><Text style={s.ctaText}>DAVET OLUŞTUR</Text></>}</Pressable></View>
  <Text style={s.section}>ÜYELER VE İZİNLER</Text>{data.family.length===0?<Text style={s.empty}>Henüz Family üyesi yok.</Text>:data.family.map((item:any)=><View key={item.id} style={s.member}><View style={s.memberHead}><View style={s.avatar}><MaterialCommunityIcons name="account" size={21} color={palette.purple}/></View><View style={{flex:1}}><Text style={s.memberTitle}>{item.display_name||item.invite_email||'Aile üyesi'}</Text><Text style={s.memberSub}>{item.status.toUpperCase()} • {item.invite_email||'Hesap eşleşti'}</Text></View><Pressable onPress={()=>Alert.alert('Family üyesini kaldır',item.display_name||item.invite_email,[{text:'Vazgeç',style:'cancel'},{text:'Kaldır',style:'destructive',onPress:()=>remove(item.id)}])} style={s.delete}><MaterialCommunityIcons name="trash-can-outline" size={17} color={palette.red}/></Pressable></View><RowToggle label="Son parkı görebilsin" value={item.can_view_park} set={v=>toggle(item.id,{can_view_park:v})}/><RowToggle label="Bildirim alabilsin" value={item.can_receive_notifications} set={v=>toggle(item.id,{can_receive_notifications:v})}/></View>)}
  <View style={s.note}><MaterialCommunityIcons name="shield-lock-outline" size={19} color={palette.green}/><Text style={s.noteText}>Family üyesi izin verilse bile telefon numaranı, e-posta adresini veya özel hesap verilerini göremez. Park paylaşımı varsayılan olarak kapalıdır.</Text></View></ScrollView></SafeAreaView>}
function Header(){return <View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><MaterialCommunityIcons name="chevron-left" size={27} color={palette.text}/></Pressable><Text style={s.headerTitle}>DraBornPark Family</Text><View style={{width:42}}/></View>}
function RowToggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleText}>{label}</Text><Switch value={value} onValueChange={set} trackColor={{true:'#563C75'}} thumbColor={value?palette.purple:'#7D8798'}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:19,paddingBottom:55},loader:{flex:1,alignItems:'center',justifyContent:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},headerTitle:{color:palette.text,fontSize:14,fontWeight:'900'},over:{color:palette.purple,fontSize:8.5,fontWeight:'900',letterSpacing:1.4,marginTop:25},title:{color:palette.text,fontSize:30,fontWeight:'900',letterSpacing:-1,marginTop:5},sub:{color:palette.muted,fontSize:11.5,lineHeight:17,marginTop:7},locked:{marginTop:14,borderRadius:17,borderWidth:1,borderColor:'#514A25',backgroundColor:'#211F14',padding:13,flexDirection:'row',gap:9},lockText:{color:'#B9B286',fontSize:10,flex:1},form:{marginTop:15,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15},formTitle:{color:palette.text,fontSize:15,fontWeight:'900'},label:{color:'#7E8A9F',fontSize:8.5,fontWeight:'900',letterSpacing:1.1,marginTop:13,marginBottom:6},input:{height:48,borderRadius:14,borderWidth:1,borderColor:'#27324A',backgroundColor:'#090E18',color:palette.text,paddingHorizontal:13,fontSize:12},toggle:{minHeight:49,borderBottomWidth:1,borderBottomColor:'#171F31',flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},toggleText:{color:palette.text,fontSize:10.5,fontWeight:'800',flex:1},cta:{height:54,borderRadius:16,backgroundColor:palette.purple,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:16},ctaText:{color:palette.bg,fontSize:9.5,fontWeight:'900'},section:{color:palette.text,fontSize:14,fontWeight:'900',marginTop:23,marginBottom:8},empty:{color:palette.muted,fontSize:10.5},member:{borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:13,marginBottom:8},memberHead:{flexDirection:'row',alignItems:'center',gap:9},avatar:{width:40,height:40,borderRadius:14,backgroundColor:'#1D1528',alignItems:'center',justifyContent:'center'},memberTitle:{color:palette.text,fontSize:11.5,fontWeight:'900'},memberSub:{color:palette.muted,fontSize:8.8,marginTop:2},delete:{width:35,height:35,borderRadius:11,borderWidth:1,borderColor:'#4B2730',alignItems:'center',justifyContent:'center'},note:{marginTop:15,borderRadius:17,borderWidth:1,borderColor:'#234336',backgroundColor:'#0C1C16',padding:13,flexDirection:'row',gap:9},noteText:{color:'#8DBAA5',fontSize:9.5,lineHeight:14,flex:1}});
