import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { addFamilyMember, hasPlusEntitlement, loadLiveDashboard, removeFamilyMember, updateFamilyMember } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

export default function FamilyScreen(){
  const [data,setData]=useState<any>(null);const [email,setEmail]=useState('');const [name,setName]=useState('');const [canPark,setCanPark]=useState(false);const [canNotify,setCanNotify]=useState(true);const [busy,setBusy]=useState(false);
  async function refresh(){try{setData(await loadLiveDashboard())}catch{router.replace('/auth')}}useEffect(()=>{refresh()},[]);const plus=data?hasPlusEntitlement(data.profile,data.subscription):false;
  async function invite(){if(!plus)return Alert.alert('DraBornPark+ gerekli','Family Plus kapsamındadır.');if(!email.trim())return Alert.alert('E-posta gerekli');setBusy(true);try{await addFamilyMember({email,displayName:name,canViewPark:canPark,canReceiveNotifications:canNotify});setEmail('');setName('');Alert.alert('Davet oluşturuldu','Aile üyesi izinleri kaydedildi.');await refresh()}catch(e:any){Alert.alert('Davet oluşturulamadı',String(e?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  async function toggle(id:string,patch:any){try{await updateFamilyMember(id,patch);await refresh()}catch(e:any){Alert.alert('Güncellenemedi',String(e?.message||'İşlem başarısız.'))}}
  async function remove(id:string){try{await removeFamilyMember(id);await refresh()}catch(e:any){Alert.alert('Silinemedi',String(e?.message||'İşlem başarısız.'))}}
  if(!data)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple}/><View style={s.loading}><ActivityIndicator color={palette.purple}/><Text style={s.loadingText}>Family ağı yükleniyor…</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple} secondary={palette.green}/><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <ScreenHeader title="DraBornPark Family" eyebrow="AİLE ARAÇ AĞI" accent={palette.purple} subtitle="Park paylaşımı ve bildirim izinlerini kişi bazında yönet."/>
    {!plus?<View style={s.locked}><MaterialCommunityIcons name="lock-outline" size={24} color={palette.yellow}/><View style={{flex:1}}><Text style={s.lockTitle}>Family şu anda kilitli</Text><Text style={s.lockBody}>Yeni üye eklemek veya izin değiştirmek için aktif DraBornPark+ gerekir.</Text></View></View>:null}
    <SectionHeading title="Yeni aile üyesi" subtitle="Davet sırasında hangi izinlerin verileceğini seç"/>
    <View style={s.form}><Field label="E-POSTA" value={email} set={setEmail} placeholder="aile@mail.com" keyboard="email-address"/><Field label="GÖRÜNEN AD" value={name} set={setName} placeholder="Eşim"/><Permission icon="map-marker-outline" color={palette.cyan} title="Son park konumunu görebilsin" detail="Yalnızca kaydettiğin son park bilgisi" value={canPark} set={setCanPark}/><Permission icon="bell-outline" color={palette.orange} title="Araç bildirimlerini alabilsin" detail="Etiket üzerinden gelen olay bildirimleri" value={canNotify} set={setCanNotify}/><Pressable disabled={busy||!plus} onPress={invite} style={[s.cta,(busy||!plus)&&{opacity:.45}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><MaterialCommunityIcons name="account-plus-outline" size={23} color={palette.ink}/><Text style={s.ctaText}>AİLE ÜYESİ DAVET ET</Text></>}</Pressable></View>
    <SectionHeading title="Üyeler ve izinler" subtitle="Her üyeyi bağımsız yönet" badge={`${data.family.length} KİŞİ`} color={palette.purple}/>
    <View style={s.members}>{data.family.length?data.family.map((item:any)=><View key={item.id} style={s.member}><View style={s.memberHead}><View style={s.avatar}><MaterialCommunityIcons name="account" size={27} color={palette.purple}/></View><View style={{flex:1}}><Text style={s.memberTitle}>{item.display_name||item.invite_email||'Aile üyesi'}</Text><Text style={s.memberSub}>{item.status==='active'?'Aktif üye':'Davet bekliyor'} • {item.invite_email||'Hesap eşleşti'}</Text></View><Pressable onPress={()=>Alert.alert('Family üyesini kaldır',item.display_name||item.invite_email,[{text:'Vazgeç',style:'cancel'},{text:'Kaldır',style:'destructive',onPress:()=>remove(item.id)}])} style={s.delete}><MaterialCommunityIcons name="trash-can-outline" size={21} color={palette.red}/></Pressable></View><Permission icon="parking" color={palette.cyan} title="Son parkı görebilsin" detail="Family park paylaşımı" value={item.can_view_park} set={v=>toggle(item.id,{can_view_park:v})}/><Permission icon="bell-check-outline" color={palette.orange} title="Bildirim alabilsin" detail="Araç olayları kendisine yönlendirilebilir" value={item.can_receive_notifications} set={v=>toggle(item.id,{can_receive_notifications:v})}/></View>):<View style={s.empty}><MaterialCommunityIcons name="account-group-outline" size={38} color={palette.muted}/><Text style={s.emptyTitle}>Family üyesi yok</Text><Text style={s.emptyBody}>İlk aile üyesini davet ederek araç ağını paylaşabilirsin.</Text></View>}</View>
    <View style={s.note}><MaterialCommunityIcons name="shield-lock-outline" size={23} color={palette.green}/><Text style={s.noteText}>Family üyesi izin verilse bile telefon numaranı, e-posta adresini veya özel hesap verilerini göremez. Park paylaşımı varsayılan olarak kapalıdır.</Text></View>
  </ScrollView></SafeAreaView>;
}
function Field({label,value,set,placeholder,keyboard='default'}:{label:string;value:string;set:(v:string)=>void;placeholder:string;keyboard?:any}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} autoCapitalize={keyboard==='email-address'?'none':'sentences'} keyboardType={keyboard} placeholder={placeholder} placeholderTextColor={palette.muted2} style={s.input}/></View>}
function Permission({icon,color,title,detail,value,set}:{icon:any;color:string;title:string;detail:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.permission}><View style={[s.permissionIcon,{backgroundColor:`${color}18`}]}><MaterialCommunityIcons name={icon} size={22} color={color}/></View><View style={{flex:1}}><Text style={s.permissionTitle}>{title}</Text><Text style={s.permissionDetail}>{detail}</Text></View><Switch value={value} onValueChange={set} trackColor={{false:'#315064',true:`${color}88`}} thumbColor={value?color:'#A9BBC6'}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:50},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12},loadingText:{color:palette.muted,fontSize:type.body},locked:{minHeight:96,borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.yellow}45`,backgroundColor:`${palette.yellow}0E`,padding:16,flexDirection:'row',alignItems:'center',gap:12},lockTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},lockBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:4},form:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:17},label:{color:palette.purple,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:12,marginBottom:7},input:{height:56,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},permission:{minHeight:82,borderTopWidth:1,borderTopColor:palette.lineSoft,flexDirection:'row',alignItems:'center',gap:11,paddingVertical:12,marginTop:8},permissionIcon:{width:46,height:46,borderRadius:16,alignItems:'center',justifyContent:'center'},permissionTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},permissionDetail:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},cta:{height:62,borderRadius:20,backgroundColor:palette.purple,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9,marginTop:17},ctaText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},members:{gap:11},member:{borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.purple}38`,backgroundColor:palette.panel,padding:16},memberHead:{flexDirection:'row',alignItems:'center',gap:11},avatar:{width:54,height:54,borderRadius:18,backgroundColor:`${palette.purple}18`,alignItems:'center',justifyContent:'center'},memberTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},memberSub:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},delete:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:`${palette.red}40`,backgroundColor:`${palette.red}0E`,alignItems:'center',justifyContent:'center'},empty:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:28,alignItems:'center'},emptyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:10},emptyBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,textAlign:'center',marginTop:5},note:{marginTop:16,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0D`,padding:15,flexDirection:'row',gap:11},noteText:{color:palette.muted,fontSize:type.caption,lineHeight:19,flex:1}});
