import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, BottomDock, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { Pill, SafeIcon } from '@/src/components/Primitives';
import { palette, radius, type } from '@/src/theme';

type Item={title:string;subtitle:string;icon:string;color:string;route:string;keywords:string;badge?:string};
type Group={title:string;caption:string;color:string;items:Item[]};
const GROUPS:Group[]=[
 {title:'Araç & Park',caption:'Günlük kullanımın başladığı yer',color:palette.cyan,items:[
  {title:'Araçlarım',subtitle:'Araba ve motosiklet profilleri',icon:'car-multiple',color:palette.blue,route:'/vehicle',keywords:'araç araba motor'},
  {title:'Park Hafızası',subtitle:'GPS, kat, bölüm, fotoğraf ve bilet',icon:'map-marker-radius',color:palette.orange,route:'/park',keywords:'park konum otopark'},
  {title:'Etiketlerim',subtitle:'NFC + QR, aktivasyon ve devir',icon:'nfc',color:palette.cyan,route:'/tags',keywords:'nfc qr etiket aktivasyon devir'},
  {title:'Araç Geçmişi',subtitle:'Olay ve hareket geçmişi',icon:'history',color:palette.purple,route:'/timeline',keywords:'geçmiş olay'},
 ]},
 {title:'İletişim & Güvenlik',caption:'Numaranı göstermeden haber al',color:palette.orange,items:[
  {title:'Bildirim Merkezi',subtitle:'Araç bildirimleri ve hızlı cevaplar',icon:'bell-ring-outline',color:palette.orange,route:'/notifications',keywords:'bildirim cevap'},
  {title:'DraBornPark Aile',subtitle:'Aile park paylaşımı ve izinler',icon:'account-group-outline',color:palette.purple,route:'/family',keywords:'aile paylaşım'},
  {title:'Geçici Sürücü',subtitle:'Süreli bildirim yönlendirmesi',icon:'account-clock-outline',color:palette.green,route:'/guest',keywords:'geçici sürücü'},
  {title:'Acil Durum Zinciri',subtitle:'Öncelikli kişiler ve yüksek öncelik',icon:'shield-alert-outline',color:palette.red,route:'/emergency',keywords:'acil zincir'},
  {title:'Gizlilik & Veri',subtitle:'Paylaşımlar, izinler ve veri kontrolü',icon:'shield-lock-outline',color:palette.aqua,route:'/legal',keywords:'gizlilik veri'},
 ]},
 {title:'Akıllı Modlar',caption:'DraBornPark+ otomasyonları',color:palette.purple,items:[
  {title:'DraBornPark+',subtitle:'Aylık / yıllık Premium ve özellikler',icon:'crown-outline',color:palette.yellow,route:'/plus',keywords:'plus premium üyelik abonelik',badge:'PLUS'},
  {title:'Vale / Servis',subtitle:'Araç teslimi ve servis durumları',icon:'car-key',color:palette.cyan,route:'/modes',keywords:'vale servis',badge:'PLUS'},
  {title:'Zaman Kuralları',subtitle:'Gün ve saate göre yönlendir',icon:'calendar-clock-outline',color:palette.pink,route:'/routing',keywords:'zaman kural saat',badge:'PLUS'},
  {title:'Bildirim Ayarları',subtitle:'Sessiz saatler ve tercihler',icon:'tune-variant',color:palette.aqua,route:'/settings',keywords:'ayar bildirim'},
 ]},
 {title:'Hesap & Destek',caption:'Hesap, destek ve yasal alan',color:palette.blue,items:[
  {title:'Hesabım',subtitle:'Hesap, telefon, veri ve silme',icon:'account-circle-outline',color:palette.blue,route:'/account',keywords:'hesap telefon silme'},
  {title:'Destek Merkezi',subtitle:'Nasıl Yardımcı Olabiliriz?',icon:'lifebuoy',color:palette.purple,route:'/feature/support',keywords:'destek yardım'},
  {title:'Yasal & Gizlilik',subtitle:'Gizlilik, koşullar ve veri güvenliği',icon:'file-shield-outline',color:palette.green,route:'/legal',keywords:'yasal gizlilik'},
  {title:'Üretim Paneli',subtitle:'Etiket üretim ve doğrulama',icon:'factory',color:palette.orange,route:'/factory',keywords:'üretim etiket'},
 ]}
];
export default function HubScreen(){const [query,setQuery]=useState('');const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('tr-TR');if(!q)return GROUPS;return GROUPS.map(g=>({...g,items:g.items.filter(i=>`${i.title} ${i.subtitle} ${i.keywords}`.toLocaleLowerCase('tr-TR').includes(q))})).filter(g=>g.items.length)},[query]);return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple} secondary={palette.cyan}/><View style={s.flex}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><ScreenHeader back={false} title="Merkezim" eyebrow="" accent={palette.purple} subtitle="Araç, park, güvenlik ve hesabın tek anlaşılır merkezde" right={<Pill label="v0.6.0" color={palette.purple}/>}/><View style={s.hero}><View style={s.heroIcon}><SafeIcon name="view-dashboard-outline" size={38} color={palette.purple}/></View><View style={{flex:1}}><Text style={s.heroKicker}>KİŞİSEL ARAÇ AĞIN</Text><Text style={s.heroTitle}>Ne yapmak istiyorsun?</Text><Text style={s.heroBody}>Ara, kategori seç veya doğrudan karta dokun.</Text></View></View><View style={s.search}><SafeIcon name="magnify" size={23} color={palette.cyan}/><TextInput value={query} onChangeText={setQuery} placeholder="Park, etiket, aile, hesap…" placeholderTextColor={palette.muted2} style={s.searchInput}/>{query?<Pressable onPress={()=>setQuery('')}><SafeIcon name="close-circle" size={22} color={palette.muted}/></Pressable>:null}</View>{filtered.map(group=><View key={group.title}><SectionHeading title={group.title} subtitle={group.caption} badge={`${group.items.length} ÖZELLİK`} color={group.color}/><View style={s.grid}>{group.items.map(item=><Pressable key={item.title} onPress={()=>router.push(item.route as any)} style={[s.tile,{borderColor:`${item.color}55`,backgroundColor:`${item.color}0E`}]}><View style={s.tileTop}><View style={[s.tileIcon,{backgroundColor:`${item.color}1D`}]}><SafeIcon name={item.icon} size={31} color={item.color}/></View>{item.badge?<View style={[s.badge,{borderColor:`${item.color}50`}]}><Text style={[s.badgeText,{color:item.color}]}>{item.badge}</Text></View>:<SafeIcon name="arrow-top-right" size={20} color={item.color}/>}</View><Text style={s.tileTitle}>{item.title}</Text><Text style={s.tileBody}>{item.subtitle}</Text><View style={[s.tileLine,{backgroundColor:item.color}]}/></Pressable>)}</View></View>)}</ScrollView><BottomDock active="hub" floating/></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},flex:{flex:1},scroll:{padding:20,paddingBottom:145},hero:{minHeight:160,borderRadius:radius.xl,borderWidth:1,borderColor:`${palette.purple}55`,backgroundColor:`${palette.purple}0E`,padding:20,flexDirection:'row',alignItems:'center',gap:15},heroIcon:{width:74,height:74,borderRadius:25,backgroundColor:`${palette.purple}1D`,alignItems:'center',justifyContent:'center'},heroKicker:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:1.2},heroTitle:{color:palette.text,fontSize:27,fontWeight:'900',marginTop:5},heroBody:{color:palette.muted,fontSize:type.caption,marginTop:6},search:{height:62,borderRadius:21,borderWidth:1,borderColor:`${palette.cyan}48`,backgroundColor:palette.glassStrong,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:10,marginTop:14},searchInput:{flex:1,color:palette.text,fontSize:type.body},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},tile:{width:'48.4%',minHeight:188,borderRadius:27,borderWidth:1,padding:14,overflow:'hidden'},tileTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},tileIcon:{width:58,height:58,borderRadius:19,alignItems:'center',justifyContent:'center'},badge:{borderWidth:1,borderRadius:999,paddingHorizontal:8,paddingVertical:5},badgeText:{fontSize:9,fontWeight:'900'},tileTitle:{color:palette.text,fontSize:17,fontWeight:'900',marginTop:14},tileBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:5},tileLine:{position:'absolute',left:13,right:13,bottom:0,height:4,borderRadius:99}});