import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Easing, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, BottomDock, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { IconName, Pill } from '@/src/components/Primitives';
import { DemoSection, useDemo } from '@/src/demo/DemoContext';
import { calculateMonthlyInsights } from '@/src/lib/extras';
import { bootstrapProfile, hasPlusEntitlement, LiveDashboard, loadLiveDashboard } from '@/src/lib/drabornpark';
import { supabase } from '@/src/lib/supabase';
import { palette, radius, shadows, type } from '@/src/theme';

const quickLive:Array<{icon:IconName;color:string;title:string;detail:string;route:string}>=[
  {icon:'car-multiple',color:palette.blue,title:'Araçlarım',detail:'Araç ve motosiklet profilleri',route:'/vehicle'},
  {icon:'nfc',color:palette.cyan,title:'Etiketlerim',detail:'NFC + QR yönetimi',route:'/tags'},
  {icon:'history',color:palette.purple,title:'Timeline',detail:'Araç olay geçmişi',route:'/timeline'},
  {icon:'account-group-outline',color:palette.green,title:'Family',detail:'Aile araç ağı',route:'/family'},
];
const quickDemo:Array<{icon:IconName;color:string;title:string;detail:string;section:DemoSection}>=[
  {icon:'car-multiple',color:palette.blue,title:'Araçlarım',detail:'3 demo araç',section:'vehicles'},
  {icon:'nfc',color:palette.cyan,title:'Etiketlerim',detail:'NFC + QR',section:'tags'},
  {icon:'history',color:palette.purple,title:'Timeline',detail:'Araç olayları',section:'timeline'},
  {icon:'account-group-outline',color:palette.green,title:'Family',detail:'Aile araç ağı',section:'family'},
];

export default function HomeScreen(){
  const demo=useDemo();
  const [session,setSession]=useState<any>(null);
  const [live,setLive]=useState<LiveDashboard|null>(null);
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const enter=useRef(new Animated.Value(0)).current;
  const load=useCallback(async(current:any,silent=false)=>{if(!silent)setLoading(true);try{if(!current){setLive(null);return;}const name=current.user?.user_metadata?.display_name||current.user?.email?.split('@')[0]||undefined;await bootstrapProfile(name);setLive(await loadLiveDashboard());}finally{if(!silent)setLoading(false)}},[]);
  useEffect(()=>{let mounted=true;supabase.auth.getSession().then(async({data})=>{if(!mounted)return;setSession(data.session);await load(data.session)});const {data:listener}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);if(next)load(next);else{setLive(null);setLoading(false)}});Animated.timing(enter,{toValue:1,duration:520,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();return()=>{mounted=false;listener.subscription.unsubscribe()}},[enter,load]);
  async function refresh(){setRefreshing(true);try{if(session)await load(session,true);}finally{setRefreshing(false)}}
  async function signOut(){await supabase.auth.signOut();setSession(null);setLive(null)}
  if(loading)return <Loading/>;
  if(!session&&!demo.active)return <Welcome onDemo={()=>{demo.start();Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)}}/>;
  if(!session&&demo.active)return <DemoHome enter={enter}/>;
  return <LiveHome live={live} session={session} refresh={refresh} refreshing={refreshing} signOut={signOut} enter={enter}/>;
}

function Loading(){return <SafeAreaView style={s.safe}><AuroraBackground/><View style={s.loading}><View style={s.loadingLogo}><MaterialCommunityIcons name="shield-car" size={42} color={palette.cyan}/></View><ActivityIndicator color={palette.aqua}/><Text style={s.loadingTitle}>DraBornPark</Text><Text style={s.loadingText}>Araç ağın hazırlanıyor…</Text></View></SafeAreaView>}

function Welcome({onDemo}:{onDemo:()=>void}){return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple} secondary={palette.aqua}/><ScrollView contentContainerStyle={s.welcome} showsVerticalScrollIndicator={false}>
  <View style={s.welcomeBrand}><View style={s.welcomeLogo}><MaterialCommunityIcons name="shield-car" size={32} color={palette.cyan}/></View><View><Text style={s.brand}>DraBornPark</Text><Text style={s.brandSub}>PRIVATE VEHICLE NETWORK</Text></View><Pill label="v0.3.3" color={palette.purple}/></View>
  <Text style={s.welcomeKicker}>ARACINA NUMARANI DEĞİL</Text><Text style={s.welcomeTitle}>DraBornPark'ı bırak.</Text><Text style={s.welcomeBody}>Aracına ulaşılması gerektiğinde telefon numaranı göstermeden haber al. Park yerini hatırla, güvenlik olaylarını takip et, aile araçlarını tek yerden yönet.</Text>
  <View style={s.promiseRow}><Promise icon="phone-lock" color={palette.green} title="Numaran gizli"/><Promise icon="qrcode-scan" color={palette.cyan} title="QR + NFC"/><Promise icon="map-marker-check-outline" color={palette.orange} title="Park hafızası"/></View>
  <Pressable onPress={()=>router.push('/auth')} style={s.primary}><MaterialCommunityIcons name="shield-account-outline" size={24} color={palette.ink}/><View style={{flex:1}}><Text style={s.primaryTitle}>HESABIMA GİR / KAYIT OL</Text><Text style={s.primarySub}>Canlı DraBornPark hesabını kullan</Text></View><MaterialCommunityIcons name="arrow-right" size={23} color={palette.ink}/></Pressable>
  <Pressable onPress={onDemo} style={s.demoCta}><View style={s.demoIcon}><MaterialCommunityIcons name="flask-outline" size={25} color={palette.yellow}/></View><View style={{flex:1}}><Text style={s.demoTitle}>TAM DEMO MODUNU AÇ</Text><Text style={s.demoSub}>Tüm modülleri etkileşimli verilerle test et; canlı hesabın değişmez.</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={palette.yellow}/></Pressable>
</ScrollView></SafeAreaView>}

function Promise({icon,color,title}:{icon:IconName;color:string;title:string}){return <View style={[s.promise,{borderColor:`${color}40`,backgroundColor:`${color}0E`}]}><MaterialCommunityIcons name={icon} size={25} color={color}/><Text style={s.promiseText}>{title}</Text></View>}

function LiveHome({live,session,refresh,refreshing,signOut,enter}:{live:LiveDashboard|null;session:any;refresh:()=>void;refreshing:boolean;signOut:()=>void;enter:Animated.Value}){
  const vehicle=live?.vehicles?.[0];const tag=vehicle?live?.tags.find((x:any)=>x.vehicle_id===vehicle.id):live?.tags?.[0];const park=live?.parks?.find((x:any)=>!x.ended_at)??live?.parks?.[0];const unread=live?.reports?.filter((x:any)=>!x.seen_at).length??0;const plus=hasPlusEntitlement(live?.profile??null,live?.subscription??null);const insights=useMemo(()=>calculateMonthlyInsights(live?.parks??[],live?.reports??[]),[live]);
  const routeToPark=()=>router.push('/park');const goTo=()=>{if(park?.latitude&&park?.longitude)Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${park.latitude},${park.longitude}&travelmode=walking`)};
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.cyan} secondary={palette.purple}/><Animated.View style={{flex:1,opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[16,0]})}]}}><ScrollView contentContainerStyle={s.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={palette.cyan}/>} showsVerticalScrollIndicator={false}>
    <ScreenHeader back={false} title={`Merhaba, ${live?.profile?.display_name||session?.user?.email?.split('@')[0]||'DraBornPark'}`} eyebrow="GÜVENLİ ARAÇ AĞIN" accent={palette.cyan} right={<Pressable onPress={signOut} style={s.exit}><MaterialCommunityIcons name="logout" size={22} color={palette.muted}/></Pressable>}/>
    <VehicleHero vehicle={vehicle} tag={tag?.tag_code} plus={plus}/>
    <View style={s.actionRow}><BigAction icon="map-marker-plus" color={palette.cyan} title="PARK ETTİM" detail="Konumu ve otoparkı kaydet" onPress={routeToPark}/><BigAction icon="walk" color={palette.orange} title="ARACIMA GİT" detail={park?.place_name||'Aktif park yok'} onPress={goTo} disabled={!park?.latitude}/></View>
    {park?<ParkStrip park={park}/>:null}
    <SectionHeading title="Bugün" subtitle="Araç ağındaki en önemli durumlar" badge={`${unread} YENİ`} color={unread?palette.orange:palette.green}/>
    <View style={s.statusRow}><StatusTile icon="bell-outline" color={palette.orange} value={String(unread)} label="Yeni bildirim" onPress={()=>router.push('/notifications')}/><StatusTile icon="parking" color={palette.cyan} value={String(insights.parks)} label="Bu ay park" onPress={()=>router.push('/insights')}/><StatusTile icon="nfc" color={palette.green} value={tag?'AKTİF':'YOK'} label="Etiket" onPress={()=>router.push('/tags')}/></View>
    <SectionHeading title="Hızlı erişim" subtitle="Sık kullandığın DraBornPark merkezleri"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}>{quickLive.map(item=><QuickCard key={item.title} {...item} onPress={()=>router.push(item.route as any)}/>)}</ScrollView>
    <View style={s.splitRow}><Pressable onPress={()=>router.push('/insights')} style={[s.split,{borderColor:`${palette.aqua}45`,backgroundColor:`${palette.aqua}0E`}]}><MaterialCommunityIcons name="chart-donut" size={28} color={palette.aqua}/><Text style={s.splitTitle}>Aylık Özet</Text><Text style={s.splitBody}>{insights.favoritePlace} • {insights.averageParkMinutes?`${insights.averageParkMinutes} dk ort.`:'Yeni veriler bekleniyor'}</Text></Pressable><Pressable onPress={()=>router.push('/settings')} style={[s.split,{borderColor:`${palette.purple}45`,backgroundColor:`${palette.purple}0E`}]}><MaterialCommunityIcons name="tune-variant" size={28} color={palette.purple}/><Text style={s.splitTitle}>Ayarlar</Text><Text style={s.splitBody}>Bildirim, sessiz saatler ve kişisel tercihler</Text></Pressable></View>
    <SectionHeading title="Son araç olayı" subtitle="Timeline'dan en yeni kayıt"/>
    <Pressable onPress={()=>router.push('/timeline')} style={s.event}><View style={[s.eventIcon,{backgroundColor:`${palette.purple}18`}]}><MaterialCommunityIcons name="history" size={26} color={palette.purple}/></View><View style={{flex:1}}><Text style={s.eventTitle}>{live?.timeline?.[0]?.title||'Timeline henüz boş'}</Text><Text style={s.eventBody}>{live?.timeline?.[0]?.description||live?.timeline?.[0]?.event_type||'İlk park veya bildirimle araç geçmişin başlayacak.'}</Text></View><MaterialCommunityIcons name="arrow-right" size={22} color={palette.purple}/></Pressable>
    <BottomDock active="home"/>
  </ScrollView></Animated.View></SafeAreaView>;
}

function DemoHome({enter}:{enter:Animated.Value}){const demo=useDemo();const st=demo.state;const vehicle=st.vehicles.find((v:any)=>v.active)||st.vehicles[0];const park=st.parks.find((p:any)=>!p.endedAt)||st.parks[0];const unread=st.notifications.filter((n:any)=>!n.seen).length;const open=(section:DemoSection)=>router.push({pathname:'/demo/[section]',params:{section}} as any);return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.yellow} secondary={palette.cyan}/><Animated.View style={{flex:1,opacity:enter}}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
  <ScreenHeader back={false} title={`Merhaba, ${st.profile.displayName}`} eyebrow="ETKİLEŞİMLİ DEMO" accent={palette.yellow} right={<Pressable onPress={demo.stop} style={s.exit}><MaterialCommunityIcons name="close" size={23} color={palette.muted}/></Pressable>}/>
  <View style={s.demoNotice}><MaterialCommunityIcons name="flask-outline" size={24} color={palette.yellow}/><View style={{flex:1}}><Text style={s.demoNoticeTitle}>Tam Demo Workspace</Text><Text style={s.demoNoticeBody}>Yaptığın değişiklikler modüller arasında taşınır ama gerçek Supabase hesabını etkilemez.</Text></View><Pressable onPress={demo.reset} style={s.reset}><MaterialCommunityIcons name="refresh" size={20} color={palette.yellow}/></Pressable></View>
  <VehicleHero vehicle={{vehicle_name:vehicle.name,plate:vehicle.plate,brand:vehicle.brand,model:vehicle.model,color:vehicle.color,vehicle_type:vehicle.type}} tag={vehicle.tagCode} plus/>
  <View style={s.actionRow}><BigAction icon="map-marker-plus" color={palette.cyan} title="PARK ETTİM" detail="Demo park kaydı oluştur" onPress={()=>router.push('/park')}/><BigAction icon="qrcode-scan" color={palette.orange} title="DIŞ QR / NFC" detail="Araç dışı ekranı test et" onPress={()=>open('public')}/></View>
  <ParkStrip park={{place_name:park.placeName,floor_code:park.floor,zone_color:park.zoneColor,row_code:park.row,bay_code:park.bay}}/>
  <SectionHeading title="Demo Pulse" subtitle="Bu oturumdaki değişiklikler anında güncellenir" badge={`${unread} YENİ`} color={palette.yellow}/>
  <View style={s.statusRow}><StatusTile icon="bell-outline" color={palette.orange} value={String(unread)} label="Yeni bildirim" onPress={()=>open('notifications')}/><StatusTile icon="parking" color={palette.cyan} value={String(st.stats.parksThisMonth)} label="Bu ay park" onPress={()=>router.push('/insights')}/><StatusTile icon="shield-check-outline" color={palette.green} value={`${st.stats.privacyScore}%`} label="Gizlilik" onPress={()=>open('privacy')}/></View>
  <SectionHeading title="Hızlı erişim" subtitle="Demo modüllerini daha az kaydırmayla aç"/>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}>{quickDemo.map(item=><QuickCard key={item.title} icon={item.icon} color={item.color} title={item.title} detail={item.detail} onPress={()=>open(item.section)}/>)}</ScrollView>
  <View style={s.splitRow}><Pressable onPress={()=>router.push('/insights')} style={[s.split,{borderColor:`${palette.aqua}45`,backgroundColor:`${palette.aqua}0E`}]}><MaterialCommunityIcons name="chart-donut" size={28} color={palette.aqua}/><Text style={s.splitTitle}>Aylık Özet</Text><Text style={s.splitBody}>Demo istatistiklerini tam ekran incele</Text></Pressable><Pressable onPress={()=>router.push('/settings')} style={[s.split,{borderColor:`${palette.purple}45`,backgroundColor:`${palette.purple}0E`}]}><MaterialCommunityIcons name="tune-variant" size={28} color={palette.purple}/><Text style={s.splitTitle}>Ayarlar</Text><Text style={s.splitBody}>Bildirim ve sessiz saat ekranını test et</Text></Pressable></View>
  <BottomDock active="home" onHub={()=>router.push('/hub')}/>
</ScrollView></Animated.View></SafeAreaView>}

function VehicleHero({vehicle,tag,plus}:{vehicle:any;tag?:string;plus:boolean}){if(!vehicle)return <Pressable onPress={()=>router.push('/vehicle')} style={s.empty}><MaterialCommunityIcons name="car-plus" size={34} color={palette.cyan}/><Text style={s.emptyTitle}>İlk aracını ekle</Text><Text style={s.emptyBody}>Araç profilini oluştur ve DraBornPark etiketini bağla.</Text></Pressable>;return <View style={s.vehicleHero}><View style={s.vehicleHeroTop}><View style={s.carOrb}><MaterialCommunityIcons name={vehicle.vehicle_type==='motorcycle'?'motorbike':'car-sports'} size={34} color={palette.cyan}/></View><View style={{flex:1}}><Text style={s.vehicleName}>{vehicle.vehicle_name}</Text><Text style={s.vehiclePlate}>{vehicle.plate||'Plaka gizli'}</Text><Text style={s.vehicleMeta}>{[vehicle.brand,vehicle.model,vehicle.color].filter(Boolean).join(' • ')}</Text></View><Pill label={plus?'PLUS':'BASIC'} color={plus?palette.yellow:palette.blue} icon={plus?'crown-outline':'shield-outline'}/></View><View style={s.vehicleBottom}><View style={s.signal}><MaterialCommunityIcons name="nfc" size={21} color={palette.cyan}/><Text style={s.signalText}>{tag||'Etiket bağlanmadı'}</Text></View><View style={s.secure}><View style={s.greenDot}/><Text style={s.secureText}>GÜVENLİ BAĞLANTI</Text></View></View></View>}
function BigAction({icon,color,title,detail,onPress,disabled}:{icon:IconName;color:string;title:string;detail:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.bigAction,{borderColor:`${color}55`,backgroundColor:disabled?palette.panel:`${color}14`,opacity:disabled?.45:pressed?.76:1}]}><View style={[s.bigActionIcon,{backgroundColor:`${color}24`}]}><MaterialCommunityIcons name={icon} size={30} color={color}/></View><Text style={s.bigActionTitle}>{title}</Text><Text numberOfLines={2} style={s.bigActionBody}>{detail}</Text><MaterialCommunityIcons name="arrow-top-right" size={21} color={color} style={s.actionArrow}/></Pressable>}
function ParkStrip({park}:{park:any}){return <View style={s.parkStrip}><View style={s.parkIcon}><MaterialCommunityIcons name="map-marker-check" size={26} color={palette.orange}/></View><View style={{flex:1}}><Text style={s.parkLabel}>SON PARK</Text><Text style={s.parkTitle}>{park.place_name||'Kaydedilen konum'}</Text><Text style={s.parkBody}>{[park.floor_code,park.zone_color,`${park.row_code||''}${park.bay_code||''}`].filter(Boolean).join(' • ')||'GPS park konumu'}</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={palette.orange}/></View>}
function StatusTile({icon,color,value,label,onPress}:{icon:IconName;color:string;value:string;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.status,{borderColor:`${color}40`,backgroundColor:`${color}0E`}]}><MaterialCommunityIcons name={icon} size={24} color={color}/><Text style={s.statusValue}>{value}</Text><Text style={s.statusLabel}>{label}</Text></Pressable>}
function QuickCard({icon,color,title,detail,onPress}:{icon:IconName;color:string;title:string;detail:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.quick,{borderColor:`${color}45`,backgroundColor:`${color}0F`}]}><View style={[s.quickIcon,{backgroundColor:`${color}20`}]}><MaterialCommunityIcons name={icon} size={25} color={color}/></View><Text style={s.quickTitle}>{title}</Text><Text style={s.quickBody}>{detail}</Text><MaterialCommunityIcons name="arrow-right" size={20} color={color}/></Pressable>}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:22},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:13},loadingLogo:{width:76,height:76,borderRadius:26,borderWidth:1,borderColor:`${palette.cyan}55`,backgroundColor:`${palette.cyan}18`,alignItems:'center',justifyContent:'center'},loadingTitle:{color:palette.text,fontSize:type.section,fontWeight:'900'},loadingText:{color:palette.muted,fontSize:type.body},
  welcome:{padding:22,paddingTop:28,paddingBottom:54},welcomeBrand:{flexDirection:'row',alignItems:'center',gap:11},welcomeLogo:{width:55,height:55,borderRadius:19,borderWidth:1,borderColor:`${palette.cyan}55`,backgroundColor:`${palette.cyan}16`,alignItems:'center',justifyContent:'center'},brand:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},brandSub:{color:palette.muted2,fontSize:type.micro,fontWeight:'800',marginTop:2},welcomeKicker:{color:palette.aqua,fontSize:type.micro,fontWeight:'900',letterSpacing:1.5,marginTop:48},welcomeTitle:{color:palette.text,fontSize:38,fontWeight:'900',letterSpacing:-1.35,lineHeight:42,marginTop:8},welcomeBody:{color:palette.muted,fontSize:type.body,lineHeight:23,marginTop:14},promiseRow:{flexDirection:'row',gap:9,marginTop:28},promise:{flex:1,minHeight:105,borderWidth:1,borderRadius:radius.md,padding:13,justifyContent:'space-between'},promiseText:{color:palette.text,fontSize:type.caption,fontWeight:'900',lineHeight:18},primary:{minHeight:76,borderRadius:24,backgroundColor:palette.aqua,marginTop:28,paddingHorizontal:17,flexDirection:'row',alignItems:'center',gap:13},primaryTitle:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},primarySub:{color:'#285C58',fontSize:type.caption,marginTop:3},demoCta:{minHeight:91,borderRadius:24,borderWidth:1,borderColor:`${palette.yellow}50`,backgroundColor:`${palette.yellow}0E`,marginTop:13,padding:15,flexDirection:'row',alignItems:'center',gap:12},demoIcon:{width:52,height:52,borderRadius:18,backgroundColor:`${palette.yellow}20`,alignItems:'center',justifyContent:'center'},demoTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},demoSub:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},
  exit:{width:48,height:48,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,alignItems:'center',justifyContent:'center'},vehicleHero:{borderRadius:radius.xl,borderWidth:1,borderColor:`${palette.cyan}48`,backgroundColor:palette.panel,padding:18,...shadows.soft},vehicleHeroTop:{flexDirection:'row',alignItems:'center',gap:14},carOrb:{width:66,height:66,borderRadius:22,backgroundColor:`${palette.cyan}18`,borderWidth:1,borderColor:`${palette.cyan}38`,alignItems:'center',justifyContent:'center'},vehicleName:{color:palette.text,fontSize:23,fontWeight:'900',letterSpacing:-.5},vehiclePlate:{color:palette.cyan,fontSize:type.bodyStrong,fontWeight:'900',marginTop:3},vehicleMeta:{color:palette.muted,fontSize:type.caption,marginTop:4},vehicleBottom:{borderTopWidth:1,borderTopColor:palette.lineSoft,marginTop:17,paddingTop:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},signal:{flexDirection:'row',alignItems:'center',gap:8},signalText:{color:palette.text,fontSize:type.caption,fontWeight:'900'},secure:{flexDirection:'row',alignItems:'center',gap:6},greenDot:{width:8,height:8,borderRadius:4,backgroundColor:palette.green},secureText:{color:palette.green,fontSize:type.micro,fontWeight:'900'},empty:{minHeight:180,borderRadius:radius.xl,borderWidth:1,borderStyle:'dashed',borderColor:`${palette.cyan}55`,backgroundColor:`${palette.cyan}0A`,alignItems:'center',justifyContent:'center',padding:20},emptyTitle:{color:palette.text,fontSize:type.section,fontWeight:'900',marginTop:10},emptyBody:{color:palette.muted,fontSize:type.body,textAlign:'center',marginTop:5},
  actionRow:{flexDirection:'row',gap:11,marginTop:13},bigAction:{flex:1,minHeight:156,borderRadius:radius.lg,borderWidth:1,padding:15,overflow:'hidden'},bigActionIcon:{width:55,height:55,borderRadius:19,alignItems:'center',justifyContent:'center'},bigActionTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:15},bigActionBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4,paddingRight:16},actionArrow:{position:'absolute',right:14,top:16},parkStrip:{minHeight:94,borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.orange}42`,backgroundColor:`${palette.orange}0D`,marginTop:13,padding:15,flexDirection:'row',alignItems:'center',gap:12},parkIcon:{width:52,height:52,borderRadius:18,backgroundColor:`${palette.orange}20`,alignItems:'center',justifyContent:'center'},parkLabel:{color:palette.orange,fontSize:type.micro,fontWeight:'900',letterSpacing:.8},parkTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:2},parkBody:{color:palette.muted,fontSize:type.caption,marginTop:3},statusRow:{flexDirection:'row',gap:9},status:{flex:1,minHeight:128,borderRadius:radius.md,borderWidth:1,padding:14},statusValue:{color:palette.text,fontSize:23,fontWeight:'900',marginTop:13},statusLabel:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},quickRail:{gap:10,paddingRight:20},quick:{width:182,minHeight:162,borderRadius:radius.lg,borderWidth:1,padding:15},quickIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},quickTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:14},quickBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},quickCardArrow:{},splitRow:{flexDirection:'row',gap:11,marginTop:17},split:{flex:1,minHeight:150,borderRadius:radius.lg,borderWidth:1,padding:16},splitTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:14},splitBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:5},event:{minHeight:100,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15,flexDirection:'row',alignItems:'center',gap:13},eventIcon:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center'},eventTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},eventBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},
  demoNotice:{minHeight:94,borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.yellow}50`,backgroundColor:`${palette.yellow}0F`,padding:15,flexDirection:'row',alignItems:'center',gap:12,marginBottom:13},demoNoticeTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},demoNoticeBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},reset:{width:40,height:40,borderRadius:14,borderWidth:1,borderColor:`${palette.yellow}40`,alignItems:'center',justifyContent:'center'},
});
