import * as Haptics from 'expo-haptics';
import * as ImagePicker from 'expo-image-picker';
import { router, useFocusEffect } from 'expo-router';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Animated, Easing, Image, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, BottomDock, NotificationBell, SectionHeading } from '@/src/components/AppChrome';
import { ColorPopup } from '@/src/components/ColorPopup';
import { MetricChip, Pill, SafeIcon } from '@/src/components/Primitives';
import { calculateMonthlyInsights } from '@/src/lib/extras';
import { bootstrapProfile, hasPlusEntitlement, LiveDashboard, loadLiveDashboard, uploadProfileAvatar } from '@/src/lib/drabornpark';
import { supabase } from '@/src/lib/supabase';
import { palette, type } from '@/src/theme';

type Quick={icon:string;color:string;title:string;detail:string;route:string};
const quickItems:Quick[]=[
  {icon:'car-multiple',color:palette.blue,title:'Araçlarım',detail:'Araç profilleri',route:'/vehicle'},
  {icon:'nfc',color:palette.cyan,title:'Etiketler',detail:'NFC + QR',route:'/tags'},
  {icon:'account-group-outline',color:palette.purple,title:'Aile',detail:'Paylaşım ağı',route:'/family'},
  {icon:'history',color:palette.green,title:'Araç Geçmişi',detail:'Son olaylar',route:'/timeline'},
  {icon:'car-key',color:palette.orange,title:'Vale / Servis',detail:'Akıllı modlar',route:'/modes'},
];

export default function HomeScreen(){
  const [session,setSession]=useState<any>(null);
  const [live,setLive]=useState<LiveDashboard|null>(null);
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const enter=useRef(new Animated.Value(0)).current;

  const load=useCallback(async(current:any,silent=false)=>{
    if(!silent)setLoading(true);
    try{
      if(!current){setLive(null);return;}
      const username=current.user?.user_metadata?.username||current.user?.user_metadata?.display_name||current.user?.email?.split('@')[0]||undefined;
      await bootstrapProfile(username,username);
      setLive(await loadLiveDashboard());
    }catch(error:any){if(!silent)console.warn('[DraBornPark home]',error?.message||error)}finally{if(!silent)setLoading(false)}
  },[]);

  useEffect(()=>{
    let mounted=true;
    supabase.auth.getSession().then(async({data})=>{if(!mounted)return;setSession(data.session);await load(data.session)});
    const {data:listener}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);if(next)void load(next);else{setLive(null);setLoading(false)}});
    Animated.timing(enter,{toValue:1,duration:520,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();
    return()=>{mounted=false;listener.subscription.unsubscribe()};
  },[enter,load]);

  useFocusEffect(useCallback(()=>{if(session)void load(session,true);return undefined;},[load,session]));

  useEffect(()=>{
    const dkd_user_id=session?.user?.id;
    if(!dkd_user_id)return;
    const dkd_channel=supabase.channel(`dkd_home_sync_${dkd_user_id}`)
      .on('postgres_changes',{event:'*',schema:'public',table:'drabornpark_vehicles',filter:`owner_user_id=eq.${dkd_user_id}`},()=>{void load(session,true)})
      .on('postgres_changes',{event:'*',schema:'public',table:'drabornpark_tags',filter:`owner_user_id=eq.${dkd_user_id}`},()=>{void load(session,true)})
      .subscribe();
    return()=>{void supabase.removeChannel(dkd_channel)};
  },[load,session]);

  const refresh=async()=>{setRefreshing(true);try{if(session)await load(session,true)}finally{setRefreshing(false)}};
  const signOut=async()=>{await supabase.auth.signOut();setSession(null);setLive(null)};

  if(loading)return <Loading/>;
  if(!session)return <Welcome/>;
  return <LiveHome live={live} session={session} refresh={refresh} refreshing={refreshing} signOut={signOut} enter={enter}/>;
}

function Loading(){
  const spinOuter=useRef(new Animated.Value(0)).current;
  const spinInner=useRef(new Animated.Value(0)).current;
  const pulse=useRef(new Animated.Value(0)).current;
  const sweep=useRef(new Animated.Value(0)).current;
  const beat=useRef(new Animated.Value(0)).current;
  useEffect(()=>{
    const a=Animated.loop(Animated.timing(spinOuter,{toValue:1,duration:3400,easing:Easing.linear,useNativeDriver:true}));
    const b=Animated.loop(Animated.timing(spinInner,{toValue:1,duration:4700,easing:Easing.linear,useNativeDriver:true}));
    const c=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true})]));
    const d=Animated.loop(Animated.timing(sweep,{toValue:1,duration:2350,easing:Easing.linear,useNativeDriver:true}));
    const e=Animated.loop(Animated.sequence([Animated.timing(beat,{toValue:1,duration:620,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.timing(beat,{toValue:0,duration:820,easing:Easing.inOut(Easing.ease),useNativeDriver:true}),Animated.delay(420)]));
    a.start();b.start();c.start();d.start();e.start();return()=>{a.stop();b.stop();c.stop();d.stop();e.stop()};
  },[beat,pulse,spinInner,spinOuter,sweep]);
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.cyan} secondary={palette.purple}/><View style={s.loading}>
    <View style={s.loadingStage}>
      <Animated.View style={[s.loadingOrbitOuter,{transform:[{rotate:spinOuter.interpolate({inputRange:[0,1],outputRange:['0deg','360deg']})}]}]}><View style={[s.loadingOrbitNode,{backgroundColor:palette.pink,top:-5,left:72}]}/><View style={[s.loadingOrbitNode,{backgroundColor:palette.cyan,right:-5,top:72}]}/></Animated.View>
      <Animated.View style={[s.loadingOrbitInner,{transform:[{rotate:spinInner.interpolate({inputRange:[0,1],outputRange:['360deg','0deg']})}]}]}><View style={[s.loadingOrbitNodeSmall,{backgroundColor:palette.orange,left:-4,top:52}]}/><View style={[s.loadingOrbitNodeSmall,{backgroundColor:palette.green,right:4,bottom:-4}]}/></Animated.View>
      <View style={[s.loadingNode,s.loadingNodeA,{backgroundColor:palette.cyan}]}/><View style={[s.loadingNode,s.loadingNodeB,{backgroundColor:palette.purple}]}/><View style={[s.loadingNode,s.loadingNodeC,{backgroundColor:palette.orange}]}/><View style={[s.loadingNode,s.loadingNodeD,{backgroundColor:palette.green}]}/>
      <Animated.View style={[s.loadingCore,{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[.97,1.045]})}]}]}><Animated.View pointerEvents="none" style={[s.loadingCoreSweep,{transform:[{translateX:sweep.interpolate({inputRange:[0,1],outputRange:[-85,120]})},{rotate:'14deg'}]}]}/><View style={s.loadingCoreIcon}><SafeIcon name="car-connected" size={46} color={palette.cyan}/><Animated.View style={[s.loadingCoreDot,{opacity:beat.interpolate({inputRange:[0,1],outputRange:[.45,1]}),transform:[{scale:beat.interpolate({inputRange:[0,1],outputRange:[1,1.35]})}]}]}/></View><View style={s.loadingSignal}><View style={[s.loadingSignalBar,{height:8,backgroundColor:palette.blue}]}/><View style={[s.loadingSignalBar,{height:13,backgroundColor:palette.purple}]}/><View style={[s.loadingSignalBar,{height:18,backgroundColor:palette.cyan}]}/></View></Animated.View>
    </View>
    <View style={s.loadingBadge}><Animated.View style={[s.loadingBadgeDot,{opacity:beat.interpolate({inputRange:[0,1],outputRange:[.45,1]})}]}/><Text style={s.loadingBadgeText}>ARAÇ AĞI BAĞLANIYOR</Text></View>
    <Text style={s.loadingTitle}>DraBornPark</Text><Text style={s.loadingText}>Kişisel araç ağın, park hafızan ve güvenlik katmanın hazırlanıyor…</Text>
    <Animated.View style={[s.loadingSpectrum,{opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.58,1]})}]}><View style={[s.loadingSpectrumBar,{backgroundColor:palette.cyan}]}/><View style={[s.loadingSpectrumBar,{backgroundColor:palette.blue}]}/><View style={[s.loadingSpectrumBar,{backgroundColor:palette.purple}]}/><View style={[s.loadingSpectrumBar,{backgroundColor:palette.pink}]}/><View style={[s.loadingSpectrumBar,{backgroundColor:palette.orange}]}/><View style={[s.loadingSpectrumBar,{backgroundColor:palette.green}]}/></Animated.View>
  </View></SafeAreaView>;
}

function Welcome(){
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple} secondary={palette.cyan}/><ScrollView contentContainerStyle={s.welcome} showsVerticalScrollIndicator={false}>
    <View style={s.welcomeTop}><View style={s.brandOrb}><SafeIcon name="shield-car" size={30} color={palette.cyan}/></View><View style={{flex:1}}><Text style={s.brand}>DraBornPark</Text><Text style={s.brandSub}>KİŞİSEL ARAÇ AĞI</Text></View><Pill label="v1.0.23" color={palette.purple}/></View>
    <View style={s.welcomeHero}><Spectrum/><Text style={s.welcomeEyebrow}>ARACININ DİJİTAL KOKPİTİ</Text><Text style={s.welcomeTitle}>Park, güvenlik ve iletişim tek yerde.</Text><Text style={s.welcomeBody}>Telefon numaranı araçta bırakmadan ulaşılabilir ol. Park yerini hatırla, NFC + QR bildirimlerini yönet ve kişisel araç ağını güvenle kullan.</Text><View style={s.welcomePills}><StatusPill icon="phone-lock" text="NUMARA GİZLİ" color={palette.green}/><StatusPill icon="nfc" text="NFC + QR" color={palette.cyan}/></View></View>
    <View style={s.promiseGrid}><Promise icon="map-marker-radius" color={palette.orange} title="Park hafızası" body="GPS, kat, sıra ve park no."/><Promise icon="bell-badge-outline" color={palette.pink} title="Güvenli bildirim" body="Aracın için anonim haber al."/><Promise icon="account-group-outline" color={palette.purple} title="Aile paylaşımı" body="İzin verdiğin kişilerle paylaş."/><Promise icon="history" color={palette.green} title="Araç geçmişi" body="Park ve olayları tek yerde gör."/></View>
    <WelcomeAuthButton/>
  </ScrollView></SafeAreaView>;
}

function WelcomeAuthButton(){
  const pulse=useRef(new Animated.Value(0)).current;const sweep=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const p=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:820,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:820,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(450)]));const q=Animated.loop(Animated.timing(sweep,{toValue:1,duration:2400,easing:Easing.linear,useNativeDriver:true}));p.start();q.start();return()=>{p.stop();q.stop()};},[pulse,sweep]);
  return <Animated.View style={{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.012]})}]}}><Pressable onPress={()=>router.push('/auth')} style={({pressed})=>[s.primary,pressed&&s.pressed]}><Animated.View pointerEvents="none" style={[s.primarySweep,{transform:[{translateX:sweep.interpolate({inputRange:[0,1],outputRange:[-130,430]})},{rotate:'13deg'}]}]}/><View style={s.primaryIcon}><SafeIcon name="account-arrow-right-outline" size={28} color={palette.cyan}/><View style={s.primaryIconDot}/></View><View style={{flex:1,minWidth:0}}><Text style={s.primaryKicker}>GÜVENLİ HESAP</Text><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.82} style={s.primaryTitle}>GİRİŞ YAP / KAYIT OL</Text><Text style={s.primarySub}>Canlı hesabını aç</Text></View><Animated.View style={{transform:[{translateX:pulse.interpolate({inputRange:[0,1],outputRange:[0,5]})}]}}><SafeIcon name="arrow-right" size={27} color={palette.cyan}/></Animated.View><View style={s.primarySpectrum}><View style={[s.primaryBar,{backgroundColor:palette.cyan}]}/><View style={[s.primaryBar,{backgroundColor:palette.purple}]}/><View style={[s.primaryBar,{backgroundColor:palette.pink}]}/><View style={[s.primaryBar,{backgroundColor:palette.orange}]}/><View style={[s.primaryBar,{backgroundColor:palette.green}]}/></View></Pressable></Animated.View>;
}

function LiveHome({live,session,refresh,refreshing,signOut,enter}:{live:LiveDashboard|null;session:any;refresh:()=>Promise<void>;refreshing:boolean;signOut:()=>Promise<void>;enter:Animated.Value}){
  const [dockVisible,setDockVisible]=useState(false);
  const [premiumOpen,setPremiumOpen]=useState(false);
  const vehicle=live?.vehicles?.[0];
  const tag=vehicle?live?.tags.find((x:any)=>x.vehicle_id===vehicle.id):live?.tags?.[0];
  const park=live?.parks?.find((x:any)=>!x.ended_at)??live?.parks?.[0];
  const unread=live?.reports?.filter((x:any)=>!x.seen_at).length??0;
  const plus=hasPlusEntitlement(live?.profile??null,live?.subscription??null);
  const insights=useMemo(()=>calculateMonthlyInsights(live?.parks??[],live?.reports??[]),[live]);
  const name=live?.profile?.username||live?.profile?.display_name||session?.user?.user_metadata?.username||session?.user?.email?.split('@')[0]||'DraBornPark';
  const goToCar=()=>{if(park?.latitude&&park?.longitude)void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${park.latitude},${park.longitude}&travelmode=walking`)};
  const editAvatar=async()=>{try{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Fotoğraf izni gerekli','Profil resmini değiştirmek için fotoğraf arşivine erişim izni vermelisin.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'] as ImagePicker.MediaType[],allowsEditing:true,aspect:[1,1],quality:.82});if(result.canceled||!result.assets?.[0])return;const asset:any=result.assets[0];await uploadProfileAvatar({uri:asset.uri,mimeType:asset.mimeType,fileName:asset.fileName});await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);await refresh();}catch(error:any){Alert.alert('Profil resmi değiştirilemedi',error?.message||'Lütfen tekrar dene.')}};
  useEffect(()=>{
    if(!live||plus)return;
    const dkd_runtime=globalThis as any;
    if(dkd_runtime.__dkdPremiumPopupShownThisLaunch)return;
    dkd_runtime.__dkdPremiumPopupShownThisLaunch=true;
    const dkd_timer=setTimeout(()=>setPremiumOpen(true),420);
    return()=>clearTimeout(dkd_timer);
  },[live,plus]);

  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.cyan} secondary={palette.purple}/><Animated.View style={[s.flex,{opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[12,0]})}]}]}><ScrollView contentContainerStyle={s.scrollWithDock} showsVerticalScrollIndicator={false} onScroll={e=>setDockVisible(e.nativeEvent.contentOffset.y>28)} scrollEventThrottle={16} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()} tintColor={palette.cyan}/> }>
    <Greeting name={name} subtitle="Aracının bugünkü durumunu tek bakışta gör" avatarUrl={live?.profile?.avatar_url} onAvatarPress={editAvatar} onAccount={()=>router.push('/account')} unread={unread}/>
    <VehicleCore vehicle={vehicle} tag={tag?.tag_code} plus={plus}/>
    <SectionHeading title="Hızlı Erişim" subtitle="En sık kullandığın alanlar"/><QuickRail items={quickItems}/>
    <View style={s.primaryRow}><HeroAction icon="map-marker-plus-outline" color={palette.cyan} title="PARK ETTİM" detail="Konumu ve park detayını kaydet" onPress={()=>router.push('/park')}/><HeroAction icon="navigation-variant" color={palette.orange} title="ARACIMA GİT" detail={park?.place_name||'Aktif park yok'} onPress={goToCar} disabled={!park?.latitude}/></View>
    {park?<ParkPulse park={park}/>:null}
    <SectionHeading title="Bugünkü durum" subtitle="Önemli bilgilerin hızlı özeti" badge={unread?`${unread} YENİ`:'TEMİZ'} color={unread?palette.orange:palette.green}/><View style={s.metricRow}><MetricChip icon="bell-outline" color={palette.orange} value={String(unread)} label="Yeni bildirim"/><MetricChip icon="parking" color={palette.cyan} value={String(insights.parks)} label="Bu ay park"/><MetricChip icon="nfc" color={tag?palette.green:palette.muted} value={tag?'AKTİF':'YOK'} label="Etiket"/></View>
    <View style={s.featurePair}><PlusFeatureCard plus={plus}/><FeatureCard icon="view-grid-outline" color={palette.purple} title="Merkezim" body="Tüm özelliklere tek yerden ulaş" onPress={()=>router.push('/hub')}/></View>
    <SectionHeading title="Son olay" subtitle="Araç geçmişindeki en yeni kayıt"/><Pressable onPress={()=>router.push('/timeline')} style={({pressed})=>[s.event,pressed&&s.pressed]}><View style={s.eventIcon}><SafeIcon name="history" size={27} color={palette.pink}/></View><View style={{flex:1}}><Text style={s.eventTitle}>{live?.timeline?.[0]?.title||'Araç geçmişi henüz boş'}</Text><Text style={s.eventBody}>{live?.timeline?.[0]?.description||'İlk park veya araç bildiriminle geçmişin başlayacak.'}</Text></View><SafeIcon name="arrow-right" size={22} color={palette.pink}/></Pressable>
    <Pressable onPress={()=>void signOut()} style={s.signOut}><SafeIcon name="logout" size={20} color={palette.muted2}/><Text style={s.signOutText}>Oturumu kapat</Text></Pressable>
  </ScrollView><BottomDock active="home" onHub={()=>router.push('/hub')} transparent={!dockVisible} floating/><ColorPopup visible={premiumOpen} icon="shield-crown-outline" eyebrow="DRABORNPARK+ KORUMA" title="ARACINIZI KORUYUN" body="İçiniz rahat olsun. Premium Aboneliği alın, Bütün içeriklere Sahip Olun. DraBornPark+ ile aile paylaşımı, geçici sürücü, vale/servis, zaman kuralları ve gelişmiş araç korumasını açın." accent={palette.yellow} secondary={palette.pink} primaryLabel="PREMIUM'U İNCELE" onPrimary={()=>{setPremiumOpen(false);router.push('/feature/plus')}} secondaryLabel="ŞİMDİ DEĞİL" onSecondary={()=>setPremiumOpen(false)} chips={["TAM KORUMA","AYLIK + YILLIK","GOOGLE PLAY"]}/></Animated.View></SafeAreaView>;
}

function Greeting({name,subtitle,onAccount,avatarUrl,onAvatarPress,unread=0}:{name:string;subtitle:string;onAccount:()=>void;avatarUrl?:string|null;onAvatarPress?:()=>void;unread?:number}){
  const pulse=useRef(new Animated.Value(0)).current;useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:760,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:760,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(700)]));loop.start();return()=>loop.stop();},[pulse]);
  const avatar=<View style={[s.greetingAvatar,{borderColor:`${palette.pink}90`,backgroundColor:`${palette.pink}24`}]}>{avatarUrl?<Image source={{uri:avatarUrl}} style={s.avatarImage}/>:<SafeIcon name="account-circle-outline" size={39} color={palette.pink}/>}<View style={s.avatarDot}/><View style={s.avatarEdit}><SafeIcon name="camera-plus-outline" size={14} color={palette.ink}/></View></View>;
  return <View style={[s.greeting,{borderColor:`${palette.pink}82`}]}><Spectrum/><View style={s.greetingTopRow}><Pressable accessibilityLabel="Profil resmini değiştir" onPress={onAvatarPress}>{avatar}</Pressable><View style={s.greetingText}><Text style={[s.greetingEyebrow,{color:palette.pink}]}>KİŞİSEL KOKPİT</Text><Text numberOfLines={2} style={s.greetingName}>Merhaba, {name}</Text><Text style={s.greetingSub}>{subtitle}</Text></View><View style={s.greetingActions}><NotificationBell countOverride={unread}/><Animated.View style={{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.1]})}],opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.72,1]})}}><Pressable onPress={onAccount} style={[s.accountButton,{borderColor:`${palette.pink}88`,backgroundColor:`${palette.pink}20`}]}><SafeIcon name="account-cog-outline" size={24} color={palette.pink}/></Pressable></Animated.View></View></View><View style={s.greetingDivider}/><View style={s.badgeRow}><StatusPill compact offsetX={-4} textOffsetX={-3} icon="shield-check-outline" text="GÜVENLİ OTURUM" color={palette.green}/><StatusPill compact icon="car-connected" text="ARAÇ AĞI" color={palette.cyan}/><StatusPill compact icon="lock-check-outline" text="ÖZEL" color={palette.purple}/></View></View>;
}

function VehicleCore({vehicle,tag,plus}:{vehicle:any;tag?:string;plus:boolean}){
  const pulse=useRef(new Animated.Value(0)).current;const scan=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const p=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(240)]));const q=Animated.loop(Animated.timing(scan,{toValue:1,duration:2900,easing:Easing.linear,useNativeDriver:true}));p.start();q.start();return()=>{p.stop();q.stop()};},[pulse,scan]);
  if(!vehicle)return <Pressable onPress={()=>router.push('/vehicle')} style={s.emptyVehicle}><SafeIcon name="car-plus" size={40} color={palette.cyan}/><Text style={s.emptyTitle}>İlk aracını ekle</Text><Text style={s.emptyBody}>Araç profilini oluştur, ardından NFC + QR etiketini bağla.</Text><View style={s.emptyCta}><Text style={s.emptyCtaText}>ARAÇ EKLE</Text><SafeIcon name="arrow-right" size={19} color={palette.ink}/></View></Pressable>;
  const accent=vehicle.vehicle_type==='motorcycle'?palette.purple:palette.cyan;const tagColor=tag?palette.green:palette.orange;const meta=[vehicle.brand,vehicle.model,vehicle.color].filter(Boolean).join(' • ')||'Araç profili hazır';
  return <Animated.View style={[s.vehicleCore,{borderColor:accent+'A0',backgroundColor:vehicle.vehicle_type==='motorcycle'?'#130D24':'#061A27',transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.006]})}]}]}>
    <Animated.View pointerEvents="none" style={[s.vehicleGlow,{backgroundColor:accent+'18',opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.34,.62]}),transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[.92,1.08]})}]}]}/>
    <Animated.View pointerEvents="none" style={[s.vehicleSweep,{backgroundColor:'#FFFFFF10',transform:[{translateX:scan.interpolate({inputRange:[0,1],outputRange:[-120,700]})},{rotate:'13deg'}]}]}/><Spectrum/>
    <View style={s.vehicleHeader}><Animated.View style={[s.liveBadge,{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.03]})}]}]}><Animated.View style={[s.liveDot,{opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.42,1]})}]}/><Text style={s.liveOver}>•CANLI•</Text></Animated.View><Pill label={plus?'PLUS':'TEMEL'} color={plus?palette.yellow:palette.blue} icon={plus?'crown-outline':'shield-outline'}/></View>
    <View style={s.vehicleMinimalMain}><Animated.View style={[s.vehicleIconMini,{borderColor:accent+'90',backgroundColor:accent+'22',transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.055]})}]}]}><SafeIcon name={vehicle.vehicle_type==='motorcycle'?'motorbike':'car-connected'} size={32} color={accent}/><Animated.View style={[s.onlineDot,{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[.8,1.25]})}]}]}/></Animated.View><View style={{flex:1,minWidth:0}}><Text style={[s.coreEyebrow,{color:accent}]}>KİŞİSEL ARAÇ</Text><Text numberOfLines={1} style={s.coreName}>{vehicle.vehicle_name}</Text><Text numberOfLines={1} style={s.coreMeta}>{meta}</Text></View><Animated.View style={[s.vehicleShield,{opacity:pulse.interpolate({inputRange:[0,1],outputRange:[.62,1]})}]}><SafeIcon name="shield-check" size={24} color={palette.green}/></Animated.View></View>
    <View style={s.vehiclePills}><View style={[s.vehiclePill,{borderColor:accent+'58',backgroundColor:accent+'10'}]}><SafeIcon name="card-text-outline" size={14} color={accent}/><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.75} style={[s.vehiclePillText,{color:accent}]}>{vehicle.plate||'PLAKA GİZLİ'}</Text></View><View style={[s.vehiclePill,{borderColor:tagColor+'58',backgroundColor:tagColor+'10'}]}><SafeIcon name={tag?'nfc-variant':'qrcode-scan'} size={14} color={tagColor}/><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.72} style={[s.vehiclePillText,{color:tagColor}]}>{tag?'NFC + QR AKTİF':'ETİKET BEKLİYOR'}</Text></View><View style={[s.vehiclePill,{borderColor:palette.green+'58',backgroundColor:palette.green+'10'}]}><SafeIcon name="lock-check-outline" size={14} color={palette.green}/><Text style={[s.vehiclePillText,{color:palette.green}]}>ÖZEL</Text></View></View>
    <View style={s.vehicleBottomSpectrum}><View style={[s.bottomColor,{backgroundColor:accent,flex:2}]}/><View style={[s.bottomColor,{backgroundColor:palette.pink}]}/><View style={[s.bottomColor,{backgroundColor:palette.orange}]}/><View style={[s.bottomColor,{backgroundColor:palette.green}]}/></View>
  </Animated.View>;
}

function VehicleStatus({icon,label,value,color}:{icon:string;label:string;value:string;color:string}){return <View style={[s.vehicleStatus,{borderColor:color+'60',backgroundColor:color+'10'}]}><View style={[s.vehicleStatusIcon,{backgroundColor:color+'22'}]}><SafeIcon name={icon} size={19} color={color}/></View><View style={{flex:1,minWidth:0}}><Text style={s.vehicleStatusLabel}>{label}</Text><Text numberOfLines={1} style={[s.vehicleStatusValue,{color}]}>{value}</Text></View></View>}
function Spectrum(){return <View style={s.spectrum}><View style={[s.spectrumBar,{backgroundColor:palette.cyan}]}/><View style={[s.spectrumBar,{backgroundColor:palette.blue}]}/><View style={[s.spectrumBar,{backgroundColor:palette.pink}]}/><View style={[s.spectrumBar,{backgroundColor:palette.orange}]}/><View style={[s.spectrumBar,{backgroundColor:palette.green}]}/></View>}
function StatusPill({icon,text,color,compact=false,offsetX=0,textOffsetX=0}:{icon:string;text:string;color:string;compact?:boolean;offsetX?:number;textOffsetX?:number}){return <View style={[s.statusPill,{borderColor:color+'60',backgroundColor:color+'14',transform:[{translateX:offsetX}]},compact&&s.statusPillCompact]}><SafeIcon name={icon} size={compact?13:16} color={color}/><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.76} style={[s.statusPillText,{color},compact&&s.statusTextCompact,{transform:[{translateX:textOffsetX}]}]}>{text}</Text></View>}
function Promise({icon,color,title,body}:{icon:string;color:string;title:string;body:string}){return <View style={[s.promise,{borderColor:`${color}58`,backgroundColor:`${color}10`}]}><View style={[s.promiseIcon,{backgroundColor:`${color}22`}]}><SafeIcon name={icon} size={26} color={color}/></View><Text style={s.promiseTitle}>{title}</Text><Text style={s.promiseBody}>{body}</Text><View style={[s.cardLine,{backgroundColor:color}]}/></View>}
function QuickRail({items}:{items:Quick[]}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}>{items.map(item=><Pressable key={item.title} onPress={()=>router.push(item.route as any)} style={({pressed})=>[s.quickCard,{borderColor:`${item.color}68`,backgroundColor:`${item.color}12`},pressed&&s.pressed]}><View style={[s.quickIcon,{backgroundColor:`${item.color}26`,borderColor:`${item.color}60`}]}><SafeIcon name={item.icon} size={27} color={item.color}/></View><Text style={s.quickTitle}>{item.title}</Text><Text style={s.quickBody}>{item.detail}</Text><View style={s.quickFooter}><Text style={[s.quickOpen,{color:item.color}]}>AÇ</Text><SafeIcon name="arrow-right" size={18} color={item.color}/></View><View style={[s.cardLine,{backgroundColor:item.color}]}/></Pressable>)}</ScrollView>}
function HeroAction({icon,color,title,detail,onPress,disabled}:{icon:string;color:string;title:string;detail:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.heroAction,{borderColor:`${color}72`,backgroundColor:disabled?palette.panel:`${color}13`,opacity:disabled?.45:pressed?.72:1}]}><View style={[s.heroActionIcon,{backgroundColor:`${color}25`,borderColor:`${color}64`}]}><SafeIcon name={icon} size={31} color={color}/></View><Text style={s.heroActionTitle}>{title}</Text><Text numberOfLines={2} style={s.heroActionBody}>{detail}</Text><View style={[s.heroArrow,{borderColor:`${color}55`}]}><SafeIcon name="arrow-top-right" size={18} color={color}/></View><View style={[s.cardLine,{backgroundColor:color}]}/></Pressable>}
function FeatureCard({icon,color,title,body,onPress}:{icon:string;color:string;title:string;body:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[s.featureCard,{borderColor:`${color}68`,backgroundColor:`${color}12`},pressed&&s.pressed]}><View style={[s.featureIcon,{backgroundColor:`${color}26`}]}><SafeIcon name={icon} size={28} color={color}/></View><Text style={s.featureTitle}>{title}</Text><Text style={s.featureBody}>{body}</Text><SafeIcon name="arrow-top-right" size={19} color={color}/><View style={[s.cardLine,{backgroundColor:color}]}/></Pressable>}
function PlusFeatureCard({plus}:{plus:boolean}){const pulse=useRef(new Animated.Value(0)).current;const sweep=useRef(new Animated.Value(0)).current;useEffect(()=>{const a=Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:920,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:920,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(520)]));const b=Animated.loop(Animated.timing(sweep,{toValue:1,duration:2800,easing:Easing.linear,useNativeDriver:true}));a.start();b.start();return()=>{a.stop();b.stop()};},[pulse,sweep]);return <Animated.View style={{flex:1,transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.012]})}]}}><Pressable onPress={()=>router.push('/feature/plus')} style={({pressed})=>[s.featureCard,{flex:1,borderColor:palette.yellow+'86',backgroundColor:palette.yellow+'14',overflow:'hidden'},pressed&&s.pressed]}><Animated.View pointerEvents="none" style={{position:'absolute',top:-24,bottom:-24,width:62,backgroundColor:'#FFFFFF12',transform:[{translateX:sweep.interpolate({inputRange:[0,1],outputRange:[-90,360]})},{rotate:'14deg'}]}}/><View style={[s.featureIcon,{backgroundColor:palette.yellow+'28',borderWidth:1,borderColor:palette.orange+'72'}]}><SafeIcon name="crown-outline" size={30} color={palette.yellow}/></View><Text style={s.featureTitle}>DraBornPark+</Text><Text style={s.featureBody}>{plus?'Premium özelliklerin aktif':'14 gün hediye + Google Play planları'}</Text><Animated.View style={{transform:[{translateX:pulse.interpolate({inputRange:[0,1],outputRange:[0,5]})}]}}><SafeIcon name="arrow-top-right" size={19} color={palette.yellow}/></Animated.View><View style={[s.cardLine,{backgroundColor:palette.yellow}]}/></Pressable></Animated.View>}
function ParkPulse({park}:{park:any}){const slot=[park.floor_code?'Kat '+park.floor_code:null,park.zone_name||park.zone_color||null,park.row_code?'Sıra '+park.row_code:null,park.bay_code?'Park '+park.bay_code:null].filter(Boolean).join(' • ');const valid=Number.isFinite(Number(park.latitude))&&Number.isFinite(Number(park.longitude));const coordinates=valid?Number(park.latitude).toFixed(5)+', '+Number(park.longitude).toFixed(5):'';const actual=[park.place_name,slot].filter(Boolean).join(' • ')||coordinates||'Konum ayrıntısı kaydedilmedi';const accuracy=park.accuracy_meters?' • ±'+Math.round(Number(park.accuracy_meters))+' m':'';const detail=coordinates&&park.place_name?coordinates+accuracy:(slot||'Park hafızasındaki son kayıt');return <View style={s.parkPulse}><View style={s.parkPulseIcon}><SafeIcon name="map-marker-check" size={28} color={palette.orange}/></View><View style={{flex:1,minWidth:0}}><Text style={s.parkLabel}>SON PARK</Text><Text numberOfLines={2} style={s.parkTitle}>{actual}</Text><Text numberOfLines={1} style={s.parkBody}>{detail}</Text></View><SafeIcon name="chevron-right" size={24} color={palette.orange}/><View style={[s.cardLine,{backgroundColor:palette.orange}]}/></View>}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:palette.bg},flex:{flex:1},scrollWithDock:{padding:18,paddingBottom:132},pressed:{opacity:.75,transform:[{scale:.985}]},spectrum:{position:'absolute',left:18,right:18,top:0,height:4,flexDirection:'row',gap:4},spectrumBar:{flex:1,borderRadius:99},
  loading:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:24},loadingStage:{width:196,height:196,alignItems:'center',justifyContent:'center'},loadingOrbitOuter:{position:'absolute',width:158,height:158,borderRadius:79,borderWidth:2,borderColor:`${palette.cyan}62`,borderTopColor:palette.pink,borderRightColor:palette.purple,borderBottomColor:palette.green},loadingOrbitInner:{position:'absolute',width:126,height:126,borderRadius:63,borderWidth:2,borderColor:`${palette.blue}48`,borderTopColor:palette.orange,borderLeftColor:palette.cyan},loadingOrbitNode:{position:'absolute',width:10,height:10,borderRadius:5,borderWidth:2,borderColor:palette.bg},loadingOrbitNodeSmall:{position:'absolute',width:8,height:8,borderRadius:4,borderWidth:2,borderColor:palette.bg},loadingCore:{width:98,height:98,borderRadius:31,borderWidth:1,borderColor:`${palette.cyan}90`,backgroundColor:'#082C39',alignItems:'center',justifyContent:'center',overflow:'hidden'},loadingCoreSweep:{position:'absolute',top:-18,bottom:-18,width:48,backgroundColor:'#FFFFFF18'},loadingCoreIcon:{width:70,height:62,borderRadius:22,borderWidth:1,borderColor:`${palette.cyan}68`,backgroundColor:`${palette.cyan}16`,alignItems:'center',justifyContent:'center'},loadingCoreDot:{position:'absolute',right:7,top:7,width:9,height:9,borderRadius:5,backgroundColor:palette.green},loadingSignal:{height:20,flexDirection:'row',alignItems:'flex-end',gap:4,marginTop:5},loadingSignalBar:{width:5,borderRadius:4},loadingNode:{position:'absolute',width:9,height:9,borderRadius:3,borderWidth:1,borderColor:palette.bg},loadingNodeA:{left:18,top:86},loadingNodeB:{right:20,top:44},loadingNodeC:{right:26,bottom:30},loadingNodeD:{left:38,bottom:20},loadingBadge:{marginTop:8,borderRadius:999,borderWidth:1,borderColor:`${palette.green}58`,backgroundColor:`${palette.green}10`,paddingHorizontal:12,paddingVertical:7,flexDirection:'row',alignItems:'center',gap:7},loadingBadgeDot:{width:7,height:7,borderRadius:4,backgroundColor:palette.green},loadingBadgeText:{color:palette.green,fontSize:10,fontWeight:'900',letterSpacing:1.05},loadingTitle:{color:palette.text,fontSize:31,fontWeight:'900',marginTop:12,letterSpacing:-.8},loadingText:{maxWidth:330,color:'#C0CBDD',fontSize:type.body,lineHeight:22,marginTop:8,textAlign:'center'},loadingSpectrum:{width:236,height:5,flexDirection:'row',gap:4,marginTop:18},loadingSpectrumBar:{flex:1,borderRadius:99},
  welcome:{padding:20,paddingBottom:50},welcomeTop:{flexDirection:'row',alignItems:'center',gap:12},brandOrb:{width:58,height:58,borderRadius:19,borderWidth:1,borderColor:`${palette.cyan}68`,backgroundColor:`${palette.cyan}18`,alignItems:'center',justifyContent:'center'},brand:{color:palette.text,fontSize:21,fontWeight:'900'},brandSub:{color:palette.muted2,fontSize:type.micro,fontWeight:'900',letterSpacing:1},welcomeHero:{marginTop:22,borderRadius:32,borderWidth:1,borderColor:`${palette.purple}6A`,backgroundColor:palette.glass,padding:19,overflow:'hidden'},welcomeEyebrow:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:1.2,marginTop:17},welcomeTitle:{color:palette.text,fontSize:33,fontWeight:'900',lineHeight:38,letterSpacing:-1,marginTop:5},welcomeBody:{color:palette.muted,fontSize:type.body,lineHeight:23,marginTop:12},welcomePills:{flexDirection:'row',gap:8,marginTop:17},promiseGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:18},promise:{width:'48.4%',minHeight:154,borderRadius:24,borderWidth:1,padding:14,overflow:'hidden'},promiseIcon:{width:47,height:47,borderRadius:15,alignItems:'center',justifyContent:'center'},promiseTitle:{color:palette.text,fontSize:16,fontWeight:'900',marginTop:12},promiseBody:{color:palette.muted,fontSize:12.5,lineHeight:18,marginTop:5},primary:{minHeight:92,borderRadius:26,backgroundColor:'#092C39',borderWidth:1,borderColor:`${palette.cyan}88`,marginTop:20,padding:14,flexDirection:'row',alignItems:'center',gap:12,overflow:'hidden'},primarySweep:{position:'absolute',top:-18,bottom:-18,width:76,backgroundColor:'#FFFFFF18'},primaryIcon:{width:54,height:54,borderRadius:18,borderWidth:1,borderColor:`${palette.aqua}90`,backgroundColor:`${palette.aqua}20`,alignItems:'center',justifyContent:'center'},primaryIconDot:{position:'absolute',width:9,height:9,borderRadius:5,right:5,top:5,backgroundColor:palette.pink},primaryKicker:{color:palette.green,fontSize:10,fontWeight:'900',letterSpacing:1},primaryTitle:{color:palette.text,fontSize:20,fontWeight:'900',marginTop:2},primarySub:{color:palette.muted,fontSize:13,marginTop:2},primarySpectrum:{position:'absolute',left:14,right:14,bottom:0,height:4,flexDirection:'row',gap:4},primaryBar:{flex:1,borderRadius:99},
  greeting:{borderRadius:31,borderWidth:1,backgroundColor:'#1B0D2B',padding:16,overflow:'hidden'},greetingTopRow:{flexDirection:'row',alignItems:'center',gap:11,marginTop:12},greetingAvatar:{width:70,height:70,borderRadius:24,borderWidth:1,alignItems:'center',justifyContent:'center',overflow:'visible'},avatarImage:{width:'100%',height:'100%',borderRadius:23},avatarDot:{position:'absolute',right:4,bottom:4,width:12,height:12,borderRadius:7,backgroundColor:palette.green,borderWidth:2,borderColor:palette.bg},avatarEdit:{position:'absolute',right:-4,top:-5,width:26,height:26,borderRadius:9,backgroundColor:palette.aqua,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:palette.bg},greetingText:{flex:1,minWidth:0},greetingEyebrow:{fontSize:type.micro,fontWeight:'900',letterSpacing:1.4},greetingName:{fontSize:28,lineHeight:31,fontWeight:'900',color:palette.text,letterSpacing:-.8,marginTop:4},greetingSub:{color:palette.muted,fontSize:13.5,lineHeight:19,marginTop:7},greetingActions:{gap:7},accountButton:{width:44,height:44,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center'},greetingDivider:{height:1,backgroundColor:'#FFFFFF12',marginVertical:14},badgeRow:{flexDirection:'row',justifyContent:'space-between',gap:6},statusPill:{minHeight:36,borderRadius:999,borderWidth:1,paddingHorizontal:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},statusPillCompact:{flex:1,paddingHorizontal:7,minWidth:0},statusPillText:{fontSize:11.5,fontWeight:'900'},statusTextCompact:{fontSize:9.8},
  vehicleCore:{marginTop:14,borderRadius:25,borderWidth:1,padding:13,minHeight:180,overflow:'hidden'},vehicleGlow:{position:'absolute',width:180,height:180,borderRadius:90,right:-78,top:14},vehicleSweep:{position:'absolute',top:-90,bottom:-90,width:108},vehicleHeader:{marginTop:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},liveBadge:{minHeight:36,borderRadius:15,borderWidth:1,borderColor:palette.green+'72',backgroundColor:palette.green+'13',paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:7},liveDot:{width:8,height:8,borderRadius:4,backgroundColor:palette.green},liveOver:{color:palette.green,fontSize:11.5,fontWeight:'900',letterSpacing:1.5,textAlign:'center',lineHeight:14},liveText:{color:palette.green,fontSize:10.5,fontWeight:'900',marginTop:1},vehicleMinimalMain:{flexDirection:'row',alignItems:'center',gap:10,marginTop:11},vehicleIconMini:{width:60,height:60,borderRadius:20,borderWidth:1,alignItems:'center',justifyContent:'center'},onlineDot:{position:'absolute',right:5,bottom:5,width:11,height:11,borderRadius:6,backgroundColor:palette.green,borderWidth:2,borderColor:palette.bg},coreEyebrow:{fontSize:9.5,fontWeight:'900',letterSpacing:1.1},coreName:{fontSize:21,fontWeight:'900',color:palette.text,marginTop:2,letterSpacing:-.45},plateRow:{flexDirection:'row',alignItems:'center',gap:5,marginTop:4},corePlate:{fontSize:14,fontWeight:'900'},coreMeta:{color:palette.muted,fontSize:12,marginTop:4},vehicleShield:{width:38,height:38,borderRadius:13,borderWidth:1,borderColor:palette.green+'58',backgroundColor:palette.green+'10',alignItems:'center',justifyContent:'center'},vehiclePills:{flexDirection:'row',gap:6,marginTop:11},vehiclePill:{flex:1,minWidth:0,minHeight:34,borderRadius:12,borderWidth:1,paddingHorizontal:7,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5},vehiclePillText:{fontSize:9,fontWeight:'900'},vehicleCompactRow:{flexDirection:'row',gap:8,marginTop:10},vehicleStatus:{flex:1,minHeight:38,borderRadius:13,borderWidth:1,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:6},vehicleStatusIcon:{width:27,height:27,borderRadius:9,alignItems:'center',justifyContent:'center'},vehicleStatusLabel:{color:palette.muted2,fontSize:8,fontWeight:'900',letterSpacing:.4},vehicleStatusValue:{fontSize:9.8,fontWeight:'900',marginTop:1},vehicleBottomSpectrum:{position:'absolute',left:18,right:18,bottom:0,height:4,flexDirection:'row',gap:4},bottomColor:{flex:1,borderRadius:99},
  emptyVehicle:{marginTop:14,borderRadius:29,borderWidth:1,borderColor:`${palette.cyan}72`,backgroundColor:`${palette.cyan}10`,padding:22,alignItems:'center'},emptyTitle:{fontSize:22,fontWeight:'900',color:palette.text,marginTop:8},emptyBody:{color:palette.muted,textAlign:'center',lineHeight:21,marginTop:6},emptyCta:{marginTop:15,borderRadius:999,backgroundColor:palette.aqua,paddingHorizontal:18,paddingVertical:10,flexDirection:'row',gap:8},emptyCtaText:{color:palette.ink,fontWeight:'900'},
  quickRail:{gap:10,paddingRight:6},quickCard:{width:142,minHeight:152,borderRadius:24,borderWidth:1,padding:13,overflow:'hidden'},quickIcon:{width:50,height:50,borderRadius:17,borderWidth:1,alignItems:'center',justifyContent:'center'},quickTitle:{fontSize:16,fontWeight:'900',color:palette.text,marginTop:13},quickBody:{fontSize:12.5,color:palette.muted,marginTop:4},quickFooter:{marginTop:'auto',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},quickOpen:{fontSize:10,fontWeight:'900'},cardLine:{position:'absolute',left:18,right:18,bottom:0,height:4,borderRadius:99},primaryRow:{flexDirection:'row',gap:10,marginTop:16},heroAction:{flex:1,minHeight:170,borderRadius:26,borderWidth:1,padding:14,overflow:'hidden'},heroActionIcon:{width:56,height:56,borderRadius:18,borderWidth:1,alignItems:'center',justifyContent:'center'},heroActionTitle:{fontSize:18,fontWeight:'900',color:palette.text,marginTop:18},heroActionBody:{fontSize:13,color:palette.muted,lineHeight:19,marginTop:5},heroArrow:{position:'absolute',right:13,top:13,width:35,height:35,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},parkPulse:{marginTop:12,borderRadius:24,borderWidth:1,borderColor:`${palette.orange}62`,backgroundColor:`${palette.orange}10`,padding:14,flexDirection:'row',alignItems:'center',gap:12,overflow:'hidden'},parkPulseIcon:{width:48,height:48,borderRadius:16,backgroundColor:`${palette.orange}24`,alignItems:'center',justifyContent:'center'},parkLabel:{color:palette.orange,fontSize:10,fontWeight:'900'},parkTitle:{fontSize:16,fontWeight:'900',color:palette.text,marginTop:3},parkBody:{fontSize:12.5,color:palette.muted,marginTop:4},metricRow:{flexDirection:'row',gap:8},featurePair:{flexDirection:'row',gap:10,marginTop:14},featureCard:{flex:1,minHeight:156,borderRadius:25,borderWidth:1,padding:14,overflow:'hidden'},featureIcon:{width:50,height:50,borderRadius:17,alignItems:'center',justifyContent:'center'},featureTitle:{fontSize:17,fontWeight:'900',color:palette.text,marginTop:16},featureBody:{color:palette.muted,fontSize:12.5,lineHeight:18,marginTop:5,marginBottom:10},event:{minHeight:112,borderRadius:24,borderWidth:1,borderColor:`${palette.pink}62`,backgroundColor:`${palette.pink}10`,padding:14,flexDirection:'row',alignItems:'center',gap:12},eventIcon:{width:52,height:52,borderRadius:17,backgroundColor:`${palette.pink}24`,alignItems:'center',justifyContent:'center'},eventTitle:{fontSize:16,fontWeight:'900',color:palette.text},eventBody:{fontSize:12.5,color:palette.muted,lineHeight:18,marginTop:5},signOut:{alignSelf:'center',marginTop:26,flexDirection:'row',alignItems:'center',gap:8,padding:12},signOutText:{color:palette.muted2,fontSize:13,fontWeight:'900'},
});