import { router } from 'expo-router';
import React from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { Pill, SafeIcon } from '@/src/components/Primitives';
import { ACCOUNT_DELETION_URL, DATA_SAFETY_URL, PRIVACY_URL, SUPPORT_URL, TERMS_URL } from '@/src/lib/account';
import { palette, radius, type } from '@/src/theme';

const DATA=[
 {icon:'account-outline',color:palette.blue,title:'Hesap ve iletişim',body:'E-posta, kullanıcı adı, kayıt sırasında telefon numarası ve isteğe bağlı profil resmi. Telefon normal QR/NFC ziyaretçilerine gösterilmez.'},
 {icon:'car-outline',color:palette.cyan,title:'Araç bilgileri',body:'Araç adı, plaka, marka, model, renk ve araç tipi. Dış ekranda yalnızca gizlilik tercihlerinin izin verdiği alanlar gösterilir.'},
 {icon:'map-marker-radius-outline',color:palette.orange,title:'Park konumu',body:'Yalnızca Park Ettim akışında sen konumu kaydetmeyi seçtiğinde erişilir. Sürekli arka plan konum takibi yapılmaz.'},
 {icon:'camera-outline',color:palette.purple,title:'İsteğe bağlı görseller',body:'Profil, park yeri veya otopark bileti görselleri yalnızca sen eklemeyi seçersen işlenir.'},
 {icon:'message-text-outline',color:palette.pink,title:'QR/NFC iletişimi',body:'Bildirim türü, mesaj içeriği ve güvenli araç iletişimi. E-posta ve telefon ziyaretçiye açık edilmez.'},
 {icon:'cellphone-key',color:palette.green,title:'Cihaz ve güvenlik',body:'Push tokenı, platform/uygulama sürümü ve kötüye kullanım önleme için sınırlı teknik kayıtlar.'},
 {icon:'credit-card-check-outline',color:palette.yellow,title:'Abonelik durumu',body:'Google Play ürün kimliği, satın alma doğrulama tokenının hash’i, plan, süre bitişi ve yenileme durumu. Kart bilgisi DraBornPark’a gelmez.'},
];
export default function LegalScreen(){return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.green} secondary={palette.purple}/><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
 <ScreenHeader title="Gizlilik & Veri Merkezi" eyebrow="GİZLİLİK ÖNCELİKLİ" accent={palette.green} subtitle="DraBornPark hangi veriye neden erişir, kim işler ve nasıl silebilirsin?" right={<Pill label="v0.6.0" color={palette.green}/>}/>
 <View style={s.hero}><View style={s.heroIcon}><SafeIcon name="shield-lock-outline" size={39} color={palette.green}/></View><View style={{flex:1}}><Text style={s.heroKicker}>TEMEL PRENSİP</Text><Text style={s.heroTitle}>Kişisel iletişim bilgilerin aracın üzerinde değildir.</Text><Text style={s.heroBody}>Telefonun ve e-postan QR/NFC ziyaretçisine gösterilmez. Park geçmişin kamusal değildir. DraBornPark kullanıcı verilerini reklam amacıyla satmaz.</Text></View></View>
 <SectionHeading title="Erişilebilen veri grupları" subtitle="Özellik amacı dışında gereksiz veri istememeyi hedefler"/>
 <View style={s.dataGrid}>{DATA.map(x=><View key={x.title} style={[s.dataCard,{borderColor:`${x.color}42`,backgroundColor:`${x.color}0C`}]}><View style={[s.dataIcon,{backgroundColor:`${x.color}18`}]}><SafeIcon name={x.icon} size={25} color={x.color}/></View><Text style={s.dataTitle}>{x.title}</Text><Text style={s.dataBody}>{x.body}</Text></View>)}</View>
 <SectionHeading title="Konum izni" subtitle="Yalnızca kullanıcı tarafından başlatılan park özelliği" color={palette.orange}/><Policy icon="map-marker-check-outline" color={palette.orange} title="Park Ettim için konum" body="Mevcut konumuna yalnızca park noktasını kaydetmeyi seçtiğinde erişilir. Amaç park yerini saklamak ve Aracıma Git yönlendirmesini sağlamaktır; sürekli arka plan takibi yapılmaz."/>
 <SectionHeading title="DraBornPark+ ve Google Play" subtitle="Ödeme verisini DraBornPark toplamaz" color={palette.yellow}/><Policy icon="google-play" color={palette.yellow} title="Google Play Billing" body="Aylık/yıllık DraBornPark+ satın alımları Google Play tarafından işlenir. DraBornPark yalnızca üyelik yetkisini doğrulamak için ürün, plan, süre, yenileme ve token hash durumunu saklar."/><Policy icon="server-security" color={palette.green} title="Sunucu doğrulaması" body="Premium yetkisi yalnızca Google Play tarafından doğrulanmış aktif abonelik veya etiket aktivasyonuyla kazanılan 14 günlük deneme durumundan verilir."/>
 <SectionHeading title="Saklama ve kalıcı silme" subtitle="Hesabı dondurmak silme yerine kullanılmaz" color={palette.red}/><Policy icon="database-remove-outline" color={palette.red} title="Uygulama içinden veya webden silme" body="Hesap silme; profil, Auth hesabı ve hesaba bağlı araç, park, mesaj/bildirim, aile, geçici sürücü, push, destek, abonelik ve kullanıcı dosyalarını kaldırmak üzere tasarlanmıştır. Yasal veya güvenlik gerekçesiyle tutulması zorunlu kayıtlar varsa politika içinde açıkça belirtilir."/>
 <View style={s.noAds}><SafeIcon name="advertisements-off" size={26} color={palette.green}/><View style={{flex:1}}><Text style={s.noAdsTitle}>Reklam amacıyla veri satışı yok</Text><Text style={s.noAdsBody}>v0.6.0 kaynaklarında üçüncü taraf davranışsal reklam SDK’sı bulunmuyor. Bu durum değişirse uygulama politikası ve Play Console Data Safety beyanı yayın öncesinde güncellenmelidir.</Text></View></View>
 <Pressable onPress={()=>router.push('/account')} style={s.accountCta}><SafeIcon name="account-cog-outline" size={24} color={palette.ink}/><Text style={s.accountCtaText}>HESAP & VERİ İŞLEMLERİNİ AÇ</Text><SafeIcon name="arrow-right" size={21} color={palette.ink}/></Pressable>
 <SectionHeading title="Herkese açık belgeler" subtitle="Google Play incelemesi için uygulama olmadan da erişilebilir"/>
 <View style={s.links}><Link icon="file-lock-outline" color={palette.green} title="Gizlilik Politikası" url={PRIVACY_URL}/><Link icon="file-document-check-outline" color={palette.purple} title="Kullanım Koşulları" url={TERMS_URL}/><Link icon="shield-check-outline" color={palette.cyan} title="Veri Güvenliği" url={DATA_SAFETY_URL}/><Link icon="account-remove-outline" color={palette.red} title="Hesap Silme" url={ACCOUNT_DELETION_URL}/><Link icon="lifebuoy" color={palette.blue} title="Web Destek" url={SUPPORT_URL}/></View>
 <Text style={s.footer}>DraBornPark • v0.6.0 • Son güncelleme: 21 Ağustos 2026</Text>
 </ScrollView></SafeAreaView>}
function Policy({icon,color,title,body}:{icon:string;color:string;title:string;body:string}){return <View style={[s.policy,{borderColor:`${color}40`,backgroundColor:`${color}0A`}]}><View style={[s.policyIcon,{backgroundColor:`${color}18`}]}><SafeIcon name={icon} size={25} color={color}/></View><View style={{flex:1}}><Text style={s.policyTitle}>{title}</Text><Text style={s.policyBody}>{body}</Text></View></View>}
function Link({icon,color,title,url}:{icon:string;color:string;title:string;url:string}){return <Pressable onPress={()=>Linking.openURL(url)} style={[s.link,{borderColor:`${color}40`,backgroundColor:`${color}0D`}]}><SafeIcon name={icon} size={25} color={color}/><Text style={s.linkTitle}>{title}</Text><SafeIcon name="open-in-new" size={18} color={color}/></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:55},hero:{minHeight:190,borderRadius:radius.xl,borderWidth:1,borderColor:`${palette.green}4D`,backgroundColor:`${palette.green}0C`,padding:20,flexDirection:'row',alignItems:'center',gap:16},heroIcon:{width:76,height:76,borderRadius:26,backgroundColor:`${palette.green}18`,alignItems:'center',justifyContent:'center'},heroKicker:{color:palette.green,fontSize:type.micro,fontWeight:'900',letterSpacing:1},heroTitle:{color:palette.text,fontSize:25,fontWeight:'900',lineHeight:30,marginTop:5},heroBody:{color:palette.muted,fontSize:type.caption,lineHeight:20,marginTop:7},dataGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},dataCard:{width:'48.4%',minHeight:205,borderRadius:radius.md,borderWidth:1,padding:15},dataIcon:{width:49,height:49,borderRadius:16,alignItems:'center',justifyContent:'center'},dataTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900',marginTop:13},dataBody:{color:palette.muted,fontSize:type.caption,lineHeight:20,marginTop:6},policy:{borderRadius:radius.lg,borderWidth:1,padding:17,flexDirection:'row',gap:13,marginBottom:9},policyIcon:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center'},policyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},policyBody:{color:palette.muted,fontSize:type.caption,lineHeight:20,marginTop:5},noAds:{borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}42`,backgroundColor:`${palette.green}0C`,padding:15,flexDirection:'row',gap:12,marginTop:12},noAdsTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},noAdsBody:{color:palette.muted,fontSize:type.caption,lineHeight:20,marginTop:4},accountCta:{height:64,borderRadius:20,backgroundColor:palette.aqua,marginTop:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,paddingHorizontal:14},accountCtaText:{flex:1,color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900',textAlign:'center'},links:{gap:9},link:{minHeight:70,borderRadius:20,borderWidth:1,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:11},linkTitle:{flex:1,color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},footer:{color:palette.muted2,fontSize:type.caption,textAlign:'center',marginTop:28}});