import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, BottomDock, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { loadLiveDashboard, markReportSeen, quickReply } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

const replies=['Geliyorum','2 dakika','5 dakika','10 dakika','Şu anda hareket ettiremiyorum','Güvenliğe bilgi verebilirsiniz','Teşekkür ederim'];
const categoryNames:Record<string,string>={blocked_exit:'Çıkış engelleniyor',blocking_exit:'Çıkış engelleniyor',move_vehicle:'Aracı hareket ettir',lights_on:'Farlar açık',window_open:'Cam açık',door_open:'Kapı açık',trunk_open:'Bagaj açık',damage:'Hasar',suspicious:'Şüpheli durum',towing:'Araç çekiliyor',animal:'Araçta hayvan',child:'Araçta çocuk',fire:'Yangın şüphesi',forgotten_item:'Eşya / anahtar unutuldu',witness:'Tanık Modu',emergency:'Acil durum',other:'Araç bildirimi'};
const statusNames:Record<string,string>={new:'YENİ',seen:'OKUNDU',replied:'CEVAPLANDI',responded:'CEVAPLANDI',closed:'KAPALI',blocked:'ENGELLENDİ'};
export default function NotificationsScreen(){
  const [reports,setReports]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [sending,setSending]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const d=await loadLiveDashboard();setReports(d.reports);}catch{router.replace('/auth');}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
  async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
  async function seen(id:string){try{await markReportSeen(id);setReports(r=>r.map(x=>x.id===id?{...x,seen_at:new Date().toISOString(),status:x.status==='new'?'seen':x.status}:x));}catch(e:any){Alert.alert('İşlem başarısız',e?.message||'Bildirim güncellenemedi.')}}
  async function reply(report:any,text:string){setSending(report.id);try{await quickReply(report.id,text);Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);setReports(r=>r.map(x=>x.id===report.id?{...x,status:'replied',seen_at:x.seen_at||new Date().toISOString()}:x));Alert.alert('Cevap gönderildi','Karşı taraf anonim iletişim oturumu açıksa cevabını görebilir.');}catch(e:any){const msg=String(e?.message||'');Alert.alert(msg.includes('session_closed')?'Oturum kapandı':'Cevap gönderilemedi',msg.includes('session_closed')?'Geçici iletişim süresi dolmuş veya oturum kapanmış.':msg.includes('status_check')?'Bildirim durumu güncellenemedi. Lütfen tekrar deneyin.':msg);}finally{setSending(null)}}
  if(loading)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.orange}/><View style={s.loading}><ActivityIndicator color={palette.orange}/><Text style={s.loadingText}>Bildirim Merkezi açılıyor…</Text></View></SafeAreaView>;
  const unread=reports.filter(x=>!x.seen_at).length;const urgent=reports.filter(x=>x.priority==='emergency').length;const answered=reports.filter(x=>['replied','responded'].includes(String(x.status))).length;
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.orange} secondary={palette.pink}/><ScrollView contentContainerStyle={s.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={palette.orange}/>} showsVerticalScrollIndicator={false}>
    <ScreenHeader title="Bildirim Merkezi" eyebrow="ANONİM ARAÇ İLETİŞİMİ" accent={palette.orange} subtitle="QR/NFC üzerinden gelen olayları gör ve numaranı paylaşmadan cevap ver."/>
    <View style={s.stats}><Stat icon="bell-badge-outline" value={unread} label="Yeni" color={palette.orange}/><Stat icon="shield-alert-outline" value={urgent} label="Acil" color={palette.red}/><Stat icon="message-check-outline" value={answered} label="Cevaplandı" color={palette.green}/></View>
    <SectionHeading title="Gelen kutusu" subtitle="Yeni bildirimler üstte gösterilir" badge={`${reports.length} KAYIT`} color={palette.orange}/>
    {reports.length===0?<View style={s.empty}><View style={s.emptyIcon}><MaterialCommunityIcons name="bell-check-outline" size={38} color={palette.green}/></View><Text style={s.emptyTitle}>Her şey sakin</Text><Text style={s.emptyBody}>DraBornPark etiketin tarandığında güvenli araç bildirimleri burada görünecek.</Text></View>:reports.map(r=>{const color=r.priority==='emergency'?palette.red:r.priority==='high'?palette.orange:palette.cyan;return <View key={r.id} style={[s.card,{borderColor:!r.seen_at?`${color}65`:palette.line}]}><View style={s.cardHead}><View style={[s.icon,{backgroundColor:`${color}20`}]}><MaterialCommunityIcons name={r.priority==='emergency'?'alert-octagon-outline':'bell-ring-outline'} size={26} color={color}/></View><View style={{flex:1}}><Text style={s.category}>{categoryNames[r.category]||'Araç bildirimi'}</Text><Text style={s.time}>{new Date(r.created_at).toLocaleString('tr-TR')}</Text></View><View style={[s.status,{borderColor:`${color}50`,backgroundColor:`${color}10`}]}><Text style={[s.statusText,{color}]}>{statusNames[String(r.status||'new')]||'BİLDİRİM'}</Text></View></View><Text style={s.body}>{r.message_safe||'Aracınız için yeni bir bildirim gönderildi.'}</Text>{!r.seen_at?<Pressable onPress={()=>seen(r.id)} style={s.seen}><MaterialCommunityIcons name="check-all" size={19} color={palette.cyan}/><Text style={s.seenText}>Okundu işaretle</Text></Pressable>:null}<Text style={s.replyLabel}>HIZLI CEVAP</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.replyRail}>{replies.map(text=><Pressable disabled={sending===r.id} key={text} onPress={()=>reply(r,text)} style={s.reply}>{sending===r.id?<ActivityIndicator size="small" color={palette.green}/>:<Text style={s.replyText}>{text}</Text>}</Pressable>)}</ScrollView></View>})}
    <View style={s.privacy}><MaterialCommunityIcons name="shield-lock-outline" size={23} color={palette.green}/><Text style={s.privacyText}>Hazır cevaplar geçici DraBornPark oturumuna gider. Telefon ve e-posta iki tarafta da otomatik maskelenir.</Text></View>
    <BottomDock active="inbox"/>
  </ScrollView></SafeAreaView>;
}
function Stat({icon,value,label,color}:{icon:any;value:number;label:string;color:string}){return <View style={[s.stat,{borderColor:`${color}45`,backgroundColor:`${color}0E`}]}><MaterialCommunityIcons name={icon} size={24} color={color}/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:22},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:13},loadingText:{color:palette.muted,fontSize:type.body},stats:{flexDirection:'row',gap:9},stat:{flex:1,minHeight:126,borderRadius:radius.md,borderWidth:1,padding:14},statValue:{color:palette.text,fontSize:27,fontWeight:'900',marginTop:13},statLabel:{color:palette.muted,fontSize:type.caption,fontWeight:'800',marginTop:3},card:{marginTop:11,borderRadius:radius.lg,borderWidth:1,backgroundColor:palette.panel,padding:17},cardHead:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:52,height:52,borderRadius:18,alignItems:'center',justifyContent:'center'},category:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},time:{color:palette.muted,fontSize:type.caption,marginTop:3},status:{borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:7},statusText:{fontSize:type.micro,fontWeight:'900'},body:{color:palette.text,fontSize:type.body,lineHeight:22,marginTop:15},seen:{marginTop:13,flexDirection:'row',gap:7,alignItems:'center'},seenText:{color:palette.cyan,fontSize:type.caption,fontWeight:'900'},replyLabel:{color:palette.muted2,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:18,marginBottom:9},replyRail:{gap:8,paddingRight:12},reply:{minHeight:43,borderRadius:14,borderWidth:1,borderColor:`${palette.green}40`,backgroundColor:`${palette.green}0E`,paddingHorizontal:13,justifyContent:'center'},replyText:{color:palette.green,fontSize:type.caption,fontWeight:'900',maxWidth:220},empty:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:28,alignItems:'center'},emptyIcon:{width:70,height:70,borderRadius:24,backgroundColor:`${palette.green}18`,alignItems:'center',justifyContent:'center'},emptyTitle:{color:palette.text,fontSize:type.section,fontWeight:'900',marginTop:13},emptyBody:{color:palette.muted,fontSize:type.body,lineHeight:21,textAlign:'center',marginTop:6},privacy:{marginTop:16,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0D`,padding:15,flexDirection:'row',gap:11},privacyText:{color:palette.muted,fontSize:type.caption,lineHeight:19,flex:1}});
