import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { loadLiveDashboard, markReportSeen, quickReply } from '@/src/lib/drabornpark';
import { palette, radius } from '@/src/theme';

const replies=['Geliyorum','2 dakika','5 dakika','10 dakika','Aracı şu anda hareket ettiremiyorum','Güvenliğe bilgi verebilirsiniz','Teşekkür ederim'];
const categoryNames:Record<string,string>={blocked_exit:'Çıkış engelleniyor',move_vehicle:'Aracı hareket ettir',lights_on:'Farlar açık',window_open:'Cam açık',door_open:'Kapı açık',trunk_open:'Bagaj açık',damage:'Hasar',suspicious:'Şüpheli durum',towing:'Araç çekiliyor',animal:'Araçta hayvan',child:'Araçta çocuk',fire:'Yangın şüphesi',witness:'Tanık Modu',emergency:'Acil durum',other:'Araç bildirimi'};

export default function NotificationsScreen(){const [reports,setReports]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [sending,setSending]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const d=await loadLiveDashboard();setReports(d.reports);}catch{router.replace('/auth');}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 async function refresh(){setRefreshing(true);await load();setRefreshing(false)}
 async function seen(id:string){try{await markReportSeen(id);setReports(r=>r.map(x=>x.id===id?{...x,seen_at:new Date().toISOString(),status:x.status==='new'?'seen':x.status}:x));}catch(e:any){Alert.alert('İşlem başarısız',e?.message||'');}}
 async function reply(report:any,text:string){setSending(report.id);try{await quickReply(report.id,text);Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);setReports(r=>r.map(x=>x.id===report.id?{...x,status:'responded',seen_at:x.seen_at||new Date().toISOString()}:x));Alert.alert('Cevap gönderildi','Karşı taraf anonim oturum açıksa cevabınızı görebilir.');}catch(e:any){const msg=String(e?.message||'');Alert.alert(msg.includes('session_closed')?'Oturum kapandı':'Cevap gönderilemedi',msg.includes('session_closed')?'Geçici iletişim süresi dolmuş veya oturum kapatılmış.':msg);}finally{setSending(null)}}
 if(loading)return <SafeAreaView style={s.safe}><View style={s.loader}><ActivityIndicator color={palette.cyan}/><Text style={s.muted}>Bildirimler yükleniyor</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={palette.cyan}/>}><Header/><Text style={s.over}>ANONİM ARAÇ İLETİŞİMİ</Text><Text style={s.title}>Bildirim Merkezi</Text><Text style={s.sub}>QR/NFC üzerinden gelen bildirimleri gör, okundu olarak işaretle ve kişisel numaranı paylaşmadan hızlı cevap ver.</Text>
 <View style={s.stats}><Stat n={reports.filter(x=>!x.seen_at).length} label="YENİ" color={palette.orange}/><Stat n={reports.filter(x=>x.priority==='emergency').length} label="ACİL" color={palette.red}/><Stat n={reports.filter(x=>x.status==='responded').length} label="CEVAPLANDI" color={palette.green}/></View>
 {reports.length===0?<View style={s.empty}><MaterialCommunityIcons name="bell-check-outline" size={38} color={palette.green}/><Text style={s.emptyTitle}>Henüz bildirim yok</Text><Text style={s.emptyText}>DraBornPark etiketin tarandığında gelen güvenli bildirimler burada görünecek.</Text></View>:reports.map(r=>{const color=r.priority==='emergency'?palette.red:r.priority==='high'?palette.orange:palette.cyan;return <View key={r.id} style={[s.card,!r.seen_at&&{borderColor:`${color}77`}]}><View style={s.cardHead}><View style={[s.icon,{backgroundColor:`${color}18`}]}><MaterialCommunityIcons name={r.priority==='emergency'?'alert-octagon-outline':'bell-ring-outline'} size={23} color={color}/></View><View style={{flex:1}}><Text style={s.cat}>{categoryNames[r.category]||r.category}</Text><Text style={s.time}>{new Date(r.created_at).toLocaleString('tr-TR')}</Text></View><View style={[s.status,{borderColor:`${color}55`}]}><Text style={[s.statusText,{color}]}>{String(r.status||'new').toUpperCase()}</Text></View></View><Text style={s.body}>{r.message_safe||'Aracınız için yeni bir bildirim gönderildi.'}</Text>{!r.seen_at?<Pressable onPress={()=>seen(r.id)} style={s.seen}><MaterialCommunityIcons name="check-all" size={16} color={palette.cyan}/><Text style={s.seenText}>OKUNDU İŞARETLE</Text></Pressable>:null}<Text style={s.replyLabel}>HAZIR CEVAP</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{replies.map(text=><Pressable disabled={sending===r.id} key={text} onPress={()=>reply(r,text)} style={s.reply}>{sending===r.id?<ActivityIndicator size="small" color={palette.green}/>:<Text style={s.replyText}>{text}</Text>}</Pressable>)}</ScrollView></View>})}
 <View style={s.privacy}><MaterialCommunityIcons name="shield-lock-outline" size={20} color={palette.green}/><Text style={s.privacyText}>Hazır cevaplar geçici DraBornPark oturumuna gönderilir. Telefon ve e-posta iki tarafta da otomatik olarak maskelenir.</Text></View></ScrollView></SafeAreaView>}
function Header(){return <View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><MaterialCommunityIcons name="chevron-left" size={27} color={palette.text}/></Pressable><Text style={s.headerTitle}>Bildirimler</Text><View style={{width:42}}/></View>}
function Stat({n,label,color}:{n:number;label:string;color:string}){return <View style={s.stat}><Text style={[s.statN,{color}]}>{n}</Text><Text style={s.statL}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:19,paddingBottom:55},loader:{flex:1,alignItems:'center',justifyContent:'center',gap:12},muted:{color:palette.muted,fontSize:10},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},headerTitle:{color:palette.text,fontSize:14,fontWeight:'900'},over:{color:palette.orange,fontSize:9,fontWeight:'900',letterSpacing:1.5,marginTop:24},title:{color:palette.text,fontSize:29,fontWeight:'900',letterSpacing:-1,marginTop:6},sub:{color:palette.muted,fontSize:11.5,lineHeight:17,marginTop:7},stats:{flexDirection:'row',gap:8,marginTop:16},stat:{flex:1,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:12},statN:{fontSize:22,fontWeight:'900'},statL:{color:palette.muted,fontSize:7.5,fontWeight:'900',marginTop:3},card:{marginTop:11,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15},cardHead:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:45,height:45,borderRadius:15,alignItems:'center',justifyContent:'center'},cat:{color:palette.text,fontSize:13,fontWeight:'900'},time:{color:palette.muted,fontSize:8.8,marginTop:3},status:{borderWidth:1,borderRadius:10,paddingHorizontal:7,paddingVertical:4},statusText:{fontSize:7.2,fontWeight:'900'},body:{color:'#C4CCE0',fontSize:11.5,lineHeight:17,marginTop:12},seen:{marginTop:12,flexDirection:'row',gap:6,alignItems:'center'},seenText:{color:palette.cyan,fontSize:8.5,fontWeight:'900'},replyLabel:{color:'#6D7A91',fontSize:8,fontWeight:'900',letterSpacing:1.1,marginTop:14,marginBottom:7},reply:{borderRadius:12,borderWidth:1,borderColor:'#285140',backgroundColor:'#0D211A',paddingHorizontal:10,paddingVertical:9,minHeight:34,justifyContent:'center'},replyText:{color:palette.green,fontSize:8.8,fontWeight:'800',maxWidth:170},empty:{marginTop:20,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:25,alignItems:'center'},emptyTitle:{color:palette.text,fontSize:16,fontWeight:'900',marginTop:11},emptyText:{color:palette.muted,fontSize:10.5,lineHeight:15,textAlign:'center',marginTop:5},privacy:{marginTop:14,borderRadius:17,borderWidth:1,borderColor:'#244539',backgroundColor:'#0C1D17',padding:13,flexDirection:'row',gap:10},privacyText:{color:'#8DBAA6',fontSize:10,lineHeight:14.5,flex:1}});
