import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import * as Notifications from 'expo-notifications';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { loadLiveDashboard, savePark } from '@/src/lib/drabornpark';
import { uploadPrivateImage } from '@/src/lib/storage';
import { palette, radius } from '@/src/theme';

const reminders=[{label:'Yok',min:0},{label:'30 dk',min:30},{label:'1 saat',min:60},{label:'2 saat',min:120},{label:'3 saat',min:180}];

export default function ParkScreen(){
  const [vehicles,setVehicles]=useState<any[]>([]); const [vehicleId,setVehicleId]=useState(''); const [place,setPlace]=useState(''); const [floor,setFloor]=useState(''); const [zone,setZone]=useState(''); const [row,setRow]=useState(''); const [bay,setBay]=useState(''); const [note,setNote]=useState(''); const [reminder,setReminder]=useState(0); const [photo,setPhoto]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [locating,setLocating]=useState(false); const [coords,setCoords]=useState<{lat:number;lon:number;accuracy:number|null}|null>(null);
  useEffect(()=>{loadLiveDashboard().then(d=>{setVehicles(d.vehicles);if(d.vehicles[0])setVehicleId(d.vehicles[0].id);}).catch(()=>router.replace('/auth'));},[]);
  async function locate(){setLocating(true);try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted'){Alert.alert('Konum izni gerekli','Park konumunu kaydetmek için uygulama açıkken konum izni ver.');return;}const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setCoords({lat:l.coords.latitude,lon:l.coords.longitude,accuracy:l.coords.accuracy});Haptics.selectionAsync();}catch(e:any){Alert.alert('Konum alınamadı',e?.message||'Konum servisini kontrol et.');}finally{setLocating(false)}}
  async function pickPhoto(){const p=await ImagePicker.requestCameraPermissionsAsync();if(!p.granted){Alert.alert('Kamera izni gerekli','Park yerinin fotoğrafını çekmek için kamera izni ver.');return;}const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.78,allowsEditing:false});if(!r.canceled)setPhoto(r.assets[0].uri);}
  async function store(){if(!vehicleId){Alert.alert('Araç gerekli','Önce bir araç ekle.');return;}setBusy(true);try{let photoPath:null|string=null;if(photo)photoPath=await uploadPrivateImage(photo,'parks');const saved:any=await savePark({vehicleId,placeName:place,latitude:coords?.lat,longitude:coords?.lon,accuracyMeters:coords?.accuracy,floorCode:floor,zoneColor:zone,rowCode:row,bayCode:bay,note,photoPath,reminderMinutes:reminder,source:coords?'gps_manual':'manual'});if(reminder>0){const permission=await Notifications.requestPermissionsAsync();if(permission.granted){await Notifications.scheduleNotificationAsync({content:{title:'DraBornPark • Park süresi',body:'Park sürenizin bitmesine 15 dakika kaldı.',data:{parkId:saved?.id}},trigger:{type:Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,seconds:Math.max(5,(reminder-15)*60)}});}}Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Park kaydedildi','Son Park kartın ve Timeline güncellendi.',[{text:'Ana Sayfa',onPress:()=>router.replace('/')}]);}catch(e:any){Alert.alert('Park kaydedilemedi',e?.message||'İşlem başarısız.');}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><Header/><Text style={s.over}>DraBornPark PARK HAFIZASI</Text><Text style={s.title}>Aracımı burada bıraktım</Text><Text style={s.sub}>GPS konumunu kaydet; kapalı otoparktaysan kat, renk, sıra ve park numarasını da ekle.</Text>
  <Text style={s.label}>ARAÇ</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{vehicles.map(v=><Pressable key={v.id} onPress={()=>setVehicleId(v.id)} style={[s.vehicle,vehicleId===v.id&&s.vehicleActive]}><MaterialCommunityIcons name={v.vehicle_type==='motorcycle'?'motorbike':'car'} size={20} color={vehicleId===v.id?palette.cyan:palette.muted}/><Text style={[s.vehicleText,vehicleId===v.id&&{color:palette.cyan}]}>{v.vehicle_name}</Text></Pressable>)}</ScrollView>
  <Pressable onPress={locate} style={s.locate}>{locating?<ActivityIndicator color={palette.cyan}/>:<MaterialCommunityIcons name="crosshairs-gps" size={24} color={palette.cyan}/>}<View style={{flex:1}}><Text style={s.locateTitle}>{coords?'Konum hazır':'MEVCUT KONUMU KAYDET'}</Text><Text style={s.locateSub}>{coords?`${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)} • doğruluk ${Math.round(coords.accuracy||0)} m`:'Telefonun mevcut konumu yalnızca bu park kaydı için alınır.'}</Text></View></Pressable>
  <View style={s.form}><Field label="MEKAN / OTOPARK" value={place} set={setPlace} placeholder="Örn. Metromall AVM"/><Text style={s.section}>KAPALI OTOPARK DETAYI</Text><View style={s.double}><View style={{flex:1}}><Field label="KAT" value={floor} set={setFloor} placeholder="P2"/></View><View style={{flex:1}}><Field label="BÖLGE / RENK" value={zone} set={setZone} placeholder="Mavi"/></View></View><View style={s.double}><View style={{flex:1}}><Field label="SIRA" value={row} set={setRow} placeholder="C"/></View><View style={{flex:1}}><Field label="PARK NO" value={bay} set={setBay} placeholder="128"/></View></View><Field label="NOT" value={note} set={setNote} placeholder="Asansörün karşısı, kolon yanı..."/>
  <Text style={s.label}>PARK SÜRESİ HATIRLATICISI</Text><View style={s.chips}>{reminders.map(r=><Pressable key={r.min} onPress={()=>setReminder(r.min)} style={[s.chip,reminder===r.min&&s.chipActive]}><Text style={[s.chipText,reminder===r.min&&{color:palette.yellow}]}>{r.label}</Text></Pressable>)}</View>
  <Text style={s.label}>PARK YERİ FOTOĞRAFI</Text><Pressable onPress={pickPhoto} style={s.photo}>{photo?<Image source={{uri:photo}} style={s.photoImg}/>:<><MaterialCommunityIcons name="camera-plus-outline" size={28} color={palette.purple}/><Text style={s.photoTitle}>PARK YERİNİN FOTOĞRAFINI ÇEK</Text><Text style={s.photoSub}>Direk, tabela veya park numarası hesabına özel saklanır.</Text></>}</Pressable>
  <Pressable disabled={busy} onPress={store} style={[s.cta,busy&&{opacity:.65}]}>{busy?<ActivityIndicator color={palette.bg}/>:<><MaterialCommunityIcons name="map-marker-check" size={22} color={palette.bg}/><Text style={s.ctaText}>PARKI KAYDET</Text></>}</Pressable></View>
  <View style={s.private}><MaterialCommunityIcons name="shield-lock-outline" size={20} color={palette.green}/><Text style={s.privateText}>Park geçmişin kamusal değildir. Konum sürekli takip edilmez; yalnızca sen “Park Ettim” dediğinde kayıt oluşur.</Text></View></ScrollView></SafeAreaView>}
function Header(){return <View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><MaterialCommunityIcons name="chevron-left" size={27} color={palette.text}/></Pressable><Text style={s.headerTitle}>Park Ettim</Text><View style={{width:42}}/></View>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#5B667B" style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:19,paddingBottom:55},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},headerTitle:{color:palette.text,fontSize:14,fontWeight:'900'},over:{color:palette.orange,fontSize:9,fontWeight:'900',letterSpacing:1.5,marginTop:25},title:{color:palette.text,fontSize:29,fontWeight:'900',letterSpacing:-1,marginTop:7},sub:{color:palette.muted,fontSize:11.5,lineHeight:17,marginTop:7},label:{color:'#7E8BA3',fontSize:8.5,fontWeight:'900',letterSpacing:1.1,marginBottom:6,marginTop:13},vehicle:{height:45,borderRadius:14,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:7},vehicleActive:{borderColor:'#275D6C',backgroundColor:'#0C2730'},vehicleText:{color:palette.muted,fontSize:10,fontWeight:'900'},locate:{marginTop:16,borderRadius:radius.lg,borderWidth:1,borderColor:'#245061',backgroundColor:'#0C2028',padding:15,flexDirection:'row',alignItems:'center',gap:12},locateTitle:{color:palette.cyan,fontSize:11,fontWeight:'900'},locateSub:{color:'#7997A2',fontSize:9.5,lineHeight:14,marginTop:3},form:{marginTop:12,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15},section:{color:palette.text,fontSize:12,fontWeight:'900',marginTop:18,marginBottom:2},double:{flexDirection:'row',gap:9},input:{height:49,borderRadius:14,borderWidth:1,borderColor:'#263249',backgroundColor:'#090E18',paddingHorizontal:13,color:palette.text,fontSize:13},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:11,paddingVertical:9,borderRadius:12,borderWidth:1,borderColor:palette.line,backgroundColor:'#0A101C'},chipActive:{borderColor:'#564D25',backgroundColor:'#211E12'},chipText:{color:palette.muted,fontSize:9,fontWeight:'900'},photo:{minHeight:116,borderRadius:17,borderWidth:1,borderStyle:'dashed',borderColor:'#45345D',backgroundColor:'#151021',alignItems:'center',justifyContent:'center',overflow:'hidden',padding:12},photoImg:{width:'100%',height:170,borderRadius:13},photoTitle:{color:palette.purple,fontSize:9.5,fontWeight:'900',marginTop:8},photoSub:{color:'#8E819F',fontSize:9,textAlign:'center',marginTop:4},cta:{height:57,borderRadius:17,backgroundColor:palette.cyan,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:19},ctaText:{color:palette.bg,fontSize:11,fontWeight:'900'},private:{marginTop:13,borderRadius:17,borderWidth:1,borderColor:'#26483A',backgroundColor:'#0C1D17',padding:13,flexDirection:'row',gap:10},privateText:{color:'#8DB9A5',fontSize:10,lineHeight:14.5,flex:1}});
