import * as Haptics from 'expo-haptics';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import { router } from 'expo-router';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Animated, Easing, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, BottomDock } from '@/src/components/AppChrome';
import { ColorPopup } from '@/src/components/ColorPopup';
import { Pill, SafeIcon } from '@/src/components/Primitives';
import { useDemo } from '@/src/demo/DemoContext';
import { attachParkTicket } from '@/src/lib/extras';
import { loadLiveDashboard, savePark } from '@/src/lib/drabornpark';
import { uploadPrivateImage } from '@/src/lib/storage';
import { palette, type } from '@/src/theme';

const REMINDERS=[{label:'Kapalı',min:0},{label:'30 dk',min:30},{label:'1 saat',min:60},{label:'2 saat',min:120},{label:'3 saat',min:180}];

export default function ParkScreen(){
  const demo=useDemo();
  const [vehicles,setVehicles]=useState<any[]>([]);
  const [vehicleId,setVehicleId]=useState('');
  const [place,setPlace]=useState('');
  const [floor,setFloor]=useState('');
  const [zone,setZone]=useState('');
  const [row,setRow]=useState('');
  const [bay,setBay]=useState('');
  const [note,setNote]=useState('');
  const [reminder,setReminder]=useState(0);
  const [photo,setPhoto]=useState<string|null>(null);
  const [ticket,setTicket]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  const [locating,setLocating]=useState(false);
  const [coords,setCoords]=useState<{lat:number;lon:number;accuracy:number|null}|null>(null);
  const [locationInfoOpen,setLocationInfoOpen]=useState(false);
  const enter=useRef(new Animated.Value(0)).current;
  const locationPulse=useRef(new Animated.Value(0)).current;
  const locationSweep=useRef(new Animated.Value(0)).current;
  const savePulse=useRef(new Animated.Value(0)).current;
  const saveSweep=useRef(new Animated.Value(0)).current;

  useEffect(()=>{if(demo.active){setVehicles(demo.state.vehicles.map((v:any)=>({id:v.id,vehicle_name:v.name,plate:v.plate,vehicle_type:v.type})));if(demo.state.vehicles[0])setVehicleId(demo.state.vehicles[0].id);}else{let mounted=true;loadLiveDashboard().then(d=>{if(!mounted)return;setVehicles(d.vehicles);if(d.vehicles[0])setVehicleId(d.vehicles[0].id)}).catch(()=>router.replace('/auth'));return()=>{mounted=false};}},[demo.active]);
  useEffect(()=>{Animated.timing(enter,{toValue:1,duration:480,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start()},[enter]);
  useEffect(()=>{
    const lp=Animated.loop(Animated.sequence([Animated.timing(locationPulse,{toValue:1,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(locationPulse,{toValue:0,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(520)]));
    const ls=Animated.loop(Animated.timing(locationSweep,{toValue:1,duration:2700,easing:Easing.linear,useNativeDriver:true}));
    const sp=Animated.loop(Animated.sequence([Animated.timing(savePulse,{toValue:1,duration:820,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(savePulse,{toValue:0,duration:820,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.delay(380)]));
    const ss=Animated.loop(Animated.timing(saveSweep,{toValue:1,duration:2300,easing:Easing.linear,useNativeDriver:true}));
    lp.start();ls.start();sp.start();ss.start();return()=>{lp.stop();ls.stop();sp.stop();ss.stop()};
  },[locationPulse,locationSweep,savePulse,saveSweep]);

  function locate(){if(demo.active){setCoords({lat:39.9357,lon:32.8063,accuracy:8});Haptics.selectionAsync();return;}setLocationInfoOpen(true);}
  async function locateNow(){setLocating(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert('Konum izni verilmedi','Konumu kullanmadan da kat, bölüm ve park numarasını elle kaydedebilirsin.');return;}const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setCoords({lat:current.coords.latitude,lon:current.coords.longitude,accuracy:current.coords.accuracy});Haptics.selectionAsync();}catch(e:any){Alert.alert('Konum alınamadı',e?.message||'Konum servisini kontrol et.');}finally{setLocating(false)}}
  async function capture(kind:'park'|'ticket'){try{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){Alert.alert('Kamera izni verilmedi','Fotoğraf eklemek isteğe bağlıdır. Park kaydını fotoğraf olmadan da oluşturabilirsin.');return;}const result=await ImagePicker.launchCameraAsync({mediaTypes:['images'] as ImagePicker.MediaType[],quality:.8,allowsEditing:false});const asset=result.assets?.[0];if(!result.canceled&&asset){kind==='park'?setPhoto(asset.uri):setTicket(asset.uri)}}catch(e:any){Alert.alert('Kamera açılamadı',e?.message||'Kamera erişimini kontrol et.')}}
  async function scheduleReminder(parkId?:string){if(reminder<=0)return;try{const Notifications=await import('expo-notifications');const permission=await Notifications.requestPermissionsAsync();if(!permission.granted)return;await Notifications.scheduleNotificationAsync({content:{title:'DraBornPark • Park süresi',body:'Park sürenizin bitmesine 15 dakika kaldı.',data:{parkId}},trigger:{type:Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,seconds:Math.max(5,(reminder-15)*60)}});}catch{}}

  async function store(){
    if(!vehicleId){Alert.alert('Araç gerekli','Önce park kaydının bağlı olacağı aracı seç.');return;}
    if(demo.active){const now=new Date().toISOString();demo.patch(st=>({...st,parks:[{id:`demo-${Date.now()}`,vehicleId,placeName:place||'Metromall AVM',floor:floor||'P2',zoneColor:zone||'Mavi',row:row||'C',bay:bay||'128',latitude:coords?.lat,longitude:coords?.lon,parkedAt:now,endedAt:null,note:note||'Demo park kaydı',reminder:REMINDERS.find(x=>x.min===reminder)?.label,ticketPath:ticket?'demo-ticket':null},...st.parks.map((p:any)=>p.endedAt?p:{...p,endedAt:now})],stats:{...st.stats,parksThisMonth:st.stats.parksThisMonth+1},timeline:[{id:`park-${Date.now()}`,type:'PARKED',icon:'map-marker-check',color:palette.cyan,title:'Yeni park kaydedildi',detail:`${place||'Metromall AVM'} • ${floor||'P2'} • ${zone||'Mavi'} • ${(row||'C')+(bay||'128')}`,time:'Şimdi'},...st.timeline]}));Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Demo park kaydedildi','Ana sayfa, araç geçmişi ve aylık özet güncellendi.');return;}
    setBusy(true);
    try{
      let photoPath:string|null=null;let ticketPath:string|null=null;
      if(photo)photoPath=await uploadPrivateImage(photo,'parks');
      if(ticket)ticketPath=await uploadPrivateImage(ticket,'park-tickets');
      const saved:any=await savePark({vehicleId,placeName:place,latitude:coords?.lat,longitude:coords?.lon,accuracyMeters:coords?.accuracy,floorCode:floor,zoneColor:zone,rowCode:row,bayCode:bay,note,photoPath,reminderMinutes:reminder,source:'manual'});
      if(ticketPath&&saved?.id)await attachParkTicket(saved.id,ticketPath);
      await scheduleReminder(saved?.id);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      Alert.alert('Park hafızaya alındı','Konum ve otopark bilgilerin yalnızca hesabının park hafızasına kaydedildi.',[{text:'Ana Sayfa',onPress:()=>router.replace('/')}]);
    }catch(e:any){Alert.alert('Park kaydedilemedi',e?.message||'İşlem başarısız.');}finally{setBusy(false)}
  }

  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.orange} secondary={palette.cyan}/><Animated.View style={{flex:1,opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[14,0]})}]}}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="always" keyboardDismissMode="none" showsVerticalScrollIndicator={false}>
    <View style={s.topbar}><Pressable onPress={()=>router.back()} style={s.back}><SafeIcon name="arrow-left" size={24} color={palette.text}/></Pressable><View style={{flex:1}}><Text style={s.topEyebrow}>PARK HAFIZASI</Text><Text style={s.topTitle}>Park Ettim</Text><Text style={s.topSub}>Açık alan veya kapalı otopark; tek kayıt.</Text></View><Pill label={demo.active?'DEMO':'ÖZEL'} color={demo.active?palette.yellow:palette.green}/></View>

    <View style={s.hero}><View style={s.heroSpectrum}><View style={[s.bar,{backgroundColor:palette.orange}]}/><View style={[s.bar,{backgroundColor:palette.cyan}]}/><View style={[s.bar,{backgroundColor:palette.purple}]}/><View style={[s.bar,{backgroundColor:palette.green}]}/></View><View style={s.heroRow}><View style={s.heroIcon}><SafeIcon name="map-marker-radius" size={39} color={palette.orange}/></View><View style={{flex:1}}><Text style={s.heroKicker}>ARACIMI BURADA BIRAKTIM</Text><Text style={s.heroTitle}>Park yerini unutma derdini bitir.</Text><Text style={s.heroBody}>Konum, kat, bölge, sıra, park no, fotoğraf ve bileti tek seferde kaydet.</Text></View></View><View style={s.heroChips}><MiniChip icon="crosshairs-gps" text="GPS" color={palette.cyan}/><MiniChip icon="parking" text="OTOPARK" color={palette.orange}/><MiniChip icon="camera-outline" text="GÖRSEL" color={palette.purple}/></View></View>

    <Step title="1 • Aracını seç" subtitle="Bu park kaydı hangi araca ait?" color={palette.cyan} icon="car-multiple"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.vehicleRail}>{vehicles.map(v=>{const active=vehicleId===v.id;const color=active?palette.cyan:palette.blue;return <Pressable key={v.id} onPress={()=>{setVehicleId(v.id);Haptics.selectionAsync()}} style={[s.vehicle,{borderColor:active?`${palette.cyan}88`:palette.line,backgroundColor:active?`${palette.cyan}1C`:palette.glass}]}><View style={[s.vehicleIcon,{backgroundColor:`${color}28`,borderColor:`${color}65`}]}><SafeIcon name={v.vehicle_type==='motorcycle'?'motorbike':'car-sports'} size={28} color={color}/></View><View style={{flex:1}}><Text style={s.vehicleName}>{v.vehicle_name}</Text><Text style={s.vehiclePlate}>{v.plate||'Plaka yok'}</Text></View>{active?<View style={s.activeCheck}><SafeIcon name="check" size={17} color={palette.ink}/></View>:null}</Pressable>})}</ScrollView>

    <Step title="2 • Konum" subtitle="İstersen GPS al, istersen bilgileri elle gir" color={palette.green} icon="crosshairs-gps"/>
    <Animated.View style={[s.locationWrap,{transform:[{scale:locationPulse.interpolate({inputRange:[0,1],outputRange:[1,1.008]})}]}]}><Pressable accessibilityRole="button" onPress={locate} style={({pressed})=>[s.locationAction,coords&&s.locationActionReady,pressed&&s.actionPressed]}>
      <Animated.View pointerEvents="none" style={[s.actionSweep,{transform:[{translateX:locationSweep.interpolate({inputRange:[0,1],outputRange:[-120,520]})},{rotate:'12deg'}]}]}/>
      <View style={s.actionSpectrum}><View style={[s.actionBar,{backgroundColor:palette.cyan}]}/><View style={[s.actionBar,{backgroundColor:palette.blue}]}/><View style={[s.actionBar,{backgroundColor:palette.purple}]}/><View style={[s.actionBar,{backgroundColor:palette.orange}]}/><View style={[s.actionBar,{backgroundColor:palette.green}]}/></View>
      <View style={[s.locationIconModern,{borderColor:`${coords?palette.green:palette.cyan}88`,backgroundColor:`${coords?palette.green:palette.cyan}22`}]}>{locating?<ActivityIndicator color={palette.cyan}/>:<SafeIcon name={coords?'check-decagram-outline':'crosshairs-gps'} size={30} color={coords?palette.green:palette.cyan}/>}<View style={[s.actionDot,{backgroundColor:coords?palette.green:palette.pink}]}/></View>
      <View style={{flex:1,minWidth:0}}><Text style={[s.locationKicker,{color:coords?palette.green:palette.aqua}]}>{coords?'GPS HAZIR':'GPS • TEK SEFERLİK KONUM'}</Text><Text style={s.locationTitle}>{coords?'Konum hazır':'MEVCUT KONUMU AL'}</Text><Text style={s.locationBody}>{coords?`${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)} • ±${Math.round(coords.accuracy||0)} m`:'Yalnızca bu park kaydı için konum izni ister.'}</Text></View>
      <Animated.View style={[s.locationArrow,{borderColor:`${coords?palette.green:palette.cyan}70`,transform:[{translateX:locationPulse.interpolate({inputRange:[0,1],outputRange:[0,5]})}]}]}><SafeIcon name={coords?'check':'arrow-right'} size={23} color={coords?palette.green:palette.cyan}/></Animated.View>
    </Pressable></Animated.View>

    <Step title="3 • Otopark detayları" subtitle="Kapalı otoparkta aracını nokta atışı bul" color={palette.purple} icon="parking"/>
    <View style={s.form}><Field label="MEKAN / OTOPARK" value={place} set={setPlace} placeholder="Örn. Metromall AVM" color={palette.cyan}/><View style={s.double}><View style={{flex:1}}><Field label="KAT" value={floor} set={setFloor} placeholder="P2" color={palette.purple}/></View><View style={{flex:1}}><Field label="BÖLGE / RENK" value={zone} set={setZone} placeholder="Mavi" color={palette.blue}/></View></View><View style={s.double}><View style={{flex:1}}><Field label="SIRA" value={row} set={setRow} placeholder="C" color={palette.green}/></View><View style={{flex:1}}><Field label="PARK NO" value={bay} set={setBay} placeholder="128" color={palette.orange}/></View></View><Field label="KISA NOT" value={note} set={setNote} placeholder="Asansör karşısı, kolon yanı…" color={palette.pink}/></View>

    <Step title="4 • Hatırlatıcı" subtitle="Park süresi için yerel bildirim seç" color={palette.yellow} icon="timer-outline" badge={REMINDERS.find(x=>x.min===reminder)?.label}/>
    <View style={s.reminders}>{REMINDERS.map((x,index)=>{const active=reminder===x.min;const colors=[palette.yellow,palette.cyan,palette.blue,palette.purple,palette.orange];const color=colors[index];return <Pressable key={x.min} onPress={()=>{setReminder(x.min);Haptics.selectionAsync()}} style={[s.reminder,{borderColor:active?color:`${color}45`,backgroundColor:active?`${color}25`:`${color}0E`}]}><View style={[s.reminderDot,{backgroundColor:color}]}/><Text style={[s.reminderText,active&&{color:palette.text}]}>{x.label}</Text>{active?<SafeIcon name="check-circle" size={18} color={color}/>:null}</Pressable>})}</View>

    <Step title="5 • Görsel hafıza" subtitle="İstersen park noktasını fotoğrafla güçlendir" color={palette.pink} icon="camera-outline"/>
    <View style={s.mediaGrid}><Media title="Park fotoğrafı" body="Direk, tabela veya park numarası" icon="camera-plus-outline" color={palette.purple} uri={photo} onPress={()=>capture('park')}/><Media title="Otopark bileti" body="Fiş, bilet veya giriş kartı" icon="ticket-confirmation-outline" color={palette.orange} uri={ticket} onPress={()=>capture('ticket')}/></View>

    <Animated.View style={[s.saveWrap,{transform:[{scale:savePulse.interpolate({inputRange:[0,1],outputRange:[1,1.009]})}]}]}><Pressable accessibilityRole="button" disabled={busy} onPress={store} style={({pressed})=>[s.saveModern,busy&&{opacity:.58},pressed&&s.actionPressed]}>
      <Animated.View pointerEvents="none" style={[s.saveSweep,{transform:[{translateX:saveSweep.interpolate({inputRange:[0,1],outputRange:[-140,620]})},{rotate:'13deg'}]}]}/>
      <View style={s.saveSpectrum}><View style={[s.actionBar,{backgroundColor:palette.aqua}]}/><View style={[s.actionBar,{backgroundColor:palette.cyan}]}/><View style={[s.actionBar,{backgroundColor:palette.purple}]}/><View style={[s.actionBar,{backgroundColor:palette.pink}]}/><View style={[s.actionBar,{backgroundColor:palette.green}]}/></View>
      <View style={s.saveIconModern}>{busy?<ActivityIndicator color={palette.aqua}/>:<SafeIcon name="map-marker-check" size={30} color={palette.aqua}/>}<View style={s.saveIconDot}/></View>
      <View style={{flex:1,minWidth:0}}><Text style={s.saveKickerModern}>DRABORNPARK HAFIZASI</Text><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.82} style={s.saveTitleModern}>{demo.active?'DEMO PARKI KAYDET':'PARKI KAYDET'}</Text><Text style={s.saveSubModern}>Konum ve otopark detaylarını tek kayıtta sakla</Text></View>
      <Animated.View style={[s.saveArrow,{transform:[{translateX:savePulse.interpolate({inputRange:[0,1],outputRange:[0,6]})}]}]}><SafeIcon name="arrow-right" size={27} color={palette.cyan}/></Animated.View>
    </Pressable></Animated.View>
    <View style={s.bottomPrivacy}><SafeIcon name="shield-check-outline" size={24} color={palette.green}/><Text style={s.bottomPrivacyText}>Park geçmişin kamusal değildir. Aile paylaşımı yalnızca sen açıkça izin verdiğinde çalışır.</Text></View>
    <BottomDock active="park"/>
  </ScrollView><ColorPopup visible={locationInfoOpen} icon="map-marker-radius-outline" eyebrow="KONUM İZNİ" title="Park yerini hatırlayalım" body="DraBornPark konumunu yalnızca bu park kaydındaki noktayı kaydetmek ve Aracıma Git yönlendirmesini oluşturmak için kullanır. Arka planda sürekli takip yapmaz; konum QR/NFC ziyaretçilerine gösterilmez." accent={palette.green} secondary={palette.cyan} primaryLabel="KONUMA İZİN VER" onPrimary={()=>{setLocationInfoOpen(false);void locateNow()}} secondaryLabel="ELLE GİRECEĞİM" onSecondary={()=>setLocationInfoOpen(false)} chips={['TEK SEFERLİK','ARKA PLAN TAKİBİ YOK','ÖZEL']}/></Animated.View></SafeAreaView>;
}

function MiniChip({icon,text,color}:{icon:string;text:string;color:string}){return <View style={[s.miniChip,{borderColor:`${color}58`,backgroundColor:`${color}14`}]}><SafeIcon name={icon} size={15} color={color}/><Text style={[s.miniChipText,{color}]}>{text}</Text></View>}
function Step({title,subtitle,color,icon,badge}:{title:string;subtitle:string;color:string;icon:string;badge?:string}){return <View style={s.step}><View style={[s.stepIcon,{backgroundColor:`${color}22`,borderColor:`${color}65`}]}><SafeIcon name={icon} size={22} color={color}/></View><View style={{flex:1}}><Text style={s.stepTitle}>{title}</Text><Text style={s.stepSub}>{subtitle}</Text></View>{badge?<View style={[s.stepBadge,{borderColor:`${color}60`,backgroundColor:`${color}14`}]}><Text style={[s.stepBadgeText,{color}]}>{badge}</Text></View>:null}</View>}
function Field({label,value,set,placeholder,color}:{label:string;value:string;set:(v:string)=>void;placeholder:string;color:string}){return <View><Text style={[s.label,{color}]}>{label}</Text><View style={[s.inputWrap,{borderColor:`${color}45`}]}><View style={[s.inputDot,{backgroundColor:color}]}/><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={palette.muted2} blurOnSubmit={false} style={s.input}/></View></View>}
function Media({title,body,icon,color,uri,onPress}:{title:string;body:string;icon:string;color:string;uri:string|null;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.media,{borderColor:`${color}68`,backgroundColor:`${color}14`}]}>{uri?<><Image source={{uri}} resizeMode="cover" style={s.mediaImage}/><View style={s.mediaPhotoFooter}><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={s.mediaPhotoTitle}>{title}</Text><Text style={[s.mediaPhotoCta,{color}]}>YENİDEN ÇEK</Text></View><View style={[s.mediaPhotoIcon,{borderColor:`${color}72`}]}><SafeIcon name="camera-retake-outline" size={19} color={color}/></View></View><View style={[s.mediaLine,{backgroundColor:color}]}/></>:<><View style={[s.mediaIcon,{backgroundColor:`${color}25`,borderColor:`${color}65`}]}><SafeIcon name={icon} size={29} color={color}/></View><Text style={s.mediaTitle}>{title}</Text><Text style={s.mediaBody}>{body}</Text><View style={s.mediaFooter}><Text style={[s.mediaCta,{color}]}>FOTOĞRAF ÇEK</Text><SafeIcon name="camera-outline" size={17} color={color}/></View><View style={[s.mediaLine,{backgroundColor:color}]}/></>}</Pressable>}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:18,paddingBottom:22},
  topbar:{minHeight:96,borderRadius:27,borderWidth:1,borderColor:palette.lineSoft,backgroundColor:palette.glassStrong,padding:13,flexDirection:'row',alignItems:'center',gap:12},back:{width:48,height:48,borderRadius:16,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel2,alignItems:'center',justifyContent:'center'},topEyebrow:{color:palette.orange,fontSize:11,fontWeight:'900',letterSpacing:1.3},topTitle:{color:palette.text,fontSize:26,fontWeight:'900',letterSpacing:-.6,marginTop:1},topSub:{color:palette.muted,fontSize:12.5,marginTop:3},
  hero:{marginTop:13,borderRadius:31,borderWidth:1,borderColor:`${palette.orange}72`,backgroundColor:palette.glassStrong,padding:18,overflow:'hidden'},heroSpectrum:{height:5,flexDirection:'row',gap:3,marginBottom:17},bar:{flex:1,borderRadius:99},heroRow:{flexDirection:'row',alignItems:'center',gap:14},heroIcon:{width:72,height:72,borderRadius:23,borderWidth:1,borderColor:`${palette.orange}70`,backgroundColor:`${palette.orange}22`,alignItems:'center',justifyContent:'center'},heroKicker:{color:palette.orange,fontSize:11,fontWeight:'900',letterSpacing:1.05},heroTitle:{color:palette.text,fontSize:25,fontWeight:'900',lineHeight:30,letterSpacing:-.65,marginTop:4},heroBody:{color:palette.muted,fontSize:13,lineHeight:19,marginTop:6},heroChips:{flexDirection:'row',gap:7,marginTop:16,flexWrap:'wrap'},miniChip:{borderWidth:1,borderRadius:999,paddingHorizontal:9,paddingVertical:6,flexDirection:'row',alignItems:'center',gap:5},miniChipText:{fontSize:11,fontWeight:'900',letterSpacing:.4},
  step:{marginTop:24,marginBottom:10,flexDirection:'row',alignItems:'center',gap:10},stepIcon:{width:42,height:42,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},stepTitle:{color:palette.text,fontSize:18,fontWeight:'900'},stepSub:{color:palette.muted,fontSize:12.5,lineHeight:18,marginTop:2},stepBadge:{borderWidth:1,borderRadius:999,paddingHorizontal:9,paddingVertical:7},stepBadgeText:{fontSize:11,fontWeight:'900'},
  vehicleRail:{gap:9,paddingRight:15},vehicle:{width:230,minHeight:82,borderRadius:22,borderWidth:1,padding:11,flexDirection:'row',alignItems:'center',gap:10},vehicleIcon:{width:50,height:50,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},vehicleName:{color:palette.text,fontSize:16,fontWeight:'900'},vehiclePlate:{color:palette.muted,fontSize:12.5,fontWeight:'800',marginTop:4},activeCheck:{width:27,height:27,borderRadius:10,backgroundColor:palette.green,alignItems:'center',justifyContent:'center'},
  locationWrap:{marginTop:3},locationAction:{minHeight:112,borderRadius:27,borderWidth:1,borderColor:`${palette.cyan}88`,backgroundColor:'#082B39',padding:14,flexDirection:'row',alignItems:'center',gap:12,overflow:'hidden'},locationActionReady:{borderColor:`${palette.green}88`,backgroundColor:'#092D28'},actionPressed:{opacity:.82,transform:[{scale:.992}]},actionSweep:{position:'absolute',top:-24,bottom:-24,width:76,backgroundColor:'#FFFFFF13'},actionSpectrum:{position:'absolute',left:14,right:14,bottom:0,height:5,flexDirection:'row',gap:3},actionBar:{flex:1,borderRadius:99},locationIconModern:{width:60,height:60,borderRadius:20,borderWidth:1,alignItems:'center',justifyContent:'center'},actionDot:{position:'absolute',right:6,top:6,width:9,height:9,borderRadius:5},locationKicker:{fontSize:9.5,fontWeight:'900',letterSpacing:1.05,marginBottom:2},locationTitle:{color:palette.text,fontSize:18,fontWeight:'900'},locationBody:{color:'#B9D5DD',fontSize:12.5,lineHeight:18,marginTop:4},locationArrow:{width:42,height:42,borderRadius:14,borderWidth:1,backgroundColor:'#FFFFFF08',alignItems:'center',justifyContent:'center'},
  form:{borderRadius:25,borderWidth:1,borderColor:`${palette.purple}52`,backgroundColor:palette.glass,padding:14,gap:12},double:{flexDirection:'row',gap:10},label:{fontSize:11,fontWeight:'900',letterSpacing:.8,marginBottom:6},inputWrap:{minHeight:55,borderRadius:17,borderWidth:1,backgroundColor:palette.panel2,flexDirection:'row',alignItems:'center',paddingHorizontal:11},inputDot:{width:7,height:7,borderRadius:4,marginRight:8},input:{flex:1,color:palette.text,fontSize:14.5,paddingVertical:13},
  reminders:{flexDirection:'row',flexWrap:'wrap',gap:8},reminder:{minHeight:49,borderRadius:17,borderWidth:1,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:7},reminderDot:{width:7,height:7,borderRadius:4},reminderText:{color:palette.muted,fontSize:13,fontWeight:'900'},
  mediaGrid:{flexDirection:'row',gap:10},media:{flex:1,height:190,borderRadius:24,borderWidth:1,padding:13,overflow:'hidden'},mediaIcon:{width:50,height:50,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},mediaTitle:{color:palette.text,fontSize:16,fontWeight:'900',marginTop:12},mediaBody:{color:palette.muted,fontSize:12,lineHeight:17,marginTop:4},mediaFooter:{marginTop:'auto',paddingTop:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},mediaCta:{fontSize:11,fontWeight:'900',letterSpacing:.45},mediaLine:{position:'absolute',left:12,right:12,bottom:0,height:4,borderRadius:3},mediaImage:{position:'absolute',left:0,right:0,top:0,bottom:0,width:'100%',height:'100%'},mediaPhotoFooter:{position:'absolute',left:9,right:9,bottom:10,minHeight:54,borderRadius:16,borderWidth:1,borderColor:'#FFFFFF22',backgroundColor:'#050816D9',paddingHorizontal:11,paddingVertical:8,flexDirection:'row',alignItems:'center',gap:8},mediaPhotoTitle:{color:palette.text,fontSize:12.5,fontWeight:'900'},mediaPhotoCta:{fontSize:9.5,fontWeight:'900',letterSpacing:.55,marginTop:2},mediaPhotoIcon:{width:36,height:36,borderRadius:12,borderWidth:1,backgroundColor:'#FFFFFF0C',alignItems:'center',justifyContent:'center'},
  saveWrap:{marginTop:24},saveModern:{minHeight:104,borderRadius:29,borderWidth:1,borderColor:`${palette.aqua}92`,backgroundColor:'#0A3438',padding:14,flexDirection:'row',alignItems:'center',gap:12,overflow:'hidden'},saveSweep:{position:'absolute',top:-25,bottom:-25,width:90,backgroundColor:'#FFFFFF16'},saveSpectrum:{position:'absolute',left:14,right:14,bottom:0,height:5,flexDirection:'row',gap:3},saveIconModern:{width:60,height:60,borderRadius:20,borderWidth:1,borderColor:`${palette.aqua}90`,backgroundColor:`${palette.aqua}20`,alignItems:'center',justifyContent:'center'},saveIconDot:{position:'absolute',right:6,top:6,width:9,height:9,borderRadius:5,backgroundColor:palette.pink},saveKickerModern:{color:palette.aqua,fontSize:10,fontWeight:'900',letterSpacing:1.05},saveTitleModern:{color:palette.text,fontSize:21,fontWeight:'900',marginTop:1},saveSubModern:{color:'#B9D5D2',fontSize:11.5,lineHeight:16,marginTop:2},saveArrow:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:`${palette.cyan}72`,backgroundColor:`${palette.cyan}12`,alignItems:'center',justifyContent:'center'},bottomPrivacy:{minHeight:82,borderRadius:22,borderWidth:1,borderColor:`${palette.green}45`,backgroundColor:`${palette.green}0D`,padding:13,marginTop:11,flexDirection:'row',alignItems:'center',gap:10},bottomPrivacyText:{flex:1,color:palette.muted,fontSize:12.5,lineHeight:18},
});
