import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { loadLiveDashboard } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

type Filter='all'|'park'|'notice'|'mode'|'tag';
const eventLabels:Record<string,string>={
  PARKED:'PARK EDİLDİ',PARK_ENDED:'PARK SONLANDIRILDI',REPORT_RECEIVED:'BİLDİRİM ALINDI',MESSAGE_RECEIVED:'MESAJ ALINDI',NOTIFICATION_RECEIVED:'BİLDİRİM ALINDI',
  TAG_ACTIVATED:'ETİKET AKTİF',TAG_DISABLED:'ETİKET DEVRE DIŞI',TAG_TRANSFER_STARTED:'ETİKET DEVRİ BAŞLADI',TAG_TRANSFERRED:'ETİKET DEVREDİLDİ',
  VALET_STARTED:'VALE MODU BAŞLADI',VALET_ENDED:'VALE MODU BİTTİ',SERVICE_STARTED:'SERVİS MODU BAŞLADI',SERVICE_ENDED:'SERVİS MODU BİTTİ',GUEST_DRIVER_STARTED:'MİSAFİR SÜRÜCÜ BAŞLADI',GUEST_DRIVER_ENDED:'MİSAFİR SÜRÜCÜ BİTTİ',
};
const metadataLabels:Record<string,string>={parkId:'Park kaydı',reportId:'Bildirim kaydı',priority:'Öncelik',tagCode:'Etiket',vehicleId:'Araç',modeType:'Mod',state:'Durum'};
const valueLabels:Record<string,string>={normal:'Normal',high:'Yüksek',emergency:'Acil',ACTIVATED:'Aktif',PARKED:'Park edildi',REPORT_RECEIVED:'Bildirim alındı'};
function classify(value:string):Filter{const x=String(value||'').toUpperCase();if(x.includes('PARK'))return'park';if(x.includes('REPORT')||x.includes('MESSAGE')||x.includes('NOTIFICATION'))return'notice';if(x.includes('VALET')||x.includes('SERVICE')||x.includes('GUEST'))return'mode';if(x.includes('TAG')||x.includes('ACTIVAT')||x.includes('TRANSFER'))return'tag';return'all'}
function icon(value:string){const k=classify(value);if(k==='park')return'map-marker-outline' as const;if(k==='notice')return'bell-outline' as const;if(k==='mode')return'car-key' as const;if(k==='tag')return'nfc' as const;return'history' as const}
function color(value:string){const k=classify(value);if(k==='park')return palette.orange;if(k==='notice')return palette.cyan;if(k==='mode')return palette.purple;if(k==='tag')return palette.green;return palette.muted}
function eventLabel(value:string){const key=String(value||'').toUpperCase();return eventLabels[key]||key.replaceAll('_',' ').replace('REPORT','BİLDİRİM').replace('MESSAGE','MESAJ').replace('TAG','ETİKET').replace('PARKED','PARK EDİLDİ')}
export default function TimelineScreen(){
  const [data,setData]=useState<any>(null);const [filter,setFilter]=useState<Filter>('all');const [vehicleId,setVehicleId]=useState<string|null>(null);
  async function refresh(){try{setData(await loadLiveDashboard())}catch{router.replace('/auth')}}useEffect(()=>{void refresh()},[]);
  const events=useMemo(()=>data?data.timeline.filter((item:any)=>(filter==='all'||classify(item.event_type)===filter)&&(!vehicleId||item.vehicle_id===vehicleId)):[],[data,filter,vehicleId]);
  if(!data)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple}/><View style={s.loading}><ActivityIndicator color={palette.purple}/><Text style={s.loadingText}>Araç geçmişi hazırlanıyor…</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.purple} secondary={palette.cyan}/><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
    <ScreenHeader title="Araç Geçmişi" eyebrow="ARAÇ HAFIZASI" accent={palette.purple} subtitle="Park, bildirim, etiket ve geçici araç modlarını kronolojik olarak takip et." right={<Pressable onPress={()=>void refresh()} style={s.refresh}><MaterialCommunityIcons name="refresh" size={22} color={palette.purple}/></Pressable>}/>
    <View style={s.summary}><View style={[s.summaryIcon,{backgroundColor:`${palette.purple}20`}]}><MaterialCommunityIcons name="history" size={31} color={palette.purple}/></View><View style={{flex:1}}><Text style={s.summaryValue}>{events.length} olay gösteriliyor</Text><Text style={s.summaryBody}>Toplam hafıza: {data.timeline.length} kayıt • son 100 olay canlı tutuluyor</Text></View></View>
    <SectionHeading title="Araç seç" subtitle="Araç geçmişini tek araca daralt"/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}><Chip on={!vehicleId} title="Tüm araçlar" onPress={()=>setVehicleId(null)}/>{data.vehicles.map((v:any)=><Chip key={v.id} on={vehicleId===v.id} title={v.vehicle_name} onPress={()=>setVehicleId(v.id)}/>)}</ScrollView>
    <SectionHeading title="Olay türü" subtitle="İstediğin kategoriye odaklan"/>
    <View style={s.filterRow}>{([['all','Tümü','apps'],['park','Park','parking'],['notice','Bildirim','bell-outline'],['mode','Modlar','car-key'],['tag','Etiket','nfc']] as const).map(([key,label,filterIcon])=><Pressable key={key} onPress={()=>setFilter(key)} style={[s.filter,filter===key&&s.filterOn]}><MaterialCommunityIcons name={filterIcon} size={20} color={filter===key?palette.purple:palette.muted}/><Text style={[s.filterText,filter===key&&{color:palette.text}]}>{label}</Text></Pressable>)}</View>
    <SectionHeading title="Olay akışı" subtitle="En yeni olay üstte" badge={`${events.length} OLAY`} color={palette.purple}/>
    {events.length===0?<View style={s.empty}><MaterialCommunityIcons name="history" size={39} color={palette.muted}/><Text style={s.emptyTitle}>Bu filtrede olay yok</Text><Text style={s.emptyBody}>Yeni park ve araç olayları oluştukça burada görünecek.</Text></View>:<View style={s.timeline}>{events.map((item:any,index:number)=>{const c=color(item.event_type);return <View key={item.id||`${item.event_type}-${index}`} style={s.event}><View style={s.railLine}>{index<events.length-1?<View style={s.line}/>:null}<View style={[s.dot,{borderColor:`${c}60`,backgroundColor:`${c}18`}]}><MaterialCommunityIcons name={icon(item.event_type)} size={22} color={c}/></View></View><View style={[s.eventCard,{borderColor:`${c}35`}]}><View style={s.eventTop}><Text style={s.eventTitle}>{item.title||eventLabel(item.event_type)}</Text><Text style={s.eventTime}>{new Date(item.occurred_at).toLocaleString('tr-TR')}</Text></View><Text style={s.eventBody}>{item.description||formatMetadata(item.metadata)}</Text><View style={[s.typeBadge,{backgroundColor:`${c}12`,borderColor:`${c}35`}]}><Text style={[s.typeText,{color:c}]}>{eventLabel(item.event_type)}</Text></View></View></View>})}</View>}
  </ScrollView></SafeAreaView>;
}
function formatMetadata(metadata:any){if(!metadata||Object.keys(metadata).length===0)return'Araç olayı kaydedildi.';return Object.entries(metadata).slice(0,3).map(([key,value])=>`${metadataLabels[key]||key}: ${valueLabels[String(value)]||String(value)}`).join(' • ')}
function Chip({on,title,onPress}:{on:boolean;title:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.chip,on&&s.chipOn]}><Text style={[s.chipText,on&&{color:palette.text}]}>{title}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:50},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12},loadingText:{color:palette.muted,fontSize:type.body},refresh:{width:48,height:48,borderRadius:17,borderWidth:1,borderColor:`${palette.purple}45`,backgroundColor:`${palette.purple}0E`,alignItems:'center',justifyContent:'center'},summary:{minHeight:116,borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.purple}45`,backgroundColor:`${palette.purple}0E`,padding:16,flexDirection:'row',alignItems:'center',gap:13},summaryIcon:{width:60,height:60,borderRadius:20,alignItems:'center',justifyContent:'center'},summaryValue:{color:palette.text,fontSize:type.section,fontWeight:'900'},summaryBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:4},rail:{gap:8,paddingRight:14},chip:{minHeight:46,borderRadius:15,borderWidth:1,borderColor:palette.line,paddingHorizontal:13,alignItems:'center',justifyContent:'center'},chipOn:{borderColor:`${palette.purple}55`,backgroundColor:`${palette.purple}10`},chipText:{color:palette.muted,fontSize:type.caption,fontWeight:'900'},filterRow:{flexDirection:'row',gap:7},filter:{flex:1,minHeight:72,borderRadius:17,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center',gap:5,paddingHorizontal:4},filterOn:{borderColor:`${palette.purple}55`,backgroundColor:`${palette.purple}10`},filterText:{color:palette.muted,fontSize:type.micro,fontWeight:'900'},timeline:{gap:0},event:{flexDirection:'row',gap:12},railLine:{width:48,alignItems:'center'},line:{position:'absolute',top:50,bottom:-4,width:2,backgroundColor:palette.lineSoft},dot:{width:46,height:46,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},eventCard:{flex:1,borderRadius:radius.md,borderWidth:1,backgroundColor:palette.panel,padding:15,marginBottom:12},eventTop:{flexDirection:'row',alignItems:'flex-start',gap:9},eventTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',flex:1},eventTime:{color:palette.muted2,fontSize:type.micro,maxWidth:105,textAlign:'right'},eventBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:6},typeBadge:{alignSelf:'flex-start',borderRadius:999,borderWidth:1,paddingHorizontal:9,paddingVertical:6,marginTop:10},typeText:{fontSize:type.micro,fontWeight:'900'},empty:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:28,alignItems:'center'},emptyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:10},emptyBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,textAlign:'center',marginTop:5}});