import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { createVehicle, loadLiveDashboard } from '@/src/lib/drabornpark';
import { palette, radius } from '@/src/theme';

export default function VehicleScreen() {
  const [type,setType]=useState<'car'|'motorcycle'>('car'); const [name,setName]=useState(''); const [plate,setPlate]=useState(''); const [brand,setBrand]=useState(''); const [model,setModel]=useState(''); const [year,setYear]=useState(''); const [color,setColor]=useState(''); const [busy,setBusy]=useState(false); const [vehicles,setVehicles]=useState<any[]>([]);
  useEffect(()=>{loadLiveDashboard().then(d=>setVehicles(d.vehicles)).catch(()=>router.replace('/auth'));},[]);
  async function save(){if(!name.trim()){Alert.alert('Araç adı gerekli','Örn. Tiguan, Aile Aracı veya Motorum.');return;} setBusy(true);try{await createVehicle({vehicleName:name,plate,brand,model,modelYear:year?Number(year):null,color,vehicleType:type});Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Araç eklendi','Şimdi DraBornPark etiketini bu araca bağlayabilirsin.',[{text:'Etiket Aktivasyonu',onPress:()=>router.replace('/activate/new')},{text:'Ana Sayfa',onPress:()=>router.replace('/')}]);}catch(e:any){Alert.alert('Araç eklenemedi',e?.message||'İşlem başarısız.');}finally{setBusy(false)}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><Head/><Text style={styles.over}>ARAÇ PROFİLİ</Text><Text style={styles.title}>DraBornPark’a aracını ekle</Text><Text style={styles.sub}>Plaka, marka/model ve renk bilgilerinin QR/NFC ekranında görünürlüğünü daha sonra ayrı ayrı yönetebilirsin.</Text>
  {vehicles.length>0?<View style={styles.current}><Text style={styles.currentTitle}>MEVCUT ARAÇLAR</Text>{vehicles.map(v=><View key={v.id} style={styles.row}><MaterialCommunityIcons name={v.vehicle_type==='motorcycle'?'motorbike':'car'} size={21} color={palette.cyan}/><View style={{flex:1}}><Text style={styles.rowTitle}>{v.vehicle_name}</Text><Text style={styles.rowSub}>{[v.plate,v.brand,v.model].filter(Boolean).join(' • ')}</Text></View></View>)}</View>:null}
  <Text style={styles.label}>ARAÇ TİPİ</Text><View style={styles.types}><Pressable onPress={()=>setType('car')} style={[styles.type,type==='car'&&styles.typeActive]}><MaterialCommunityIcons name="car-sports" size={28} color={type==='car'?palette.cyan:palette.muted}/><Text style={[styles.typeText,type==='car'&&{color:palette.cyan}]}>ARABA</Text></Pressable><Pressable onPress={()=>setType('motorcycle')} style={[styles.type,type==='motorcycle'&&styles.typeActive]}><MaterialCommunityIcons name="motorbike" size={28} color={type==='motorcycle'?palette.orange:palette.muted}/><Text style={[styles.typeText,type==='motorcycle'&&{color:palette.orange}]}>MOTOSİKLET</Text></Pressable></View>
  <View style={styles.form}><Field label="ARAÇ ADI *" value={name} set={setName} placeholder="Örn. Volkswagen Tiguan"/><Field label="PLAKA" value={plate} set={setPlate} placeholder="06 ABC 123" autoCapitalize="characters"/><View style={styles.double}><View style={{flex:1}}><Field label="MARKA" value={brand} set={setBrand} placeholder="Volkswagen"/></View><View style={{flex:1}}><Field label="MODEL" value={model} set={setModel} placeholder="Tiguan"/></View></View><View style={styles.double}><View style={{flex:1}}><Field label="MODEL YILI" value={year} set={setYear} placeholder="2025" keyboard="number-pad"/></View><View style={{flex:1}}><Field label="RENK" value={color} set={setColor} placeholder="Gece Mavisi"/></View></View><Pressable disabled={busy} onPress={save} style={[styles.cta,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={palette.bg}/>:<><MaterialCommunityIcons name="car" size={20} color={palette.bg}/><Text style={styles.ctaText}>ARACI KAYDET</Text></>}</Pressable></View>
  <View style={styles.info}><MaterialCommunityIcons name="shield-lock-outline" size={21} color={palette.green}/><Text style={styles.infoText}>Telefon, e-posta ve tam ad bu araç profiline kamusal olarak eklenmez. DraBornPark’ın dış kullanıcı ekranı kişisel bilgileri saklar.</Text></View></ScrollView></SafeAreaView>}
function Head(){return <View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><MaterialCommunityIcons name="chevron-left" size={27} color={palette.text}/></Pressable><Text style={styles.headTitle}>Araçlarım</Text><View style={{width:42}}/></View>}
function Field({label,value,set,placeholder,autoCapitalize='sentences',keyboard='default'}:{label:string;value:string;set:(v:string)=>void;placeholder:string;autoCapitalize?:any;keyboard?:any}){return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#59657A" autoCapitalize={autoCapitalize} keyboardType={keyboard} style={styles.input}/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:19,paddingBottom:55},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},headTitle:{color:palette.text,fontSize:14,fontWeight:'900'},over:{color:palette.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.6,marginTop:26},title:{color:palette.text,fontSize:28,fontWeight:'900',letterSpacing:-1,marginTop:7},sub:{color:palette.muted,fontSize:11.5,lineHeight:17,marginTop:8},current:{borderWidth:1,borderColor:palette.line,borderRadius:radius.lg,backgroundColor:palette.panel,padding:14,marginTop:18},currentTitle:{color:palette.muted,fontSize:8.5,fontWeight:'900',letterSpacing:1.1,marginBottom:7},row:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#171F31'},rowTitle:{color:palette.text,fontSize:12,fontWeight:'900'},rowSub:{color:palette.muted,fontSize:9.5,marginTop:2},label:{color:'#7E8BA3',fontSize:8.5,fontWeight:'900',letterSpacing:1.1,marginBottom:6,marginTop:12},types:{flexDirection:'row',gap:9},type:{flex:1,height:83,borderRadius:18,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,alignItems:'center',justifyContent:'center',gap:7},typeActive:{borderColor:'#23586A',backgroundColor:'#0E2730'},typeText:{color:palette.muted,fontSize:9,fontWeight:'900'},form:{marginTop:8,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15},double:{flexDirection:'row',gap:10},input:{height:50,borderRadius:14,borderWidth:1,borderColor:'#27324A',backgroundColor:'#090E18',color:palette.text,paddingHorizontal:13,fontSize:13},cta:{height:55,borderRadius:17,backgroundColor:palette.cyan,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:19},ctaText:{color:palette.bg,fontSize:10.5,fontWeight:'900'},info:{marginTop:13,borderRadius:17,borderWidth:1,borderColor:'#234336',backgroundColor:'#0C1C16',padding:13,flexDirection:'row',gap:10},infoText:{color:'#8DBAA5',fontSize:10,lineHeight:14.5,flex:1}});
