import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { createVehicle, loadLiveDashboard } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

export default function VehicleScreen(){
  const [vehicleType,setVehicleType]=useState<'car'|'motorcycle'>('car');const [name,setName]=useState('');const [plate,setPlate]=useState('');const [brand,setBrand]=useState('');const [model,setModel]=useState('');const [year,setYear]=useState('');const [color,setColor]=useState('');const [busy,setBusy]=useState(false);const [vehicles,setVehicles]=useState<any[]>([]);
  useEffect(()=>{loadLiveDashboard().then(d=>setVehicles(d.vehicles)).catch(()=>router.replace('/auth'))},[]);
  async function save(){if(!name.trim()){Alert.alert('Araç adı gerekli','Örn. Tiguan, Aile Aracı veya Motorum.');return;}setBusy(true);try{const created=await createVehicle({vehicleName:name,plate,brand,model,modelYear:year?Number(year):null,color,vehicleType});setVehicles(current=>[...current,created]);setName('');setPlate('');setBrand('');setModel('');setYear('');setColor('');Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);Alert.alert('Araç eklendi','Şimdi DraBornPark etiketini bu araca bağlayabilirsin.',[{text:'Etiket Aktivasyonu',onPress:()=>router.push('/activate/new')},{text:'Tamam'}]);}catch(e:any){Alert.alert('Araç eklenemedi',e?.message||'İşlem başarısız.');}finally{setBusy(false)}}
  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.blue} secondary={palette.cyan}/><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <ScreenHeader title="Araçlarım" eyebrow="KİŞİSEL FİLO" accent={palette.blue} subtitle="Araba ve motosiklet profillerini aynı DraBornPark hesabında yönet."/>
    {vehicles.length?<><SectionHeading title="Kayıtlı araçlar" subtitle="Etiket ve park kayıtlarının bağlı olduğu araçlar" badge={`${vehicles.length} ARAÇ`} color={palette.blue}/><View style={s.list}>{vehicles.map(v=><View key={v.id} style={s.vehicle}><View style={[s.vehicleIcon,{backgroundColor:`${v.vehicle_type==='motorcycle'?palette.orange:palette.blue}1B`}]}><MaterialCommunityIcons name={v.vehicle_type==='motorcycle'?'motorbike':'car-sports'} size={29} color={v.vehicle_type==='motorcycle'?palette.orange:palette.blue}/></View><View style={{flex:1}}><Text style={s.vehicleTitle}>{v.vehicle_name}</Text><Text style={s.vehiclePlate}>{v.plate||'Plaka eklenmedi'}</Text><Text style={s.vehicleMeta}>{[v.brand,v.model,v.color].filter(Boolean).join(' • ')||'Profil ayrıntısı eklenmedi'}</Text></View><MaterialCommunityIcons name="shield-check-outline" size={24} color={palette.green}/></View>)}</View></>:null}
    <SectionHeading title="Yeni araç ekle" subtitle="Sonradan görünürlük ayarlarını ayrı ayrı değiştirebilirsin"/>
    <View style={s.typeRow}><TypeCard active={vehicleType==='car'} icon="car-sports" color={palette.cyan} title="Araba" detail="Otomobil, SUV, ticari" onPress={()=>setVehicleType('car')}/><TypeCard active={vehicleType==='motorcycle'} icon="motorbike" color={palette.orange} title="Motosiklet" detail="DraBornPark Moto" onPress={()=>setVehicleType('motorcycle')}/></View>
    <View style={s.form}><Field label="ARAÇ ADI *" value={name} set={setName} placeholder="Örn. Volkswagen Tiguan"/><Field label="PLAKA" value={plate} set={setPlate} placeholder="06 ABC 123" autoCapitalize="characters"/><View style={s.double}><View style={{flex:1}}><Field label="MARKA" value={brand} set={setBrand} placeholder="Volkswagen"/></View><View style={{flex:1}}><Field label="MODEL" value={model} set={setModel} placeholder="Tiguan"/></View></View><View style={s.double}><View style={{flex:1}}><Field label="MODEL YILI" value={year} set={setYear} placeholder="2025" keyboard="number-pad"/></View><View style={{flex:1}}><Field label="RENK" value={color} set={setColor} placeholder="Gece Mavisi"/></View></View><Pressable disabled={busy} onPress={save} style={[s.save,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><MaterialCommunityIcons name="car-plus" size={24} color={palette.ink}/><Text style={s.saveText}>ARACI KAYDET</Text><MaterialCommunityIcons name="arrow-right" size={21} color={palette.ink}/></>}</Pressable></View>
    <View style={s.privacy}><MaterialCommunityIcons name="shield-lock-outline" size={23} color={palette.green}/><Text style={s.privacyText}>Telefon, e-posta ve tam ad araç profiline kamusal bilgi olarak eklenmez. QR/NFC ekranında yalnızca izin verdiğin araç alanları gösterilir.</Text></View>
  </ScrollView></SafeAreaView>;
}
function TypeCard({active,icon,color,title,detail,onPress}:{active:boolean;icon:any;color:string;title:string;detail:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.typeCard,{borderColor:active?`${color}65`:palette.line,backgroundColor:active?`${color}12`:palette.panel}]}><View style={[s.typeIcon,{backgroundColor:`${color}20`}]}><MaterialCommunityIcons name={icon} size={31} color={color}/></View><Text style={s.typeTitle}>{title}</Text><Text style={s.typeDetail}>{detail}</Text>{active?<View style={[s.selected,{backgroundColor:color}]}><MaterialCommunityIcons name="check" size={14} color={palette.ink}/></View>:null}</Pressable>}
function Field({label,value,set,placeholder,autoCapitalize='sentences',keyboard='default'}:{label:string;value:string;set:(v:string)=>void;placeholder:string;autoCapitalize?:any;keyboard?:any}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={palette.muted2} autoCapitalize={autoCapitalize} keyboardType={keyboard} style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:50},list:{gap:10},vehicle:{minHeight:102,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15,flexDirection:'row',alignItems:'center',gap:13},vehicleIcon:{width:58,height:58,borderRadius:20,alignItems:'center',justifyContent:'center'},vehicleTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},vehiclePlate:{color:palette.cyan,fontSize:type.bodyStrong,fontWeight:'900',marginTop:3},vehicleMeta:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},typeRow:{flexDirection:'row',gap:11},typeCard:{flex:1,minHeight:154,borderRadius:radius.lg,borderWidth:1,padding:16},typeIcon:{width:56,height:56,borderRadius:19,alignItems:'center',justifyContent:'center'},typeTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:13},typeDetail:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},selected:{position:'absolute',right:13,top:13,width:26,height:26,borderRadius:13,alignItems:'center',justifyContent:'center'},form:{marginTop:15,borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:17},double:{flexDirection:'row',gap:10},label:{color:palette.blue,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:12,marginBottom:7},input:{height:57,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},save:{height:64,borderRadius:20,backgroundColor:palette.aqua,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10,marginTop:20},saveText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},privacy:{marginTop:14,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0C`,padding:15,flexDirection:'row',gap:11},privacyText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19}});
