import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AuroraBackground, ScreenHeader, SectionHeading } from '@/src/components/AppChrome';
import { createSupportRequest, hasPlusEntitlement, loadLiveDashboard, updatePrivacySettings } from '@/src/lib/drabornpark';
import { palette, radius, type } from '@/src/theme';

const redirects:Record<string,string>={tags:'/tags',family:'/family',guest:'/guest',valet:'/modes',service:'/modes',routing:'/routing',emergency:'/emergency',timeline:'/timeline'};
export default function FeatureScreen(){
  const {slug}=useLocalSearchParams<{slug?:string}>();const key=String(slug||'privacy');const redirect=redirects[key];const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [privacy,setPrivacy]=useState({showPlate:true,showBrandModel:true,showColor:true});
  useEffect(()=>{if(redirect){router.replace(redirect as any);return;}loadLiveDashboard().then(next=>{setData(next);const current=next.profile?.privacy_settings||{};setPrivacy({showPlate:current.showPlate!==false,showBrandModel:current.showBrandModel!==false,showColor:current.showColor!==false})}).catch(()=>router.replace('/auth'))},[redirect]);
  const plus=useMemo(()=>data?hasPlusEntitlement(data.profile,data.subscription):false,[data]);
  async function savePrivacy(){setBusy(true);try{await updatePrivacySettings(privacy);Alert.alert('Gizlilik güncellendi','QR/NFC ekranında gösterilecek araç alanları kaydedildi.')}catch(e:any){Alert.alert('Kaydedilemedi',String(e?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  async function sendSupport(){if(!subject.trim()||!body.trim())return Alert.alert('Eksik bilgi','Konu ve açıklama gerekli.');setBusy(true);try{await createSupportRequest(subject,body);setSubject('');setBody('');Alert.alert('Destek kaydı oluşturuldu','Talebin DraBornPark Care sistemine kaydedildi.')}catch(e:any){Alert.alert('Gönderilemedi',String(e?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  if(redirect||!data)return <SafeAreaView style={s.safe}><AuroraBackground/><View style={s.loading}><ActivityIndicator color={palette.cyan}/></View></SafeAreaView>;
  const support=key==='support';const plusPage=key==='plus';const color=support?palette.blue:plusPage?palette.yellow:palette.green;const title=support?'DraBornPark Care':plusPage?'DraBornPark+':'Gizlilik Merkezi';const icon=support?'lifebuoy':plusPage?'crown-outline':'shield-lock-outline';
  return <SafeAreaView style={s.safe}><AuroraBackground accent={color} secondary={palette.purple}/><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <ScreenHeader title={title} eyebrow={support?'DESTEK MERKEZİ':plusPage?'PREMIUM EXPERIENCE':'PRIVACY FIRST'} accent={color} subtitle={support?'Etiket, park, bildirim veya hesap sorunlarını güvenli destek kaydıyla ilet.':plusPage?'Basic ve Plus özelliklerinin durumunu tek yerde gör.':'QR/NFC ziyaretçisinin görebileceği araç alanlarını sen belirlersin.'}/>
    <View style={[s.hero,{borderColor:`${color}45`,backgroundColor:`${color}0E`}]}><View style={[s.heroIcon,{backgroundColor:`${color}20`}]}><MaterialCommunityIcons name={icon as any} size={35} color={color}/></View><View style={{flex:1}}><Text style={s.heroTitle}>{support?'Sorununu doğru yere ulaştır.':plusPage?(plus?'Plus aktif':'Basic aktif'):'Kişisel bilgiler varsayılan olarak gizli.'}</Text><Text style={s.heroBody}>{support?'DraBornPark Care kayıtların hesabına bağlı tutulur.':plusPage?'Etiketin Basic fonksiyonları abonelik sona erse bile çalışmaya devam eder.':'Telefon, e-posta, tam ad ve park geçmişi bu ayarlardan bağımsız olarak kamusal değildir.'}</Text></View></View>
    {!support&&!plusPage?<><SectionHeading title="Kamusal araç alanları" subtitle="Dış QR/NFC ekranında görünmesini istediğin bilgileri seç"/><View style={s.panel}><Toggle icon="card-account-details-outline" color={palette.cyan} title="Plaka" detail="Araç plakası gösterilsin" value={privacy.showPlate} set={v=>setPrivacy(c=>({...c,showPlate:v}))}/><Toggle icon="car-info" color={palette.blue} title="Marka ve model" detail="Araç marka/model bilgisi gösterilsin" value={privacy.showBrandModel} set={v=>setPrivacy(c=>({...c,showBrandModel:v}))}/><Toggle icon="palette-outline" color={palette.purple} title="Araç rengi" detail="Kayıtlı renk dış kullanıcıya gösterilsin" value={privacy.showColor} set={v=>setPrivacy(c=>({...c,showColor:v}))}/></View><View style={s.locked}><MaterialCommunityIcons name="lock" size={23} color={palette.green}/><Text style={s.lockedText}>Telefon, e-posta, tam ad ve park geçmişi hiçbir zaman bu görünürlük anahtarlarıyla açılmaz.</Text></View><Button color={palette.green} busy={busy} label="GİZLİLİĞİ KAYDET" onPress={savePrivacy}/></>:null}
    {support?<><SectionHeading title="Yeni destek kaydı" subtitle="Sorunu kısa ve anlaşılır şekilde anlat"/><View style={s.panel}><Field label="KONU" value={subject} set={setSubject} placeholder="Etiket aktivasyonu"/><Text style={s.label}>AÇIKLAMA</Text><TextInput value={body} onChangeText={setBody} multiline placeholder="Sorunu ve denediğin adımları anlat…" placeholderTextColor={palette.muted2} style={[s.input,s.area]}/><Button color={palette.blue} busy={busy} label="DESTEK KAYDI OLUŞTUR" onPress={sendSupport}/></View><View style={s.locked}><MaterialCommunityIcons name="shield-lock-outline" size={23} color={palette.green}/><Text style={s.lockedText}>Destek kaydı yalnızca oturum açmış kullanıcı hesabına bağlı olarak kaydedilir.</Text></View></>:null}
    {plusPage?<><SectionHeading title="Üyelik durumu" subtitle="Premium hakların ve Basic güvencen"/><View style={[s.plan,{borderColor:`${plus?palette.yellow:palette.blue}50`}]}><View style={s.planTop}><View style={[s.planIcon,{backgroundColor:`${palette.yellow}20`}]}><MaterialCommunityIcons name="crown" size={34} color={palette.yellow}/></View><View style={{flex:1}}><Text style={s.planStatus}>{plus?'DraBornPark+ AKTİF':'DraBornPark Basic'}</Text><Text style={s.planBody}>{data.profile?.plus_trial_until?`Deneme bitişi: ${new Date(data.profile.plus_trial_until).toLocaleString('tr-TR')}`:'Basic etiket özellikleri üyelikten bağımsızdır.'}</Text></View></View></View><SectionHeading title="Plus özellikleri" subtitle="Sunucu tarafında üyelik yetkisiyle korunur"/><View style={s.features}>{[
      ['account-group-outline','Family','Aile üyeleri ve izin bazlı park/bildirim paylaşımı'],['account-clock-outline','Geçici Sürücü','Süreli iletişim yönlendirmesi'],['car-key','Vale / Servis','Araç teslimi ve servis durumları'],['clock-outline','Zaman Kuralları','Gün ve saate göre akıllı yönlendirme'],['alert-circle-outline','Acil Durum Zinciri','Öncelikli acil kişi sıralaması'],['history','Gelişmiş Timeline','Araç olaylarını filtreli geçmişte inceleme'],['chart-donut','Aylık Özet','Park ve bildirim kullanım özeti']
    ].map(([featureIcon,featureTitle,detail])=><View key={featureTitle} style={s.feature}><View style={s.featureIcon}><MaterialCommunityIcons name={featureIcon as any} size={23} color={palette.yellow}/></View><View style={{flex:1}}><Text style={s.featureTitle}>{featureTitle}</Text><Text style={s.featureBody}>{detail}</Text></View><MaterialCommunityIcons name={plus?'check-circle':'lock-outline'} size={21} color={plus?palette.green:palette.muted}/></View>)}</View><View style={s.billing}><MaterialCommunityIcons name="google-play" size={24} color={palette.cyan}/><Text style={s.billingText}>Gerçek Google Play satın alma ve yenileme doğrulaması Expo Go içinde test edilemez; development build + Play Console bağlantısı gereken sonraki katmandır.</Text></View></>:null}
  </ScrollView></SafeAreaView>;
}
function Toggle({icon,color,title,detail,value,set}:{icon:any;color:string;title:string;detail:string;value:boolean;set:(v:boolean)=>void}){return <View style={s.toggle}><View style={[s.toggleIcon,{backgroundColor:`${color}18`}]}><MaterialCommunityIcons name={icon} size={23} color={color}/></View><View style={{flex:1}}><Text style={s.toggleTitle}>{title}</Text><Text style={s.toggleBody}>{detail}</Text></View><Switch value={value} onValueChange={set} trackColor={{false:'#315064',true:`${color}88`}} thumbColor={value?color:'#A9BBC6'}/></View>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={palette.muted2} style={s.input}/></View>}
function Button({color,busy,label,onPress}:{color:string;busy:boolean;label:string;onPress:()=>void}){return <Pressable disabled={busy} onPress={onPress} style={[s.button,{backgroundColor:color},busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><Text style={s.buttonText}>{label}</Text><MaterialCommunityIcons name="arrow-right" size={21} color={palette.ink}/></>}</Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:50},loading:{flex:1,alignItems:'center',justifyContent:'center'},hero:{minHeight:158,borderRadius:radius.xl,borderWidth:1,padding:19,flexDirection:'row',alignItems:'center',gap:15},heroIcon:{width:68,height:68,borderRadius:23,alignItems:'center',justifyContent:'center'},heroTitle:{color:palette.text,fontSize:23,fontWeight:'900',lineHeight:28},heroBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:6},panel:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,paddingHorizontal:16},toggle:{minHeight:88,borderBottomWidth:1,borderBottomColor:palette.lineSoft,flexDirection:'row',alignItems:'center',gap:12},toggleIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},toggleTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},toggleBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},locked:{marginTop:14,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0D`,padding:15,flexDirection:'row',gap:11},lockedText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19},label:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:13,marginBottom:7},input:{height:56,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},area:{height:140,textAlignVertical:'top',paddingTop:14},button:{height:63,borderRadius:20,marginTop:18,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},buttonText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},plan:{borderRadius:radius.xl,borderWidth:1,backgroundColor:palette.panel,padding:18},planTop:{flexDirection:'row',alignItems:'center',gap:13},planIcon:{width:62,height:62,borderRadius:21,alignItems:'center',justifyContent:'center'},planStatus:{color:palette.text,fontSize:type.section,fontWeight:'900'},planBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:4},features:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,paddingHorizontal:15},feature:{minHeight:84,borderBottomWidth:1,borderBottomColor:palette.lineSoft,flexDirection:'row',alignItems:'center',gap:11},featureIcon:{width:46,height:46,borderRadius:16,backgroundColor:`${palette.yellow}14`,alignItems:'center',justifyContent:'center'},featureTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},featureBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},billing:{marginTop:14,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.cyan}38`,backgroundColor:`${palette.cyan}0B`,padding:15,flexDirection:'row',gap:11},billingText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19}});
