import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import {router,useLocalSearchParams} from 'expo-router';
import React,{useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AuroraBackground,ScreenHeader,SectionHeading} from '@/src/components/AppChrome';
import {ColorPopup} from '@/src/components/ColorPopup';
import {DraBornParkPlusPanel} from '@/src/components/DraBornParkPlusPanel';
import {SupportCenterPanel} from '@/src/components/SupportCenterPanel';
import {hasPlusEntitlement,loadLiveDashboard,updatePrivacySettings} from '@/src/lib/drabornpark';
import {palette,radius,type} from '@/src/theme';

const redirects:Record<string,string>={tags:'/tags',family:'/family',guest:'/guest',valet:'/modes',service:'/modes',routing:'/routing',emergency:'/emergency',timeline:'/timeline'};
export default function FeatureScreen(){
  const {slug}=useLocalSearchParams<{slug?:string}>();const key=String(slug||'privacy');const redirect=redirects[key];const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [dkdNoTagPopup,setDkdNoTagPopup]=useState(false);const [privacy,setPrivacy]=useState({showPlate:true,showBrandModel:true,showColor:true});
  useEffect(()=>{if(redirect){router.replace(redirect as any);return;}loadLiveDashboard().then(next=>{setData(next);if(key==='plus'&&(next.tags??[]).length===0)setDkdNoTagPopup(true);const current=next.profile?.privacy_settings||{};setPrivacy({showPlate:current.showPlate!==false,showBrandModel:current.showBrandModel!==false,showColor:current.showColor!==false})}).catch(()=>router.replace('/auth'))},[redirect]);
  const plus=useMemo(()=>data?hasPlusEntitlement(data.profile,data.subscription):false,[data]);
  async function savePrivacy(){setBusy(true);try{await updatePrivacySettings(privacy);Alert.alert('Gizlilik güncellendi','QR/NFC ekranında gösterilecek araç alanları kaydedildi.')}catch(error:any){Alert.alert('Kaydedilemedi',String(error?.message||'İşlem başarısız.'))}finally{setBusy(false)}}
  if(redirect||!data)return <SafeAreaView style={s.safe}><AuroraBackground/><View style={s.loading}><ActivityIndicator color={palette.cyan}/></View></SafeAreaView>;
  const support=key==='support';const plusPage=key==='plus';const color=support?palette.blue:plusPage?palette.yellow:palette.green;const title=support?'Nasıl Yardımcı Olabiliriz?':plusPage?'DraBornPark+':'Gizlilik Merkezi';const icon=support?'lifebuoy':plusPage?'crown-outline':'shield-lock-outline';
  return <SafeAreaView style={s.safe}><AuroraBackground accent={color} secondary={palette.purple}/><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <ScreenHeader title={title} eyebrow={support?'DESTEK MERKEZİ':plusPage?'PREMIUM ARAÇ DENEYİMİ':'PRIVACY FIRST'} accent={color} subtitle={support?'Etiket, park, bildirim, abonelik veya hesap sorunlarını tek merkezden ilet ve takip et.':plusPage?'14 günlük etiket ödülünü ve Google Play aylık/yıllık üyeliğini anlaşılır biçimde yönet.':'QR/NFC ziyaretçisinin görebileceği araç alanlarını sen belirlersin.'}/>
    {!plusPage?<View style={[s.hero,{borderColor:`${color}55`,backgroundColor:`${color}10`}]}><View style={[s.heroIcon,{backgroundColor:`${color}22`}]}><MaterialCommunityIcons name={icon as any} size={35} color={color}/></View><View style={{flex:1}}><Text style={s.heroTitle}>{support?'Sorununu doğru kişiye ulaştır.':'Kişisel bilgiler varsayılan olarak gizli.'}</Text><Text style={s.heroBody}>{support?'Yeni kayıt admin tarafına anında düşer; kayıt durumunu aynı ekrandan takip edebilirsin.':'Telefon, e-posta, tam ad ve park geçmişi bu ayarlardan bağımsız olarak kamusal değildir.'}</Text></View></View>:null}
    {support?<SupportCenterPanel/>:null}
    {plusPage?<DraBornParkPlusPanel data={data} plus={plus}/>:null}
    {!support&&!plusPage?<><SectionHeading title="Kamusal araç alanları" subtitle="Dış QR/NFC ekranında görünmesini istediğin bilgileri seç"/><View style={s.panel}><Toggle icon="card-account-details-outline" color={palette.cyan} title="Plaka" detail="Araç plakası gösterilsin" value={privacy.showPlate} set={value=>setPrivacy(current=>({...current,showPlate:value}))}/><Toggle icon="car-info" color={palette.blue} title="Marka ve model" detail="Araç marka/model bilgisi gösterilsin" value={privacy.showBrandModel} set={value=>setPrivacy(current=>({...current,showBrandModel:value}))}/><Toggle icon="palette-outline" color={palette.purple} title="Araç rengi" detail="Kayıtlı renk dış kullanıcıya gösterilsin" value={privacy.showColor} set={value=>setPrivacy(current=>({...current,showColor:value}))}/></View><View style={s.locked}><MaterialCommunityIcons name="lock" size={23} color={palette.green}/><Text style={s.lockedText}>Telefon, e-posta, tam ad ve park geçmişi hiçbir zaman bu görünürlük anahtarlarıyla açılmaz.</Text></View><Pressable disabled={busy} onPress={()=>void savePrivacy()} style={[s.button,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><Text style={s.buttonText}>GİZLİLİĞİ KAYDET</Text><MaterialCommunityIcons name="arrow-right" size={21} color={palette.ink}/></>}</Pressable></>:null}
    <ColorPopup visible={dkdNoTagPopup} icon="nfc" eyebrow="BAĞLI ETİKET BULUNMUYOR" title="DraBornPark+ ve etiket birlikte daha güçlü" body="Abonelik seçeneklerini yine de inceleyebilirsin. Etiket bağladığında 14 günlük etiket ödülü, NFC/QR araç iletişimi ve Plus ile otomatik etiket koruması devreye girer." accent={palette.cyan} secondary={palette.yellow} primaryLabel="DRABORNPARK+ SAYFASINI AÇ" onPrimary={()=>setDkdNoTagPopup(false)} secondaryLabel="ETİKET AKTİVE ET" onSecondary={()=>{setDkdNoTagPopup(false);router.push('/activate/new')}} chips={['ETİKET ÖDÜLÜ','NFC + QR','GOOGLE PLAY']}/>
  </ScrollView></SafeAreaView>;
}
function Toggle({icon,color,title,detail,value,set}:{icon:any;color:string;title:string;detail:string;value:boolean;set:(value:boolean)=>void}){return <View style={s.toggle}><View style={[s.toggleIcon,{backgroundColor:`${color}18`}]}><MaterialCommunityIcons name={icon} size={23} color={color}/></View><View style={{flex:1}}><Text style={s.toggleTitle}>{title}</Text><Text style={s.toggleBody}>{detail}</Text></View><Switch value={value} onValueChange={set} trackColor={{false:'#315064',true:`${color}88`}} thumbColor={value?color:'#A9BBC6'}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:60},loading:{flex:1,alignItems:'center',justifyContent:'center'},hero:{minHeight:158,borderRadius:radius.xl,borderWidth:1,padding:19,flexDirection:'row',alignItems:'center',gap:15,marginBottom:14},heroIcon:{width:68,height:68,borderRadius:23,alignItems:'center',justifyContent:'center'},heroTitle:{color:palette.text,fontSize:23,fontWeight:'900',lineHeight:28},heroBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:6},panel:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,paddingHorizontal:16},toggle:{minHeight:88,borderBottomWidth:1,borderBottomColor:palette.lineSoft,flexDirection:'row',alignItems:'center',gap:12},toggleIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},toggleTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},toggleBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},locked:{marginTop:14,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}3D`,backgroundColor:`${palette.green}0D`,padding:15,flexDirection:'row',gap:11},lockedText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19},button:{height:63,borderRadius:20,backgroundColor:palette.green,marginTop:18,paddingHorizontal:17,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},buttonText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'}});
