import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import {router} from 'expo-router';
import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {ColorPopup} from '@/src/components/ColorPopup';
import {createSupportRequest} from '@/src/lib/drabornpark';
import {supabase} from '@/src/lib/supabase';
import {palette,radius,type} from '@/src/theme';

const statusText:Record<string,string>={open:'Açık',in_progress:'İnceleniyor',resolved:'Çözüldü',closed:'Kapalı'};
export function SupportCenterPanel(){
  const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [requests,setRequests]=useState<any[]>([]);const [admin,setAdmin]=useState(false);const [success,setSuccess]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const {data:userData}=await supabase.auth.getUser();const user=userData.user;if(!user)return;const {data:isAdmin}=await supabase.rpc('drabornpark_is_admin');setAdmin(Boolean(isAdmin));let query=supabase.from('drabornpark_support_requests').select('id,owner_user_id,subject,body,status,created_at,updated_at,admin_seen_at').order('created_at',{ascending:false}).limit(40);if(!isAdmin)query=query.eq('owner_user_id',user.id);const {data,error}=await query;if(error)throw error;setRequests(data??[]);}finally{setLoading(false)}},[]);
  useEffect(()=>{void load();const channel=supabase.channel(`dkd-support-v054-${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'drabornpark_support_requests'},()=>{void load()}).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
  async function send(){if(!subject.trim()||!body.trim())return;setBusy(true);try{await createSupportRequest(subject,body);setSubject('');setBody('');setSuccess(true);await load();}finally{setBusy(false)}}
  return <>
    <View style={s.form}><View style={s.formHead}><View style={s.formIcon}><MaterialCommunityIcons name="message-plus-outline" size={27} color={palette.blue}/></View><View style={{flex:1}}><Text style={s.formTitle}>Yeni destek kaydı</Text><Text style={s.formBody}>Sorunu, gördüğün mesajı ve denediğin adımları yaz.</Text></View></View><Text style={s.label}>KONU</Text><TextInput value={subject} onChangeText={setSubject} placeholder="Örn. Etiket aktivasyonu" placeholderTextColor={palette.muted2} style={s.input}/><Text style={s.label}>AÇIKLAMA</Text><TextInput value={body} onChangeText={setBody} multiline placeholder="Detayları buraya yaz…" placeholderTextColor={palette.muted2} style={[s.input,s.area]}/><Pressable disabled={busy||!subject.trim()||!body.trim()} onPress={()=>void send()} style={[s.send,(busy||!subject.trim()||!body.trim())&&{opacity:.45}]}>{busy?<ActivityIndicator color={palette.ink}/>:<><MaterialCommunityIcons name="send-check-outline" size={22} color={palette.ink}/><Text style={s.sendText}>DESTEK KAYDI OLUŞTUR</Text></>}</Pressable></View>
    <View style={s.heading}><View><Text style={s.headingTitle}>{admin?'Gelen destek kayıtları':'Destek kayıtlarım'}</Text><Text style={s.headingSub}>{admin?'Yeni kayıtlar bu ekrana ve admin bildirimlerine düşer.':'Taleplerinin güncel durumunu buradan izle.'}</Text></View><View style={s.count}><Text style={s.countText}>{requests.length}</Text></View></View>
    {loading?<View style={s.loading}><ActivityIndicator color={palette.blue}/><Text style={s.loadingText}>Destek kayıtları yükleniyor…</Text></View>:requests.length?<View style={s.list}>{requests.map(item=>{const unseen=admin&&!item.admin_seen_at;const color=item.status==='resolved'?palette.green:item.status==='closed'?palette.muted:unseen?palette.pink:palette.blue;return <Pressable key={item.id} onPress={()=>router.push({pathname:'/support/[id]',params:{id:item.id}} as any)} style={({pressed})=>[s.row,{borderColor:`${color}62`,backgroundColor:`${color}0F`},pressed&&s.pressed]}><View style={[s.rowIcon,{backgroundColor:`${color}20`}]}><MaterialCommunityIcons name={unseen?'email-alert-outline':'message-text-outline'} size={25} color={color}/>{unseen?<View style={s.newDot}/>:null}</View><View style={{flex:1,minWidth:0}}><View style={s.rowTop}><Text numberOfLines={1} style={s.rowTitle}>{item.subject}</Text><Text style={[s.status,{color}]}>{unseen?'YENİ':statusText[item.status]||item.status}</Text></View><Text numberOfLines={2} style={s.rowBody}>{item.body}</Text><Text style={s.rowDate}>{new Date(item.created_at).toLocaleString('tr-TR')}</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={color}/></Pressable>})}</View>:<View style={s.empty}><MaterialCommunityIcons name="lifebuoy" size={36} color={palette.muted2}/><Text style={s.emptyTitle}>Henüz destek kaydı yok</Text><Text style={s.emptyBody}>Bir sorun olduğunda yukarıdaki formdan doğrudan DraBornPark Destek Merkezi’ne ulaşabilirsin.</Text></View>}
    <ColorPopup visible={success} icon="message-check-outline" eyebrow="DESTEK MERKEZİ" title="Kaydın bize ulaştı" body="Destek kaydın oluşturuldu. Durumu bu sayfadan takip edebilirsin; admin tarafına yeni kayıt bildirimi gönderilir." accent={palette.blue} secondary={palette.purple} primaryLabel="TAMAM" onPrimary={()=>setSuccess(false)}/>
  </>;
}
const s=StyleSheet.create({form:{borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.blue}60`,backgroundColor:`${palette.blue}0D`,padding:16},formHead:{flexDirection:'row',alignItems:'center',gap:11},formIcon:{width:54,height:54,borderRadius:18,backgroundColor:`${palette.blue}20`,alignItems:'center',justifyContent:'center'},formTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},formBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:3},label:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:.8,marginTop:14,marginBottom:7},input:{minHeight:55,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},area:{height:130,textAlignVertical:'top',paddingTop:13},send:{minHeight:61,borderRadius:20,backgroundColor:palette.aqua,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},sendText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},heading:{marginTop:27,marginBottom:12,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},headingTitle:{color:palette.text,fontSize:type.section,fontWeight:'900'},headingSub:{color:palette.muted,fontSize:type.caption,marginTop:4,maxWidth:300},count:{minWidth:40,height:32,borderRadius:999,borderWidth:1,borderColor:`${palette.purple}60`,backgroundColor:`${palette.purple}18`,alignItems:'center',justifyContent:'center'},countText:{color:palette.purple,fontWeight:'900'},loading:{padding:30,alignItems:'center',gap:9},loadingText:{color:palette.muted,fontSize:type.caption},list:{gap:10},row:{minHeight:115,borderRadius:radius.md,borderWidth:1,padding:13,flexDirection:'row',alignItems:'center',gap:11},rowIcon:{width:52,height:52,borderRadius:18,alignItems:'center',justifyContent:'center'},newDot:{position:'absolute',right:6,top:6,width:8,height:8,borderRadius:4,backgroundColor:palette.pink},rowTop:{flexDirection:'row',alignItems:'center',gap:8},rowTitle:{flex:1,color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},status:{fontSize:10,fontWeight:'900'},rowBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},rowDate:{color:palette.muted2,fontSize:type.micro,marginTop:5},empty:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:25,alignItems:'center'},emptyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900',marginTop:9},emptyBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,textAlign:'center',marginTop:5},pressed:{opacity:.76,transform:[{scale:.988}]}});
