import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import * as ImagePicker from 'expo-image-picker';
import { useLocalSearchParams } from 'expo-router';
import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Easing, Image, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PUBLIC_CONTACT_URL } from '@/src/data';
import { AuroraBackground, SectionHeading } from '@/src/components/AppChrome';
import { palette, radius, type } from '@/src/theme';

type DkdCategory={key:string;title:string;body:string;priority:'normal'|'high'|'emergency'};
type DkdChatMessage={id:string;sender_role:string;body_safe:string;created_at:string};
type DkdEvidence={uri:string;base64:string;mime:'image/jpeg';capturedAt:string};

const dkd_shop_links=[
  {title:'Trendyol',detail:'Örnek satış kanalı',icon:'shopping-outline',color:palette.orange,url:'https://www.trendyol.com/'},
  {title:'Hepsiburada',detail:'Örnek satış kanalı',icon:'shopping-search',color:palette.pink,url:'https://www.hepsiburada.com/'},
  {title:'Amazon',detail:'Örnek satış kanalı',icon:'shopping',color:palette.cyan,url:'https://www.amazon.com.tr/'},
  {title:'DraBornPark Mağaza',detail:'Kendi e-ticaret alanımız • yakında',icon:'storefront-outline',color:palette.green,url:'https://www.draborneagle.com/DraBornPark/shop/'},
] as const;

async function dkd_call(body:any){
  const dkd_response=await fetch(PUBLIC_CONTACT_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  const dkd_data=await dkd_response.json().catch(()=>({}));
  if(!dkd_response.ok){const dkd_error:any=new Error(dkd_data?.error||'request_failed');dkd_error.status=dkd_response.status;dkd_error.retryAfter=dkd_data?.retryAfter;throw dkd_error;}
  return dkd_data;
}

export default function PublicTagScreen(){
  const {id}=useLocalSearchParams<{id?:string}>();
  const dkd_tag_code='DP-'+String(id||'').toUpperCase().replace(/^DP-/,'');
  const [dkd_snapshot,setDkdSnapshot]=useState<any>(null);
  const [dkd_categories,setDkdCategories]=useState<DkdCategory[]>([]);
  const [dkd_selected,setDkdSelected]=useState<DkdCategory|null>(null);
  const [dkd_message,setDkdMessage]=useState('');
  const [dkd_message_open,setDkdMessageOpen]=useState(false);
  const [dkd_evidence,setDkdEvidence]=useState<DkdEvidence|null>(null);
  const [dkd_loading,setDkdLoading]=useState(true);
  const [dkd_sending,setDkdSending]=useState(false);
  const [dkd_error,setDkdError]=useState('');
  const [dkd_session_token,setDkdSessionToken]=useState<string|null>(null);
  const [dkd_expires_at,setDkdExpiresAt]=useState<string|null>(null);
  const [dkd_messages,setDkdMessages]=useState<DkdChatMessage[]>([]);
  const [dkd_chat,setDkdChat]=useState('');
  const [dkd_chat_busy,setDkdChatBusy]=useState(false);
  const dkd_timer=useRef<ReturnType<typeof setInterval>|null>(null);

  useEffect(()=>{dkd_call({action:'lookup',tagCode:dkd_tag_code}).then(dkd_data=>{setDkdSnapshot(dkd_data.snapshot);setDkdCategories(dkd_data.categories||[])}).catch(()=>setDkdError('Bu DraBornPark etiketi bulunamadı veya şu anda kullanılamıyor.')).finally(()=>setDkdLoading(false))},[dkd_tag_code]);
  useEffect(()=>{if(!dkd_session_token)return;if(dkd_timer.current)clearInterval(dkd_timer.current);const dkd_poll=async()=>{try{const dkd_data=await dkd_call({action:'status',sessionToken:dkd_session_token});setDkdMessages(dkd_data.messages||[])}catch(dkd_problem:any){if(dkd_problem.status===410){setDkdSessionToken(null);setDkdError('Geçici iletişim oturumu sona erdi.')}}};void dkd_poll();dkd_timer.current=setInterval(dkd_poll,4000);return()=>{if(dkd_timer.current)clearInterval(dkd_timer.current)}},[dkd_session_token]);

  function dkd_open_direct_message(){
    const dkd_direct:DkdCategory={key:'direct_message',title:'Araç sahibine güvenli mesaj',body:'Araçla ilgili kısa ve güvenli bir mesaj gönderin. İsterseniz fotoğraf da ekleyebilirsiniz.',priority:'normal'};
    setDkdSelected(dkd_direct);setDkdMessageOpen(true);setDkdError('');
  }

  async function dkd_pick_evidence(){
    setDkdError('');
    try{
      let dkd_result:ImagePicker.ImagePickerResult;
      if(Platform.OS==='web'){
        dkd_result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'] as ImagePicker.MediaType[],allowsEditing:false,quality:.78,base64:true});
      }else{
        const dkd_permission=await ImagePicker.requestCameraPermissionsAsync();
        if(!dkd_permission.granted){setDkdError('Fotoğraf eklemek için kamera izni gerekiyor.');return;}
        dkd_result=await ImagePicker.launchCameraAsync({mediaTypes:['images'] as ImagePicker.MediaType[],allowsEditing:false,quality:.72,base64:true});
      }
      if(dkd_result.canceled||!dkd_result.assets?.[0])return;
      const dkd_asset:any=dkd_result.assets[0];
      if(!dkd_asset.base64){setDkdError('Fotoğraf hazırlanamadı. Lütfen tekrar deneyin.');return;}
      const dkd_mime=String(dkd_asset.mimeType||'image/jpeg').toLowerCase();
      if(dkd_mime!=='image/jpeg'){setDkdError(Platform.OS==='web'?'Web fotoğraf ekleme için JPG/JPEG dosyası seçmelisiniz.':'Güvenli fotoğraf gönderimi için JPEG formatı gerekiyor.');return;}
      setDkdEvidence({uri:dkd_asset.uri,base64:dkd_asset.base64,mime:'image/jpeg',capturedAt:new Date().toISOString()});
    }catch{setDkdError(Platform.OS==='web'?'Fotoğraf seçici açılamadı. Tarayıcı dosya erişimini kontrol edin.':'Kamera açılamadı. Kamera iznini kontrol edin.');}
  }

  async function dkd_notify(){
    if(!dkd_selected)return;setDkdSending(true);setDkdError('');
    try{
      const dkd_data=await dkd_call({action:'notify',tagCode:dkd_tag_code,category:dkd_selected.key,message:dkd_message,evidence:dkd_evidence?{base64:dkd_evidence.base64,mime:dkd_evidence.mime,capturedAt:dkd_evidence.capturedAt,stampLabel:'DraBornPark v0.5.5 • Güvenli Araç İletişimi'}:undefined});
      setDkdSessionToken(dkd_data.sessionToken);setDkdExpiresAt(dkd_data.expiresAt);setDkdMessage('');setDkdEvidence(null);setDkdMessageOpen(false);
    }catch(dkd_problem:any){
      const dkd_code=String(dkd_problem?.message||'');
      setDkdError(dkd_problem.status===429?'Çok fazla istek gönderildi. '+Math.ceil((dkd_problem.retryAfter||60)/60)+' dakika sonra tekrar deneyin.':dkd_code==='invalid_evidence'||dkd_code==='invalid_evidence_time'||dkd_code==='evidence_too_large'?'Fotoğraf güvenlik kontrolünden geçemedi. Yeni bir fotoğraf ekleyip tekrar deneyin.':'Bildirim gönderilemedi. Lütfen tekrar deneyin.');
    }finally{setDkdSending(false)}
  }

  async function dkd_send_chat(){
    if(!dkd_session_token||!dkd_chat.trim())return;setDkdChatBusy(true);
    try{await dkd_call({action:'chat',sessionToken:dkd_session_token,message:dkd_chat});setDkdChat('');const dkd_data=await dkd_call({action:'status',sessionToken:dkd_session_token});setDkdMessages(dkd_data.messages||[])}catch(dkd_problem:any){if(dkd_problem.status===410){setDkdSessionToken(null);setDkdError('Geçici iletişim oturumu sona erdi.')}else setDkdError('Mesaj gönderilemedi.')}finally{setDkdChatBusy(false)}
  }

  if(dkd_loading)return <SafeAreaView style={s.safe}><AuroraBackground/><View style={s.loading}><View style={s.logo}><MaterialCommunityIcons name="shield-car" size={43} color={palette.cyan}/></View><ActivityIndicator color={palette.cyan}/><Text style={s.loadingTitle}>DraBornPark</Text><Text style={s.loadingBody}>Etiket güvenli şekilde doğrulanıyor…</Text></View></SafeAreaView>;

  return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.cyan} secondary={palette.green}/><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <View style={s.brand}><View style={s.brandIcon}><MaterialCommunityIcons name="shield-car" size={28} color={palette.cyan}/></View><View style={{flex:1}}><Text style={s.brandKicker}>GÜVENLİ ARAÇ İLETİŞİMİ</Text><Text style={s.brandName}>DraBornPark</Text><Text style={s.brandBody}>Sahibine kişisel bilgilerini göstermeden ulaş.</Text></View><View style={s.secure}><MaterialCommunityIcons name="shield-check" size={19} color={palette.green}/><Text style={s.secureText}>GÜVENLİ</Text></View></View>
    {dkd_error&&!dkd_snapshot?<View style={s.error}><MaterialCommunityIcons name="alert-circle-outline" size={42} color={palette.red}/><Text style={s.errorTitle}>Etiket kullanılamıyor</Text><Text style={s.errorBody}>{dkd_error}</Text></View>:null}
    {dkd_snapshot?<>
      <View style={s.vehicle}><View style={s.vehicleIcon}><MaterialCommunityIcons name={dkd_snapshot.vehicle?.type==='motorcycle'?'motorbike':'car-sports'} size={36} color={palette.cyan}/></View><View style={{flex:1}}><Text style={s.protected}>DRABORNPARK KORUMALI ARAÇ</Text><Text style={s.vehicleName}>{dkd_snapshot.vehicle?.name||[dkd_snapshot.vehicle?.brand,dkd_snapshot.vehicle?.model].filter(Boolean).join(' ')||'Araç'}</Text><Text style={s.vehicleBody}>{[dkd_snapshot.vehicle?.plate,dkd_snapshot.vehicle?.color].filter(Boolean).join(' • ')||'Araç bilgileri gizli'}</Text><View style={s.publicBadges}><View style={[s.publicBadge,{borderColor:palette.purple+'70',backgroundColor:palette.purple+'18'}]}><MaterialCommunityIcons name="account-check-outline" size={23} color={palette.purple}/><Text style={[s.publicBadgeText,{color:palette.purple}]}>ARAÇ SAHİBİ •</Text></View><View style={[s.publicBadge,{borderColor:palette.green+'70',backgroundColor:palette.green+'18'}]}><MaterialCommunityIcons name="nfc-variant" size={23} color={palette.green}/><Text style={[s.publicBadgeText,{color:palette.green}]}>NFC + QR • AKTİF</Text></View></View></View></View>
      <View style={s.privacy}><MaterialCommunityIcons name="phone-lock" size={27} color={palette.green}/><View style={{flex:1}}><Text style={s.privacyTitle}>Telefon numarası gizlidir</Text><Text style={s.privacyBody}>Telefon, e-posta ve açık kimlik bilgileri gösterilmez. Bildirim DraBornPark üzerinden iletilir.</Text></View></View>
      {!dkd_session_token?<>
        <Pressable onPress={dkd_open_direct_message} style={({pressed})=>[s.messageEntry,pressed&&{opacity:.78}]}><View style={s.messageEntryIcon}><MaterialCommunityIcons name="message-text-fast-outline" size={30} color={palette.cyan}/></View><View style={{flex:1}}><Text style={s.messageEntryKicker}>HIZLI İLETİŞİM</Text><Text style={s.messageEntryTitle}>Mesaj Gönder</Text><Text style={s.messageEntryBody}>Burada kendi mesajını yaz, istersen fotoğraf ekle. Yeni Araç Bildirimi kartına yönlendirilmez.</Text></View><MaterialCommunityIcons name={dkd_message_open&&dkd_selected?.key==='direct_message'?'chevron-up':'arrow-right'} size={27} color={palette.cyan}/></Pressable>
        {dkd_message_open&&dkd_selected?<DkdComposer selected={dkd_selected} message={dkd_message} setMessage={setDkdMessage} evidence={dkd_evidence} setEvidence={setDkdEvidence} error={dkd_error} sending={dkd_sending} pickEvidence={dkd_pick_evidence} send={dkd_notify} close={()=>setDkdMessageOpen(false)}/>:null}
        <SectionHeading title="Ne bildirmek istiyorsunuz?" subtitle="Hazır durum kartlarından birini seçebilir veya yukarıdaki doğrudan mesaj alanını kullanabilirsiniz"/>
        <View style={s.grid}>{dkd_categories.map(dkd_category=>{const dkd_color=dkd_category.priority==='emergency'?palette.red:dkd_category.priority==='high'?palette.orange:palette.cyan;const dkd_active=dkd_selected?.key===dkd_category.key;return <Pressable key={dkd_category.key} onPress={()=>{setDkdSelected(dkd_category);setDkdMessageOpen(true);setDkdError('')}} style={[s.category,{borderColor:dkd_active?dkd_color:palette.line,backgroundColor:dkd_active?dkd_color+'12':palette.panel}]}><View style={[s.categoryIcon,{backgroundColor:dkd_color+'18'}]}><MaterialCommunityIcons name={dkd_category.priority==='emergency'?'alert-octagon-outline':dkd_category.priority==='high'?'alert-circle-outline':'message-alert-outline'} size={25} color={dkd_color}/></View><Text style={s.categoryTitle}>{dkd_category.title}</Text><Text numberOfLines={2} style={s.categoryBody}>{dkd_category.body}</Text>{dkd_category.priority==='emergency'?<View style={s.emergency}><Text style={s.emergencyText}>ACİL</Text></View>:null}</Pressable>})}</View>
      </>:<DkdChat expiresAt={dkd_expires_at} messages={dkd_messages} chat={dkd_chat} setChat={setDkdChat} busy={dkd_chat_busy} send={dkd_send_chat}/>} 
      <DkdMarketplacePromo/>
    </>:null}
    <Text style={s.footer}>DraBornPark • Aracına numaranı değil, DraBornPark'ı bırak.</Text>
  </ScrollView></SafeAreaView>;
}

function DkdComposer({selected,message,setMessage,evidence,setEvidence,error,sending,pickEvidence,send,close}:{selected:DkdCategory;message:string;setMessage:(value:string)=>void;evidence:DkdEvidence|null;setEvidence:(value:DkdEvidence|null)=>void;error:string;sending:boolean;pickEvidence:()=>Promise<void>;send:()=>Promise<void>;close:()=>void}){
  const dkd_color=selected.priority==='emergency'?palette.red:selected.priority==='high'?palette.orange:palette.cyan;
  return <View style={[s.compose,{borderColor:dkd_color+'68'}]}><View style={s.composeTop}><View style={{flex:1}}><Text style={[s.composeLabel,{color:dkd_color}]}>{selected.key==='direct_message'?'DOĞRUDAN GÜVENLİ MESAJ':'MESAJ YAZMA ALANI'}</Text><Text style={s.composeTitle}>{selected.key==='direct_message'||selected.key==='other'?'Araç sahibine güvenli mesaj':selected.title}</Text></View><Pressable onPress={close} style={s.composeClose}><MaterialCommunityIcons name="close" size={20} color={palette.muted}/></Pressable></View><Text style={s.composeBody}>{selected.body}</Text><TextInput value={message} onChangeText={setMessage} multiline maxLength={700} placeholder="Mesajınızı buraya yazın…" placeholderTextColor={palette.muted2} style={s.input}/>{evidence?<View style={s.photoPreview}><Image source={{uri:evidence.uri}} style={s.photoImage}/><View style={{flex:1}}><Text style={s.photoTitle}>Fotoğraf hazır</Text><Text style={s.photoBody}>Güvenli mesaja JPEG olarak eklenecek.</Text></View><Pressable onPress={()=>setEvidence(null)} style={s.photoRemove}><MaterialCommunityIcons name="delete-outline" size={21} color={palette.red}/></Pressable></View>:<Pressable onPress={()=>void pickEvidence()} style={s.photoPick}><View style={s.photoPickIcon}><MaterialCommunityIcons name="camera-plus-outline" size={25} color={palette.pink}/></View><View style={{flex:1}}><Text style={s.photoPickTitle}>FOTOĞRAF EKLE</Text><Text style={s.photoPickBody}>{Platform.OS==='web'?'JPG/JPEG seç • isteğe bağlı • en fazla 4 MB':'Kamerayı aç • isteğe bağlı • en fazla 4 MB'}</Text></View><MaterialCommunityIcons name="arrow-right" size={21} color={palette.pink}/></Pressable>}<View style={s.filter}><MaterialCommunityIcons name="shield-lock-outline" size={20} color={palette.cyan}/><Text style={s.filterText}>Mesaj kişisel bilgi ve saldırgan içerik filtresinden geçirilir. Fotoğraf private alanda tutulur.</Text></View>{error?<Text style={s.inlineError}>{error}</Text>:null}<Pressable disabled={sending||(!message.trim()&&!evidence)} onPress={()=>void send()} style={[s.send,(sending||(!message.trim()&&!evidence))&&{opacity:.48}]}>{sending?<ActivityIndicator color={palette.ink}/>:<><MaterialCommunityIcons name="shield-check-outline" size={23} color={palette.ink}/><Text style={s.sendText}>ARAÇ SAHİBİNE GÜVENLİ GÖNDER</Text></>}</Pressable></View>;
}

function DkdMarketplacePromo(){
  const dkd_pulse=useRef(new Animated.Value(0)).current;const dkd_sweep=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const dkd_a=Animated.loop(Animated.sequence([Animated.timing(dkd_pulse,{toValue:1,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}),Animated.timing(dkd_pulse,{toValue:0,duration:900,easing:Easing.inOut(Easing.cubic),useNativeDriver:true})]));const dkd_b=Animated.loop(Animated.timing(dkd_sweep,{toValue:1,duration:3000,easing:Easing.linear,useNativeDriver:true}));dkd_a.start();dkd_b.start();return()=>{dkd_a.stop();dkd_b.stop()}},[dkd_pulse,dkd_sweep]);
  return <Animated.View style={[s.promo,{transform:[{scale:dkd_pulse.interpolate({inputRange:[0,1],outputRange:[1,1.008]})}]}]}><Animated.View pointerEvents="none" style={[s.promoSweep,{transform:[{translateX:dkd_sweep.interpolate({inputRange:[0,1],outputRange:[-120,520]})},{rotate:'14deg'}]}]}/><View style={s.promoSpectrum}><View style={[s.promoBar,{backgroundColor:palette.cyan}]}/><View style={[s.promoBar,{backgroundColor:palette.purple}]}/><View style={[s.promoBar,{backgroundColor:palette.pink}]}/><View style={[s.promoBar,{backgroundColor:palette.orange}]}/><View style={[s.promoBar,{backgroundColor:palette.green}]}/></View><View style={s.promoHead}><Animated.View style={[s.promoIcon,{transform:[{scale:dkd_pulse.interpolate({inputRange:[0,1],outputRange:[1,1.09]})}]}]}><MaterialCommunityIcons name="shield-star-outline" size={32} color={palette.yellow}/></Animated.View><View style={{flex:1}}><Text style={s.promoKicker}>DRABORNPARK • ARAÇ GÜVENLİĞİ</Text><Text style={s.promoTitle}>Senin aracında da DraBornPark olsun</Text><Text style={s.promoBody}>Bu sayfayı bir araç üzerindeki QR/NFC etiketiyle açtıysan, kendi aracın için de DraBornPark etiketi edinebilirsin.</Text></View></View><View style={s.shopGrid}>{dkd_shop_links.map(dkd_link=><Pressable key={dkd_link.title} onPress={()=>void Linking.openURL(dkd_link.url)} style={[s.shopCard,{borderColor:dkd_link.color+'58',backgroundColor:dkd_link.color+'11'}]}><View style={[s.shopIcon,{backgroundColor:dkd_link.color+'20'}]}><MaterialCommunityIcons name={dkd_link.icon as any} size={22} color={dkd_link.color}/></View><View style={{flex:1}}><Text style={s.shopTitle}>{dkd_link.title}</Text><Text numberOfLines={2} style={s.shopBody}>{dkd_link.detail}</Text></View><MaterialCommunityIcons name="open-in-new" size={18} color={dkd_link.color}/></Pressable>)}</View><Text style={s.promoLegal}>Örnek bağlantılar • Resmî satıcı/iş ortaklığı gösterimi değildir. DraBornPark Mağaza alanı ileride kendi e-ticaret sitemize bağlanacaktır.</Text></Animated.View>;
}

function DkdChat({expiresAt,messages,chat,setChat,busy,send}:{expiresAt:string|null;messages:DkdChatMessage[];chat:string;setChat:(value:string)=>void;busy:boolean;send:()=>Promise<void>}){
  return <View style={s.chat}><View style={s.success}><MaterialCommunityIcons name="check-decagram-outline" size={35} color={palette.green}/><View style={{flex:1}}><Text style={s.successTitle}>Bildirim iletildi</Text><Text style={s.successBody}>Araç sahibi cevap verdiğinde bu geçici anonim oturum güncellenir.</Text></View></View><View style={s.session}><MaterialCommunityIcons name="timer-outline" size={22} color={palette.cyan}/><Text style={s.sessionText}>Anonim oturum • {expiresAt?new Date(expiresAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}):'30 dk'} tarihine kadar</Text></View><View style={s.messages}>{messages.length===0?<Text style={s.wait}>Araç sahibinin cevabı bekleniyor…</Text>:messages.map(dkd_item=><View key={dkd_item.id} style={[s.bubble,dkd_item.sender_role==='owner'?s.ownerBubble:s.visitorBubble]}><Text style={s.bubbleWho}>{dkd_item.sender_role==='owner'?'ARAÇ SAHİBİ':'SİZ'}</Text><Text style={s.bubbleText}>{dkd_item.body_safe}</Text><Text style={s.bubbleTime}>{new Date(dkd_item.created_at).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</Text></View>)}</View><View style={s.chatRow}><TextInput value={chat} onChangeText={setChat} maxLength={700} placeholder="Anonim cevap yaz…" placeholderTextColor={palette.muted2} style={s.chatInput}/><Pressable disabled={busy||!chat.trim()} onPress={()=>void send()} style={[s.chatSend,(busy||!chat.trim())&&{opacity:.5}]}>{busy?<ActivityIndicator color={palette.ink}/>:<MaterialCommunityIcons name="send" size={22} color={palette.ink}/>}</Pressable></View><Text style={s.chatNote}>Kişisel bilgiler otomatik maskelenir. Oturum sona erdiğinde mesaj geçmişi ziyaretçiye kapatılır.</Text></View>;
}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:54},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12},logo:{width:82,height:82,borderRadius:28,borderWidth:1,borderColor:palette.cyan+'50',backgroundColor:palette.cyan+'16',alignItems:'center',justifyContent:'center'},loadingTitle:{color:palette.text,fontSize:type.section,fontWeight:'900'},loadingBody:{color:palette.muted,fontSize:type.body},
  brand:{minHeight:80,flexDirection:'row',alignItems:'center',gap:11,marginBottom:16},brandIcon:{width:54,height:54,borderRadius:18,borderWidth:1,borderColor:palette.cyan+'45',backgroundColor:palette.cyan+'14',alignItems:'center',justifyContent:'center'},brandKicker:{color:palette.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.1},brandName:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},brandBody:{color:palette.muted,fontSize:type.caption,marginTop:3},secure:{borderRadius:999,borderWidth:1,borderColor:palette.green+'40',backgroundColor:palette.green+'0D',paddingHorizontal:9,paddingVertical:7,flexDirection:'row',alignItems:'center',gap:4},secureText:{color:palette.green,fontSize:type.micro,fontWeight:'900'},
  vehicle:{minHeight:146,borderRadius:radius.xl,borderWidth:1,borderColor:palette.cyan+'45',backgroundColor:palette.panel,padding:17,flexDirection:'row',alignItems:'center',gap:14},vehicleIcon:{width:68,height:68,borderRadius:23,backgroundColor:palette.cyan+'18',alignItems:'center',justifyContent:'center'},protected:{color:palette.cyan,fontSize:type.micro,fontWeight:'900',letterSpacing:.8},vehicleName:{color:palette.text,fontSize:23,fontWeight:'900',marginTop:4},vehicleBody:{color:palette.muted,fontSize:type.caption,marginTop:4},publicBadges:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:11},publicBadge:{minHeight:44,borderRadius:999,borderWidth:1,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:7},publicBadgeText:{fontSize:12.8,fontWeight:'900',letterSpacing:.38},
  privacy:{marginTop:11,minHeight:96,borderRadius:radius.lg,borderWidth:1,borderColor:palette.green+'3D',backgroundColor:palette.green+'0D',padding:15,flexDirection:'row',alignItems:'center',gap:12},privacyTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},privacyBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:4},
  messageEntry:{marginTop:16,minHeight:108,borderRadius:radius.lg,borderWidth:1,borderColor:palette.cyan+'70',backgroundColor:palette.cyan+'11',padding:15,flexDirection:'row',alignItems:'center',gap:12},messageEntryIcon:{width:56,height:56,borderRadius:18,backgroundColor:palette.cyan+'24',borderWidth:1,borderColor:palette.cyan+'62',alignItems:'center',justifyContent:'center'},messageEntryKicker:{color:palette.cyan,fontSize:9,fontWeight:'900',letterSpacing:1},messageEntryTitle:{color:palette.text,fontSize:21,fontWeight:'900',marginTop:2},messageEntryBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:3},
  compose:{marginTop:10,borderRadius:radius.lg,borderWidth:1,backgroundColor:'#071A25',padding:17},composeTop:{flexDirection:'row',alignItems:'flex-start',gap:10},composeClose:{width:36,height:36,borderRadius:12,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center'},composeLabel:{fontSize:type.micro,fontWeight:'900',letterSpacing:.8},composeTitle:{color:palette.text,fontSize:type.section,fontWeight:'900',marginTop:5},composeBody:{color:palette.muted,fontSize:type.body,lineHeight:21,marginTop:5},input:{minHeight:118,borderRadius:17,borderWidth:1,borderColor:palette.cyan+'38',backgroundColor:palette.bg2,color:palette.text,padding:14,textAlignVertical:'top',fontSize:type.body,marginTop:13},photoPick:{marginTop:10,minHeight:72,borderRadius:18,borderWidth:1,borderColor:palette.pink+'52',backgroundColor:palette.pink+'0D',padding:11,flexDirection:'row',alignItems:'center',gap:10},photoPickIcon:{width:45,height:45,borderRadius:14,backgroundColor:palette.pink+'1B',alignItems:'center',justifyContent:'center'},photoPickTitle:{color:palette.pink,fontSize:12,fontWeight:'900'},photoPickBody:{color:palette.muted,fontSize:11.5,marginTop:3},photoPreview:{marginTop:10,minHeight:82,borderRadius:18,borderWidth:1,borderColor:palette.green+'50',backgroundColor:palette.green+'0C',padding:9,flexDirection:'row',alignItems:'center',gap:10},photoImage:{width:62,height:62,borderRadius:13,backgroundColor:palette.bg2},photoTitle:{color:palette.text,fontSize:13.5,fontWeight:'900'},photoBody:{color:palette.muted,fontSize:11.5,marginTop:3},photoRemove:{width:40,height:40,borderRadius:13,borderWidth:1,borderColor:palette.red+'40',alignItems:'center',justifyContent:'center'},filter:{marginTop:10,flexDirection:'row',gap:9,alignItems:'center'},filterText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:18},inlineError:{color:palette.red,fontSize:type.caption,marginTop:10},send:{height:64,borderRadius:20,backgroundColor:palette.aqua,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9,marginTop:14},sendText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900'},
  grid:{flexDirection:'row',flexWrap:'wrap',gap:10},category:{width:'48.3%',minHeight:168,borderRadius:radius.md,borderWidth:1,padding:14},categoryIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},categoryTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900',lineHeight:20,marginTop:12},categoryBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},emergency:{alignSelf:'flex-start',borderRadius:999,backgroundColor:palette.red+'18',paddingHorizontal:8,paddingVertical:5,marginTop:8},emergencyText:{color:palette.red,fontSize:type.micro,fontWeight:'900'},
  promo:{marginTop:26,borderRadius:radius.xl,borderWidth:1,borderColor:palette.yellow+'62',backgroundColor:'#211807',padding:16,paddingTop:23,overflow:'hidden'},promoSweep:{position:'absolute',top:-60,bottom:-60,width:82,backgroundColor:'#FFFFFF12'},promoSpectrum:{position:'absolute',top:0,left:16,right:16,height:5,flexDirection:'row',gap:4},promoBar:{flex:1,borderRadius:99},promoHead:{flexDirection:'row',alignItems:'center',gap:12},promoIcon:{width:60,height:60,borderRadius:20,borderWidth:1,borderColor:palette.yellow+'62',backgroundColor:palette.yellow+'1A',alignItems:'center',justifyContent:'center'},promoKicker:{color:palette.yellow,fontSize:9,fontWeight:'900',letterSpacing:.8},promoTitle:{color:palette.text,fontSize:20,fontWeight:'900',marginTop:3},promoBody:{color:palette.muted,fontSize:type.caption,lineHeight:18,marginTop:4},shopGrid:{marginTop:14,gap:9},shopCard:{minHeight:66,borderRadius:18,borderWidth:1,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10},shopIcon:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center'},shopTitle:{color:palette.text,fontSize:13.5,fontWeight:'900'},shopBody:{color:palette.muted,fontSize:11.5,lineHeight:16,marginTop:2},promoLegal:{color:palette.muted2,fontSize:10.5,lineHeight:15,marginTop:12},
  chat:{marginTop:18},success:{minHeight:104,borderRadius:radius.lg,borderWidth:1,borderColor:palette.green+'40',backgroundColor:palette.green+'0D',padding:16,flexDirection:'row',alignItems:'center',gap:12},successTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},successBody:{color:palette.muted,fontSize:type.caption,lineHeight:19,marginTop:4},session:{marginTop:10,minHeight:52,borderRadius:16,backgroundColor:palette.cyan+'0D',paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:8},sessionText:{color:palette.cyan,fontSize:type.caption,fontWeight:'800'},messages:{marginTop:12,gap:9},wait:{color:palette.muted,fontSize:type.body,textAlign:'center',padding:24},bubble:{maxWidth:'88%',borderRadius:18,padding:13},ownerBubble:{alignSelf:'flex-start',backgroundColor:palette.green+'10',borderWidth:1,borderColor:palette.green+'35'},visitorBubble:{alignSelf:'flex-end',backgroundColor:palette.cyan+'10',borderWidth:1,borderColor:palette.cyan+'35'},bubbleWho:{color:palette.muted,fontSize:type.micro,fontWeight:'900'},bubbleText:{color:palette.text,fontSize:type.body,lineHeight:21,marginTop:4},bubbleTime:{color:palette.muted2,fontSize:type.micro,marginTop:6},chatRow:{flexDirection:'row',gap:9,marginTop:14},chatInput:{flex:1,height:58,borderRadius:17,borderWidth:1,borderColor:palette.line,backgroundColor:palette.bg2,color:palette.text,paddingHorizontal:14,fontSize:type.body},chatSend:{width:58,height:58,borderRadius:17,backgroundColor:palette.aqua,alignItems:'center',justifyContent:'center'},chatNote:{color:palette.muted2,fontSize:type.caption,lineHeight:18,marginTop:8},
  error:{marginTop:35,alignItems:'center',borderRadius:radius.lg,borderWidth:1,borderColor:palette.red+'45',backgroundColor:palette.red+'0E',padding:28},errorTitle:{color:palette.text,fontSize:type.section,fontWeight:'900',marginTop:12},errorBody:{color:palette.muted,fontSize:type.body,lineHeight:21,textAlign:'center',marginTop:6},footer:{color:palette.muted2,fontSize:type.caption,textAlign:'center',marginTop:28}
});