import fs from 'node:fs';
const dkd_read=dkd_file=>fs.readFileSync(dkd_file,'utf8');
const dkd_assert=(dkd_condition,dkd_message)=>{if(!dkd_condition){console.error('FAIL:',dkd_message);process.exitCode=1;}else console.log('PASS:',dkd_message);};
const dkd_app=JSON.parse(dkd_read('app.json')).expo;
const dkd_package=JSON.parse(dkd_read('package.json'));
const dkd_plus=dkd_read('src/components/DraBornParkPlusPanel.tsx');
const dkd_google=dkd_read('supabase/functions/dkd-drabornpark-google-play/index.ts');
const dkd_version=dkd_read('supabase/functions/dkd-drabornpark-app-version/index.ts');
dkd_assert(dkd_app.version==='1.0.22','app version is 1.0.22');
dkd_assert(dkd_app.android?.versionCode===22,'Android versionCode is 22');
dkd_assert(dkd_package.version==='1.0.22','package version is 1.0.22');
dkd_assert(dkd_google.includes('const VERSION="1.0.22"'),'billing Edge Function is v1.0.22');
dkd_assert(dkd_google.includes('dkd_v122'),'billing writes v1.0.22 audit state');
dkd_assert(dkd_google.includes('current_purchase_trial_snapshot'),'trial bonus is snapshotted from current purchase');
dkd_assert(dkd_google.includes('calculatedTrialDays=Math.min(14'),'trial bonus is bounded to 14 whole days');
dkd_assert(!dkd_google.includes('previousUserSubscription'),'a new purchase never inherits another purchase token trial bonus');
dkd_assert(!dkd_google.includes('previousUserBonus'),'legacy/refunded purchase bonus reuse is removed');
dkd_assert(dkd_plus.includes('SAHİP OLDUĞUN PLAN • Detayları gör'),'owned subscription card is visibly marked');
dkd_assert(dkd_plus.includes('setDkdInfoPopup(true)'),'owned subscription opens information popup');
dkd_assert(dkd_plus.includes('Etiket ödülü +${dkdOwnedTrialBonusDays} gün'),'popup explains trial reward days');
dkd_assert(dkd_plus.includes('dkdPaidPremium?Math.floor'),'paid premium day counter avoids one-day ceiling inflation');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION="1.0.22"'),'app-version service fallback is v1.0.22');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION_CODE=22'),'app-version service fallback versionCode is 22');
if(process.exitCode)process.exit(process.exitCode);console.log('DraBornPark v1.0.22 release checks passed.');
