import fs from 'node:fs';
const dkd_read=dkd_file=>fs.readFileSync(dkd_file,'utf8');
const dkd_assert=(dkd_condition,dkd_message)=>{if(!dkd_condition){console.error('FAIL:',dkd_message);process.exitCode=1;}else console.log('PASS:',dkd_message);};
const dkd_app=JSON.parse(dkd_read('app.json')).expo;
const dkd_package=JSON.parse(dkd_read('package.json'));
const dkd_factory=dkd_read('app/factory.tsx');
const dkd_admin=dkd_read('app/admin.tsx');
const dkd_legal=dkd_read('app/legal.tsx');
const dkd_google=dkd_read('supabase/functions/dkd-drabornpark-google-play/index.ts');
const dkd_version=dkd_read('supabase/functions/dkd-drabornpark-app-version/index.ts');

dkd_assert(dkd_app.version==='1.0.24','app version is 1.0.24');
dkd_assert(dkd_app.android?.versionCode===24,'Android versionCode is 24');
dkd_assert(dkd_package.version==='1.0.24','package version is 1.0.24');
dkd_assert(dkd_google.includes('const VERSION="1.0.24"'),'billing Edge Function source is v1.0.24');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION="1.0.24"'),'app-version fallback is v1.0.24');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION_CODE=24'),'app-version fallback versionCode is 24');
dkd_assert(dkd_factory.includes('public_alias,dkd_personal_alias,nfc_url'),'factory loads label-specific personal alias');
dkd_assert(dkd_factory.includes("dkd_drabornpark_factory_update_tag_v124"),'factory uses v1.0.24 personal URL RPC');
dkd_assert(dkd_factory.includes("dkd_friendly_url(dkd_tag.dkd_personal_alias||'')"),'factory personal URL button is label-specific');
dkd_assert(dkd_factory.includes('editable={!dkd_busy} style={s.input}'),'personal URL can be edited without owner gate');
dkd_assert(!dkd_factory.includes('tag_owner_required_for_username'),'factory no longer requires an owner to prepare personal URL');
dkd_assert(dkd_admin.includes('dkd_drabornpark_admin_search_users_v123'),'admin uses fixed premium-aware search RPC');
dkd_assert(dkd_admin.includes('PREMİUM KALAN'),'admin keeps remaining Premium days');
dkd_assert(dkd_legal.includes('v1.0.24'),'legal screen is v1.0.24');
dkd_assert(!dkd_factory.includes('v1.0.23'),'factory has no stale v1.0.23 label');
dkd_assert(!dkd_admin.includes('v1.0.23'),'admin has no stale v1.0.23 label');
if(process.exitCode)process.exit(process.exitCode);
console.log('DraBornPark v1.0.24 release checks passed.');
