import fs from 'node:fs';
const dkd_read=dkd_file=>fs.readFileSync(dkd_file,'utf8');
const dkd_require=(dkd_ok,dkd_label)=>{if(!dkd_ok)throw new Error(`DraBornPark v1.0.20 check failed: ${dkd_label}`)};
const dkd_app=JSON.parse(dkd_read('app.json')).expo;
const dkd_package=JSON.parse(dkd_read('package.json'));
const dkd_plus=dkd_read('src/components/DraBornParkPlusPanel.tsx');
const dkd_google=dkd_read('supabase/functions/dkd-drabornpark-google-play/index.ts');
const dkd_version=dkd_read('supabase/functions/dkd-drabornpark-app-version/index.ts');
dkd_require(dkd_app.version==='1.0.20','Expo version');
dkd_require(dkd_app.android?.versionCode===20,'Android versionCode');
dkd_require(dkd_package.version==='1.0.20','package version');
dkd_require(dkd_google.includes('const VERSION="1.0.20"'),'verifier version');
dkd_require(dkd_google.includes('orderHistory?.refundEvent'),'full refund detection');
dkd_require(dkd_google.includes('effectiveEntitled=!refunded'),'refund revokes entitlement');
dkd_require(dkd_google.includes('refundOrderId:dkdRefund.orderId'),'refund evidence stored');
dkd_require(dkd_google.includes('urn:ietf:params:oauth:grant-type:jwt-bearer'),'Google OAuth grant');
dkd_require(dkd_plus.includes('visible={dkdInfoPopup}'),'subscription info popup');
dkd_require(dkd_plus.includes('if(dkdPaidPremium)setDkdInfoPopup(true)'),'paid duration card popup');
dkd_require(dkd_plus.includes('dkdPaidPremium&&dkdOwnedPlanCardId===plan.id'),'owned Aylık/Yıllık card popup');
dkd_require(!dkd_plus.includes("Aylık ve yıllık güncel fiyatlar Google Play'den canlı alınır."),'price info paragraph removed');
dkd_require(dkd_plus.includes('raw_provider_state?.refunded!==true'),'server refund guard');
dkd_require(dkd_version.includes('FALLBACK_VERSION="1.0.20"'),'app version fallback');
console.log('DraBornPark v1.0.20 checks PASS.');
