import fs from 'node:fs';
const dkd_read=dkd_file=>fs.readFileSync(dkd_file,'utf8');
const dkd_assert=(dkd_condition,dkd_message)=>{if(!dkd_condition){console.error('FAIL:',dkd_message);process.exitCode=1;}else console.log('PASS:',dkd_message);};
const dkd_app=JSON.parse(dkd_read('app.json')).expo;
const dkd_package=JSON.parse(dkd_read('package.json'));
const dkd_factory=dkd_read('app/factory.tsx');
const dkd_admin=dkd_read('app/admin.tsx');
const dkd_google=dkd_read('supabase/functions/dkd-drabornpark-google-play/index.ts');
const dkd_version=dkd_read('supabase/functions/dkd-drabornpark-app-version/index.ts');
dkd_assert(dkd_app.version==='1.0.23','app version is 1.0.23');
dkd_assert(dkd_app.android?.versionCode===23,'Android versionCode is 23');
dkd_assert(dkd_package.version==='1.0.23','package version is 1.0.23');
dkd_assert(dkd_google.includes('const VERSION="1.0.23"'),'billing Edge Function is v1.0.23');
dkd_assert(dkd_google.includes('dkd_v122'),'v1.0.22 purchase snapshot protection remains intact');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION="1.0.23"'),'app-version service fallback is v1.0.23');
dkd_assert(dkd_version.includes('const FALLBACK_VERSION_CODE=23'),'app-version service fallback versionCode is 23');
dkd_assert(dkd_factory.includes("dkd_drabornpark_factory_update_tag_v123"),'factory uses v1.0.23 edit RPC');
dkd_assert(dkd_factory.includes("nfc_url:dkd_row.public_alias?dkd_physical_url"),'factory queue derives canonical /tag/ physical URL');
dkd_assert(dkd_factory.includes("KULLANICI ADI / KİŞİSEL BAĞLANTI"),'factory username editor remains available');
dkd_assert(dkd_admin.includes("dkd_drabornpark_admin_search_users_v123"),'admin uses v1.0.23 premium-aware search');
dkd_assert(dkd_admin.includes("dkd_drabornpark_admin_update_user_v123"),'admin uses v1.0.23 premium-day update');
dkd_assert(dkd_admin.includes('PREMİUM ABONELİK SÜRESİ EKLE (GÜN)'),'admin can add Premium subscription days');
dkd_assert(dkd_admin.includes('PREMİUM KALAN'),'admin shows remaining Premium days');
dkd_assert(!dkd_admin.includes('GÖRÜNEN AD'),'Admin User Management no longer exposes Display Name');
if(process.exitCode)process.exit(process.exitCode);console.log('DraBornPark v1.0.23 release checks passed.');
