import fs from 'node:fs';
const dkd_read=dkd_file=>fs.readFileSync(dkd_file,'utf8');
const dkd_require=(dkd_ok,dkd_label)=>{if(!dkd_ok)throw new Error(`DraBornPark v1.0.21 check failed: ${dkd_label}`)};
const dkd_app=JSON.parse(dkd_read('app.json')).expo;
const dkd_package=JSON.parse(dkd_read('package.json'));
const dkd_plus=dkd_read('src/components/DraBornParkPlusPanel.tsx');
const dkd_google=dkd_read('supabase/functions/dkd-drabornpark-google-play/index.ts');
const dkd_version=dkd_read('supabase/functions/dkd-drabornpark-app-version/index.ts');
const dkd_legal=dkd_read('app/legal.tsx');
dkd_require(dkd_app.version==='1.0.21','Expo version');
dkd_require(dkd_app.android?.versionCode===21,'Android versionCode');
dkd_require(dkd_package.version==='1.0.21','package version');
dkd_require(dkd_google.includes('const VERSION="1.0.21"'),'verifier version');
dkd_require(dkd_google.includes('purchase_already_claimed'),'purchase token ownership lock');
dkd_require(dkd_google.includes('purchase_missing_account_binding'),'new purchase account binding');
dkd_require(dkd_google.includes('externalAccountMatched=Boolean(obfuscated)&&obfuscated===expectedObfuscated'),'strict external account binding');
dkd_require(dkd_plus.includes('PLUS_OTHER_ACCOUNT'),'cross-account client state');
dkd_require(dkd_plus.includes('accountConflict:true'),'cross-account error classification');
dkd_require(dkd_plus.includes('obfuscatedProfileId:obfuscated'),'Google profile attribution');
dkd_require(dkd_plus.includes('farklı bir Google Play hesabıyla ayrı abonelik'),'actionable cross-account message');
dkd_require(dkd_plus.includes('raw_provider_state?.refunded!==true'),'refund guard');
dkd_require(dkd_google.includes('effectiveEntitled=!refunded'),'refund revokes entitlement');
dkd_require(dkd_version.includes('FALLBACK_VERSION="1.0.21"'),'app version fallback');
dkd_require(dkd_version.includes('FALLBACK_VERSION_CODE=21'),'app version code fallback');
dkd_require(dkd_legal.includes('v1.0.21'),'privacy version');
console.log('DraBornPark v1.0.21 checks PASS.');
