import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import {router,useLocalSearchParams} from 'expo-router';
import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {AuroraBackground,ScreenHeader,SectionHeading} from '@/src/components/AppChrome';
import {supabase} from '@/src/lib/supabase';
import {palette,radius,type} from '@/src/theme';

const states=[['open','Açık',palette.blue],['in_progress','İnceleniyor',palette.orange],['resolved','Çözüldü',palette.green],['closed','Kapalı',palette.muted]] as const;
export default function SupportDetailScreen(){
  const {id}=useLocalSearchParams<{id?:string}>();const supportId=String(id||'');const [row,setRow]=useState<any>(null);const [admin,setAdmin]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
  async function load(){setLoading(true);try{const {data:isAdmin}=await supabase.rpc('drabornpark_is_admin');setAdmin(Boolean(isAdmin));const {data,error}=await supabase.from('drabornpark_support_requests').select('*').eq('id',supportId).maybeSingle();if(error)throw error;if(!data){Alert.alert('Kayıt bulunamadı','Bu destek kaydını görüntüleme yetkin olmayabilir.',[{text:'Geri',onPress:()=>router.back()}]);return;}setRow(data);if(isAdmin&&!data.admin_seen_at){const {data:userData}=await supabase.auth.getUser();await supabase.from('drabornpark_support_requests').update({admin_seen_at:new Date().toISOString(),admin_seen_by:userData.user?.id??null,updated_at:new Date().toISOString()}).eq('id',supportId);setRow((current:any)=>({...current,admin_seen_at:new Date().toISOString()}));}}catch(error:any){Alert.alert('Destek kaydı açılamadı',error?.message||'Lütfen tekrar dene.');}finally{setLoading(false)}}
  useEffect(()=>{if(!supportId){router.back();return;}void load()},[supportId]);
  async function change(status:string){setBusy(true);try{const {data:userData}=await supabase.auth.getUser();const {data,error}=await supabase.from('drabornpark_support_requests').update({status,admin_seen_at:new Date().toISOString(),admin_seen_by:userData.user?.id??null,updated_at:new Date().toISOString()}).eq('id',supportId).select('*').single();if(error)throw error;setRow(data);}catch(error:any){Alert.alert('Durum değiştirilemedi',error?.message||'Lütfen tekrar dene.');}finally{setBusy(false)}}
  if(loading||!row)return <SafeAreaView style={s.safe}><AuroraBackground accent={palette.blue}/><View style={s.loading}><ActivityIndicator color={palette.blue}/><Text style={s.loadingText}>Destek kaydı açılıyor…</Text></View></SafeAreaView>;
  const current=states.find(([key])=>key===row.status)??states[0];
  return <SafeAreaView style={s.safe}><AuroraBackground accent={current[2]} secondary={palette.purple}/><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
    <ScreenHeader title="Destek Kaydı" eyebrow={admin?'ADMİN DESTEK MERKEZİ':'DESTEK MERKEZİ'} accent={current[2]} subtitle="Kayıt ayrıntısı ve güncel işlem durumu"/>
    <View style={[s.hero,{borderColor:`${current[2]}70`,backgroundColor:`${current[2]}12`}]}><View style={[s.heroIcon,{backgroundColor:`${current[2]}22`}]}><MaterialCommunityIcons name="lifebuoy" size={34} color={current[2]}/></View><View style={{flex:1}}><Text style={[s.status,{color:current[2]}]}>{current[1].toUpperCase()}</Text><Text style={s.title}>{row.subject}</Text><Text style={s.date}>{new Date(row.created_at).toLocaleString('tr-TR')}</Text></View></View>
    <SectionHeading title="Talep ayrıntısı" subtitle={`Kayıt • ${String(row.id).slice(0,8).toUpperCase()}`} color={palette.blue}/><View style={s.bodyCard}><Text style={s.body}>{row.body}</Text></View>
    {admin?<><SectionHeading title="Admin işlemi" subtitle="Kullanıcı bu durum değişikliğini Destek Merkezi'nde görür" color={palette.purple}/><View style={s.actions}>{states.map(([key,label,color])=><Pressable key={key} disabled={busy||row.status===key} onPress={()=>void change(key)} style={[s.action,{borderColor:`${color}70`,backgroundColor:row.status===key?`${color}25`:`${color}0D`,opacity:busy?.55:1}]}><MaterialCommunityIcons name={row.status===key?'check-circle':'circle-outline'} size={22} color={color}/><Text style={[s.actionText,{color}]}>{label}</Text></Pressable>)}</View><View style={s.adminInfo}><MaterialCommunityIcons name="account-shield-outline" size={23} color={palette.green}/><Text style={s.adminInfoText}>Bu kayıt admin hesabı tarafından görüldü. Bildirime dokunulduğunda doğrudan bu detay ekranı açılır.</Text></View></>:<View style={s.userInfo}><MaterialCommunityIcons name="clock-check-outline" size={23} color={current[2]}/><Text style={s.userInfoText}>Destek ekibi kayıt durumunu güncellediğinde en güncel durum burada görünür.</Text></View>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.bg},scroll:{padding:20,paddingBottom:55},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:11},loadingText:{color:palette.muted,fontSize:type.body},hero:{minHeight:140,borderRadius:radius.xl,borderWidth:1,padding:18,flexDirection:'row',alignItems:'center',gap:14},heroIcon:{width:68,height:68,borderRadius:23,alignItems:'center',justifyContent:'center'},status:{fontSize:type.micro,fontWeight:'900',letterSpacing:1.1},title:{color:palette.text,fontSize:23,fontWeight:'900',lineHeight:28,marginTop:4},date:{color:palette.muted,fontSize:type.caption,marginTop:5},bodyCard:{borderRadius:radius.lg,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:18},body:{color:palette.text,fontSize:type.body,lineHeight:24},actions:{flexDirection:'row',flexWrap:'wrap',gap:9},action:{width:'48.5%',minHeight:62,borderRadius:19,borderWidth:1,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8},actionText:{fontSize:type.caption,fontWeight:'900'},adminInfo:{marginTop:15,borderRadius:radius.md,borderWidth:1,borderColor:`${palette.green}45`,backgroundColor:`${palette.green}0D`,padding:14,flexDirection:'row',gap:10},adminInfoText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19},userInfo:{marginTop:22,borderRadius:radius.md,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:15,flexDirection:'row',gap:10},userInfoText:{flex:1,color:palette.muted,fontSize:type.caption,lineHeight:19}});
