import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import {router,useLocalSearchParams} from 'expo-router';
import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {loadLiveDashboard} from '@/src/lib/drabornpark';
import {supabase} from '@/src/lib/supabase';
import {palette,radius,type} from '@/src/theme';

export default function DkdActivatePublicToken(){
  const dkd_params=useLocalSearchParams<{token?:string}>();
  const dkd_token=String(dkd_params.token||'').trim();
  const [dkd_loading,setDkdLoading]=useState(true);
  const [dkd_session,setDkdSession]=useState<any>(null);
  const [dkd_vehicles,setDkdVehicles]=useState<any[]>([]);
  const [dkd_vehicle_id,setDkdVehicleId]=useState('');
  const [dkd_pin,setDkdPin]=useState('');
  const [dkd_busy,setDkdBusy]=useState(false);
  useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();setDkdSession(data.session);if(data.session){try{const dkd_dashboard=await loadLiveDashboard();setDkdVehicles(dkd_dashboard.vehicles);if(dkd_dashboard.vehicles[0])setDkdVehicleId(dkd_dashboard.vehicles[0].id);}catch{}}setDkdLoading(false)})()},[]);
  const dkd_activate=async()=>{if(!dkd_token||!dkd_vehicle_id||!dkd_pin.trim())return Alert.alert('Eksik bilgi','Araç ve kutudaki gizli aktivasyon PIN’i gerekli.');setDkdBusy(true);try{const {data,error}=await supabase.rpc('dkd_drabornpark_activate_public_token_v101',{dkd_public_token:dkd_token,dkd_pin:dkd_pin.trim(),dkd_vehicle_id});if(error)throw error;Alert.alert('Etiket aktive edildi',data?.rewardGranted?'Etiket aracına bağlandı ve 14 günlük DraBornPark+ ödülün eklendi.':'Etiket aracına güvenle bağlandı.',[{text:'TAMAM',onPress:()=>router.replace('/tags')}]);}catch(dkd_problem:any){const dkd_message=String(dkd_problem?.message||'');Alert.alert('Aktivasyon başarısız',dkd_message.includes('tag_not_found')?'Etiket bulunamadı.':dkd_message.includes('invalid')||dkd_message.includes('pin')?'Aktivasyon PIN’i eşleşmedi.':'Etiket aktive edilemedi.');}finally{setDkdBusy(false)}};
  if(dkd_loading)return <SafeAreaView style={dkd_styles.safe}><View style={dkd_styles.center}><ActivityIndicator color={palette.cyan}/><Text style={dkd_styles.muted}>Aktivasyon hazırlanıyor…</Text></View></SafeAreaView>;
  if(!dkd_session)return <SafeAreaView style={dkd_styles.safe}><View style={dkd_styles.centerCard}><MaterialCommunityIcons name="account-lock-outline" size={46} color={palette.cyan}/><Text style={dkd_styles.title}>Önce hesabına giriş yap</Text><Text style={dkd_styles.body}>Etiket sahipliği yalnızca giriş yapılmış DraBornPark hesabına, gizli PIN ve seçilen araç birlikte doğrulandığında bağlanır.</Text><Pressable onPress={()=>router.push('/auth')} style={dkd_styles.primary}><Text style={dkd_styles.primaryText}>GİRİŞ YAP / KAYIT OL</Text></Pressable><Text style={dkd_styles.hint}>Girişten sonra NFC/QR bağlantısını yeniden açabilirsin.</Text></View></SafeAreaView>;
  return <SafeAreaView style={dkd_styles.safe}><ScrollView contentContainerStyle={dkd_styles.scroll} showsVerticalScrollIndicator={false}><View style={dkd_styles.header}><MaterialCommunityIcons name="shield-key-outline" size={31} color={palette.cyan}/><View style={{flex:1}}><Text style={dkd_styles.kicker}>PUBLIC TOKEN + GİZLİ PIN</Text><Text style={dkd_styles.headerTitle}>Etiket Aktivasyonu</Text></View></View><View style={dkd_styles.info}><Text style={dkd_styles.infoTitle}>NFC ve QR aynı güvenli bağlantıyı kullanır</Text><Text style={dkd_styles.body}>Public token araç plakasını veya kullanıcı kimliğini URL içinde taşımaz. Aktivasyon tamamlandığında aynı fiziksel NFC/QR URL’si kalır.</Text></View><Text style={dkd_styles.label}>GİZLİ AKTİVASYON PIN</Text><TextInput value={dkd_pin} onChangeText={setDkdPin} secureTextEntry keyboardType="number-pad" placeholder="Kutudaki PIN" placeholderTextColor={palette.muted2} style={dkd_styles.input}/><Text style={dkd_styles.label}>ARACI SEÇ</Text><View style={dkd_styles.list}>{dkd_vehicles.map((dkd_vehicle)=><Pressable key={dkd_vehicle.id} onPress={()=>setDkdVehicleId(dkd_vehicle.id)} style={[dkd_styles.vehicle,dkd_vehicle_id===dkd_vehicle.id&&dkd_styles.vehicleOn]}><MaterialCommunityIcons name={dkd_vehicle.vehicle_type==='motorcycle'?'motorbike':'car-sports'} size={28} color={dkd_vehicle_id===dkd_vehicle.id?palette.cyan:palette.muted}/><View style={{flex:1}}><Text style={dkd_styles.vehicleTitle}>{dkd_vehicle.vehicle_name}</Text><Text style={dkd_styles.vehicleBody}>{[dkd_vehicle.plate,dkd_vehicle.brand,dkd_vehicle.model].filter(Boolean).join(' • ')||'Araç profili'}</Text></View>{dkd_vehicle_id===dkd_vehicle.id?<MaterialCommunityIcons name="check-circle" size={24} color={palette.green}/>:null}</Pressable>)}</View>{!dkd_vehicles.length?<Pressable onPress={()=>router.push('/vehicle')} style={dkd_styles.secondary}><Text style={dkd_styles.secondaryText}>ÖNCE ARAÇ EKLE</Text></Pressable>:null}<Pressable disabled={dkd_busy||!dkd_vehicle_id||!dkd_pin} onPress={()=>void dkd_activate()} style={[dkd_styles.primary,(dkd_busy||!dkd_vehicle_id||!dkd_pin)&&{opacity:.45}]}>{dkd_busy?<ActivityIndicator color={palette.ink}/>:<><MaterialCommunityIcons name="shield-check" size={23} color={palette.ink}/><Text style={dkd_styles.primaryText}>ETİKETİ GÜVENLİ AKTİVE ET</Text></>}</Pressable></ScrollView></SafeAreaView>;
}

const dkd_styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#050816'},scroll:{padding:20,paddingBottom:60},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12},centerCard:{flex:1,alignItems:'center',justifyContent:'center',padding:28},muted:{color:palette.muted,fontSize:type.body},header:{minHeight:72,flexDirection:'row',alignItems:'center',gap:12},kicker:{color:palette.cyan,fontSize:10,fontWeight:'900',letterSpacing:1.1},headerTitle:{color:palette.text,fontSize:27,fontWeight:'900',marginTop:3},info:{marginTop:14,borderRadius:radius.lg,borderWidth:1,borderColor:`${palette.cyan}45`,backgroundColor:palette.panel,padding:18},infoTitle:{color:palette.text,fontSize:type.cardTitle,fontWeight:'900'},title:{color:palette.text,fontSize:25,fontWeight:'900',textAlign:'center',marginTop:14},body:{color:palette.muted,fontSize:type.body,lineHeight:22,textAlign:'center',marginTop:8},hint:{color:palette.muted2,fontSize:type.caption,textAlign:'center',marginTop:13},label:{color:palette.cyan,fontSize:11,fontWeight:'900',letterSpacing:.8,marginTop:24,marginBottom:8},input:{height:58,borderRadius:18,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,color:palette.text,paddingHorizontal:15,fontSize:type.body},list:{gap:10},vehicle:{minHeight:82,borderRadius:18,borderWidth:1,borderColor:palette.line,backgroundColor:palette.panel,padding:14,flexDirection:'row',alignItems:'center',gap:12},vehicleOn:{borderColor:`${palette.cyan}66`,backgroundColor:`${palette.cyan}0D`},vehicleTitle:{color:palette.text,fontSize:type.bodyStrong,fontWeight:'900'},vehicleBody:{color:palette.muted,fontSize:type.caption,marginTop:3},primary:{minHeight:62,borderRadius:20,backgroundColor:palette.aqua,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:9,paddingHorizontal:18,marginTop:20},primaryText:{color:palette.ink,fontSize:type.bodyStrong,fontWeight:'900',textAlign:'center'},secondary:{minHeight:56,borderRadius:18,borderWidth:1,borderColor:palette.line,alignItems:'center',justifyContent:'center',marginTop:12},secondaryText:{color:palette.text,fontSize:type.caption,fontWeight:'900'}});
